/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { ArticleStatus } from './articleStatus';
import type { ArticleType } from './articleType';
import type { DeliverableType } from './deliverableType';
import type { PricingInformationDto } from './pricingInformationDto';

export interface ArticleListResultDto {
  id: string;
  /** The name of the article */
  name: string;
  /** The description of the article */
  description?: string;
  /** The status of the article */
  status: ArticleStatus;
  type: ArticleType;
  /** Associated Acquisition Flow */
  flow: string;
  /** Associated processing pipeline */
  pipeline?: string;
  /** Associated order configuration */
  orderingConfig: string;
  requiredDeliverableTypes?: DeliverableType[];
  pricingInformations?: PricingInformationDto;
}
