/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { AssetType } from './assetType';
import type { AddressDto } from './addressDto';
import type { AssetAccessDto } from './assetAccessDto';
import type { AssetTagDto } from './assetTagDto';
import type { AssetDtoExternalInformation } from './assetDtoExternalInformation';

export interface AssetDto {
  id: string;
  name: string;
  type: AssetType;
  address?: AddressDto;
  access?: AssetAccessDto;
  tags?: AssetTagDto[];
  externalInformation?: AssetDtoExternalInformation;
}
