/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { CapturePanoramaComponentDtoType } from './capturePanoramaComponentDtoType';
import type { TutorialDto } from './tutorialDto';
import type { InstructionDto } from './instructionDto';

export interface CapturePanoramaComponentDto {
  position: number;
  navigation?: string;
  type: CapturePanoramaComponentDtoType;
  tutorial: TutorialDto;
  startInstructions?: InstructionDto[];
  endInstructions?: InstructionDto[];
}
