"use strict";
/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CapturePanoramaV2ComponentDtoMultibracket = void 0;
// eslint-disable-next-line @typescript-eslint/no-redeclare
exports.CapturePanoramaV2ComponentDtoMultibracket = {
    NO_BRACKET: 'NO_BRACKET',
    BRACKET_3: 'BRACKET_3',
    BRACKET_5: 'BRACKET_5',
    BRACKET_7: 'BRACKET_7',
};
