"use strict";
/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CaptureType = void 0;
// eslint-disable-next-line @typescript-eslint/no-redeclare
exports.CaptureType = {
    CAR: 'CAR',
    ROOM: 'ROOM',
    HOUSING: 'HOUSING',
    OTHER: 'OTHER',
    FREE: 'FREE',
};
