"use strict";
/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CapturePanoramaV2ComponentDtoType = void 0;
// eslint-disable-next-line @typescript-eslint/no-redeclare
exports.CapturePanoramaV2ComponentDtoType = {
    CAPTURE_PANORAMA_V2: 'CAPTURE_PANORAMA_V2',
};
