/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export type CaptureCodec = (typeof CaptureCodec)[keyof typeof CaptureCodec];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CaptureCodec = {
  H265: 'H265',
} as const;
