/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export type CaptureComponentDtoType =
  (typeof CaptureComponentDtoType)[keyof typeof CaptureComponentDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CaptureComponentDtoType = {
  CAPTURE: 'CAPTURE',
} as const;
