/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export type ClientOrderItemStatus =
  (typeof ClientOrderItemStatus)[keyof typeof ClientOrderItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClientOrderItemStatus = {
  CREATING: 'CREATING',
  PENDING: 'PENDING',
  ASSIGNED: 'ASSIGNED',
  SCHEDULED: 'SCHEDULED',
  COMPLETED: 'COMPLETED',
  AMENDED: 'AMENDED',
  CANCELED: 'CANCELED',
} as const;
