/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { ConnectionComponentDtoType } from './connectionComponentDtoType';
import type { TutorialDto } from './tutorialDto';

export interface ConnectionComponentDto {
  position: number;
  navigation?: string;
  type: ConnectionComponentDtoType;
  tutorial: TutorialDto;
}
