"use strict";
/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DeliverableCubemapDtoType = void 0;
// eslint-disable-next-line @typescript-eslint/no-redeclare
exports.DeliverableCubemapDtoType = {
    img_high_res: 'img_high_res',
    img_low_res: 'img_low_res',
    depth_map: 'depth_map',
    normal_map: 'normal_map',
};
