"use strict";
/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DeliverableStatus = void 0;
// eslint-disable-next-line @typescript-eslint/no-redeclare
exports.DeliverableStatus = {
    ERROR: 'ERROR',
    PENDING: 'PENDING',
    PROCESSING: 'PROCESSING',
    PROCESSED: 'PROCESSED',
    POST_PROCESSED: 'POST_PROCESSED',
    VALIDATED: 'VALIDATED',
    PUBLISHED: 'PUBLISHED',
    CANCELED: 'CANCELED',
    REJECTED: 'REJECTED',
};
