/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { DeliverableRoomDto } from './deliverableRoomDto';
import type { DeliverableMinimapDto } from './deliverableMinimapDto';
import type { DeliverableFloorplanDto } from './deliverableFloorplanDto';

export interface DeliverableLevelDto {
  level_uuid: string;
  level_name: string;
  rooms: DeliverableRoomDto[];
  minimaps: DeliverableMinimapDto[];
  /** @deprecated */
  floorplans?: DeliverableFloorplanDto[];
  scene_object_uuids: string[];
  is_floor: boolean;
}
