/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export type DeliverableType =
  (typeof DeliverableType)[keyof typeof DeliverableType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeliverableType = {
  SHOWROOM: 'SHOWROOM',
  ROOMPLANS: 'ROOMPLANS',
  VIRTUAL_TOUR: 'VIRTUAL_TOUR',
  GAUSSIAN_SPLATTING: 'GAUSSIAN_SPLATTING',
  FLYTHROUGH: 'FLYTHROUGH',
  REPORT: 'REPORT',
  COSTING: 'COSTING',
  LINK: 'LINK',
  ENERGY_PERFORMANCE_DIAGNOSTICS: 'ENERGY_PERFORMANCE_DIAGNOSTICS',
} as const;
