/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export type DeliverableMinimapDtoPanoramaUuidsPoses2dItem = {
  panorama_uuid: string;
  x: number;
  y: number;
};
