/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export type DeliverableStatus =
  (typeof DeliverableStatus)[keyof typeof DeliverableStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeliverableStatus = {
  ERROR: 'ERROR',
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  PROCESSED: 'PROCESSED',
  POST_PROCESSED: 'POST_PROCESSED',
  VALIDATED: 'VALIDATED',
  PUBLISHED: 'PUBLISHED',
  CANCELED: 'CANCELED',
  REJECTED: 'REJECTED',
} as const;
