/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { DeliverablePose3d } from './deliverablePose3d';

export interface DeliverableCameraPathDto {
  cx: number;
  cy: number;
  fx: number;
  fy: number;
  poses: DeliverablePose3d[];
}
