/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { DeliverableLevelDto } from './deliverableLevelDto';
import type { DeliverableSceneDto } from './deliverableSceneDto';
import type { DeliverablePanoramaDto } from './deliverablePanoramaDto';
import type { DeliverableGeometryDto } from './deliverableGeometryDto';
import type { DeliverableVirtualTourDtoStartInfo } from './deliverableVirtualTourDtoStartInfo';

export interface DeliverableVirtualTourDto {
  version: string;
  levels: DeliverableLevelDto[];
  scene: DeliverableSceneDto[];
  list_panoramas: DeliverablePanoramaDto[];
  list_geometries: DeliverableGeometryDto[];
  start_info: DeliverableVirtualTourDtoStartInfo;
}
