/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { DeliverableCubemapDtoType } from './deliverableCubemapDtoType';

export interface DeliverableCubemapDto {
  type: DeliverableCubemapDtoType;
  front: string;
  back: string;
  left: string;
  right: string;
  up: string;
  down: string;
}
