/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export interface DeliverablePose3d {
  /**
   * @minItems 3
   * @maxItems 3
   */
  center: number[];
  /**
   * @minItems 9
   * @maxItems 9
   */
  rotation: number[];
}
