/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export type DeliverableAnnotationDtoSrcType =
  (typeof DeliverableAnnotationDtoSrcType)[keyof typeof DeliverableAnnotationDtoSrcType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeliverableAnnotationDtoSrcType = {
  annotations: 'annotations',
  inventory: 'inventory',
  form: 'form',
} as const;
