/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export type ExportedCapturePanoramaV2DtoType =
  (typeof ExportedCapturePanoramaV2DtoType)[keyof typeof ExportedCapturePanoramaV2DtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExportedCapturePanoramaV2DtoType = {
  EXPORTED_CAPTURE_PANORAMA_V2: 'EXPORTED_CAPTURE_PANORAMA_V2',
} as const;
