/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { ExportedCapturePanoramaDtoType } from './exportedCapturePanoramaDtoType';
import type { CameraDto } from './cameraDto';
import type { ExportedCapturePanoramaDtoItemsItem } from './exportedCapturePanoramaDtoItemsItem';

export interface ExportedCapturePanoramaDto {
  id: string;
  type: ExportedCapturePanoramaDtoType;
  camera: CameraDto;
  items: ExportedCapturePanoramaDtoItemsItem[];
}
