/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export type ExportedListDtoType =
  (typeof ExportedListDtoType)[keyof typeof ExportedListDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExportedListDtoType = {
  EXPORTED_LIST: 'EXPORTED_LIST',
} as const;
