/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export type ExportedAnnotationPanoramaDtoType =
  (typeof ExportedAnnotationPanoramaDtoType)[keyof typeof ExportedAnnotationPanoramaDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExportedAnnotationPanoramaDtoType = {
  EXPORTED_ANNOTATION_PANORAMA: 'EXPORTED_ANNOTATION_PANORAMA',
} as const;
