/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { ExportedListDtoType } from './exportedListDtoType';
import type { ExportedListItemDto } from './exportedListItemDto';

export interface ExportedListDto {
  id: string;
  type: ExportedListDtoType;
  items: ExportedListItemDto[];
}
