/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export type ExportedCaptureCategory =
  (typeof ExportedCaptureCategory)[keyof typeof ExportedCaptureCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExportedCaptureCategory = {
  CAR: 'CAR',
  HOUSING: 'HOUSING',
  FREE: 'FREE',
  ROOM: 'ROOM',
  OTHER: 'OTHER',
} as const;
