/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export type ExtractRoomplanComponentDtoItemType =
  (typeof ExtractRoomplanComponentDtoItemType)[keyof typeof ExtractRoomplanComponentDtoItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExtractRoomplanComponentDtoItemType = {
  SURFACE: 'SURFACE',
  ROOM: 'ROOM',
} as const;
