/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export type ExtractRoomplanItemType =
  (typeof ExtractRoomplanItemType)[keyof typeof ExtractRoomplanItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExtractRoomplanItemType = {
  SURFACE: 'SURFACE',
  ROOM: 'ROOM',
} as const;
