/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { FieldType } from './fieldType';
import type { FieldDto } from './fieldDto';

export interface FieldValueDto {
  type: FieldType;
  /** @minLength 2 */
  label: string;
  field: FieldDto;
  value: string[];
  enabled?: boolean;
}
