"use strict";
/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.FieldType = void 0;
// eslint-disable-next-line @typescript-eslint/no-redeclare
exports.FieldType = {
    TEXT: 'TEXT',
    SELECT: 'SELECT',
    RADIO: 'RADIO',
    CHECKBOX: 'CHECKBOX',
    FILE: 'FILE',
    EMAIL: 'EMAIL',
    PHONE: 'PHONE',
    DATE: 'DATE',
    TIME: 'TIME',
    TEXTAREA: 'TEXTAREA',
    URL: 'URL',
    NUMBER: 'NUMBER',
    DIVIDER: 'DIVIDER',
    RGBD: 'RGBD',
    SIGNATURE: 'SIGNATURE',
};
