/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export type ListComponentDisplayMode =
  (typeof ListComponentDisplayMode)[keyof typeof ListComponentDisplayMode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListComponentDisplayMode = {
  THUMBNAIL: 'THUMBNAIL',
  LIST: 'LIST',
  LIST_THUMBNAILS: 'LIST_THUMBNAILS',
} as const;
