/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export type OrderingConfigWorkflowType =
  (typeof OrderingConfigWorkflowType)[keyof typeof OrderingConfigWorkflowType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderingConfigWorkflowType = {
  defaultOrderingWorkflow: 'defaultOrderingWorkflow',
  keyDepositWorkflow: 'keyDepositWorkflow',
  keyWithdrawalWorkflow: 'keyWithdrawalWorkflow',
  visitOrderingWorkflow: 'visitOrderingWorkflow',
  dpeOrderingWorkflow: 'dpeOrderingWorkflow',
} as const;
