/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { PipelineImageProcessingDto } from './pipelineImageProcessingDto';
import type { PipelineNavigationDto } from './pipelineNavigationDto';
import type { PipelineDigitalTwinDto } from './pipelineDigitalTwinDto';

export interface PipelineVirtualTourDto {
  imageProcessing?: PipelineImageProcessingDto;
  navigation?: PipelineNavigationDto;
  digitalTwin?: PipelineDigitalTwinDto;
}
