/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { PipelineReportDto } from './pipelineReportDto';
import type { PipelineRoomplansDto } from './pipelineRoomplansDto';
import type { PipelineCostingDto } from './pipelineCostingDto';
import type { PipelineVirtualTourDto } from './pipelineVirtualTourDto';
import type { PipelineFlowDto } from './pipelineFlowDto';
import type { PipelineGaussianSplattingDto } from './pipelineGaussianSplattingDto';

export interface PipelineJsonDto {
  report?: PipelineReportDto;
  roomplans?: PipelineRoomplansDto;
  costing?: PipelineCostingDto;
  virtualTour?: PipelineVirtualTourDto;
  flow?: PipelineFlowDto;
  gaussianSplatting?: PipelineGaussianSplattingDto;
}
