/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export type Player360ComponentDtoType =
  (typeof Player360ComponentDtoType)[keyof typeof Player360ComponentDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Player360ComponentDtoType = {
  PLAYER_360: 'PLAYER_360',
} as const;
