/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { PlayerVideoComponentDtoAnnotationsItem } from './playerVideoComponentDtoAnnotationsItem';
import type { PlayerVideoComponentDtoType } from './playerVideoComponentDtoType';

export interface PlayerVideoComponentDto {
  position: number;
  navigation?: string;
  annotations?: PlayerVideoComponentDtoAnnotationsItem[];
  type: PlayerVideoComponentDtoType;
}
