/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { FieldValueDto } from './fieldValueDto';

export interface SubmittedFormDto {
  /** @minLength 2 */
  name: string;
  fieldValues: FieldValueDto[];
  enabled?: boolean;
}
