/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export interface SurfaceRangeDto {
  /** The value to replace the placeholder with */
  skuValue: string;
  /** The min value of the range */
  min: number;
  /** The max value of the range */
  max: number;
}
