/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export type SwitchConditionDtoOperator =
  (typeof SwitchConditionDtoOperator)[keyof typeof SwitchConditionDtoOperator];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SwitchConditionDtoOperator = {
  EQUALS: 'EQUALS',
  NOT_EQUALS: 'NOT_EQUALS',
  CONTAINS: 'CONTAINS',
  NOT_CONTAINS: 'NOT_CONTAINS',
  GREATER_THAN: 'GREATER_THAN',
  LESS_THAN: 'LESS_THAN',
  GREATER_THAN_OR_EQUAL: 'GREATER_THAN_OR_EQUAL',
  LESS_THAN_OR_EQUAL: 'LESS_THAN_OR_EQUAL',
  REGEX_MATCH: 'REGEX_MATCH',
} as const;
