/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { SwitchConditionDtoOperator } from './switchConditionDtoOperator';

export interface SwitchConditionDto {
  operator: SwitchConditionDtoOperator;
  /** @minLength 1 */
  value: string;
  /** @minLength 1 */
  label: string;
  /** @minimum 0 */
  index: number;
}
