/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export interface TooltipDto {
  /** @minLength 2 */
  title: string;
  /** @minLength 5 */
  description?: string;
  iconUrl?: string;
}
