/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { CreateFlowDto } from './createFlowDto';
import type { CreatePipelineDto } from './createPipelineDto';
import type { CreateOrderingConfigDto } from './createOrderingConfigDto';
import type { DeliverableType } from './deliverableType';
import type { PricingInformationDto } from './pricingInformationDto';

export interface ArticleValidateDto {
  id: string;
  /** The associated acquisition flow */
  flow: CreateFlowDto;
  /** The associated processing pipeline */
  pipeline?: CreatePipelineDto;
  /** The associated order configuration */
  orderingConfig: CreateOrderingConfigDto;
  requiredDeliverableTypes?: DeliverableType[];
  pricingInformations?: PricingInformationDto;
}
