/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */

export type AssetCriteria = (typeof AssetCriteria)[keyof typeof AssetCriteria];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssetCriteria = {
  TYPOLOGY: 'TYPOLOGY',
  HOUSING_TYPE: 'HOUSING_TYPE',
  HOUSING_STATE: 'HOUSING_STATE',
  ZONE: 'ZONE',
  SURFACE: 'SURFACE',
  RENTAL_TYPE: 'RENTAL_TYPE',
} as const;
