/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { AssetType } from './assetType';
import type { AddressDto } from './addressDto';
import type { AssetAccessDto } from './assetAccessDto';
import type { AssetTagDto } from './assetTagDto';
import type { AssetDtoExternalInformation } from './assetDtoExternalInformation';
import type { AssetDtoOrderKeys } from './assetDtoOrderKeys';
import type { AssetCriterionDto } from './assetCriterionDto';

export interface AssetDto {
  id: string;
  name: string;
  type: AssetType;
  address?: AddressDto;
  client: string;
  access?: AssetAccessDto;
  tags?: AssetTagDto[];
  externalInformation?: AssetDtoExternalInformation;
  orderKeys: AssetDtoOrderKeys;
  criteria?: AssetCriterionDto[];
}
