/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { CaptureComponentDtoType } from './captureComponentDtoType';
import type { CaptureDto } from './captureDto';
import type { TutorialDto } from './tutorialDto';
import type { InstructionDto } from './instructionDto';

export interface CaptureComponentDto {
  position: number;
  navigation?: string;
  type: CaptureComponentDtoType;
  capture: CaptureDto;
  tutorial: TutorialDto;
  startInstructions?: InstructionDto[];
  endInstructions?: InstructionDto[];
}
