/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */

export type CapturePanoramaV2ComponentDtoMultibracket =
  (typeof CapturePanoramaV2ComponentDtoMultibracket)[keyof typeof CapturePanoramaV2ComponentDtoMultibracket];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CapturePanoramaV2ComponentDtoMultibracket = {
  NO_BRACKET: 'NO_BRACKET',
  BRACKET_3: 'BRACKET_3',
  BRACKET_5: 'BRACKET_5',
  BRACKET_7: 'BRACKET_7',
} as const;
