/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { ClientUpdateDtoBillingAddress } from './clientUpdateDtoBillingAddress';
import type { AccountUpdateDto } from './accountUpdateDto';

export interface ClientUpdateDto {
  id: string;
  billingAddress?: ClientUpdateDtoBillingAddress;
  account: AccountUpdateDto;
  group?: string;
}
