/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { DeliverableType } from './deliverableType';
import type { ClientDeliverableAction } from './clientDeliverableAction';

export interface ClientDeliverableParametersDto {
  id: string;
  article: string;
  deliverableType: DeliverableType;
  publishingWorkflowType?: string;
  postProcessingActions?: ClientDeliverableAction[];
  QA: boolean;
}
