/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { ArticleDto } from './articleDto';
import type { AssetDto } from './assetDto';
import type { ClientOrderDto } from './clientOrderDto';
import type { ClientDto } from './clientDto';
import type { ClientOrderItemStatus } from './clientOrderItemStatus';
import type { OrderItemInvoicingStatus } from './orderItemInvoicingStatus';
import type { ClientOrderItemCriterionDto } from './clientOrderItemCriterionDto';

export interface ClientOrderItemDto {
  id: string;
  itemNumber: string;
  article: ArticleDto;
  asset: AssetDto;
  dueDate?: string;
  price: number;
  vat: number;
  clientOrder: ClientOrderDto;
  client: ClientDto;
  operationalStatus: ClientOrderItemStatus;
  invoicingStatus: OrderItemInvoicingStatus;
  invoiceNumber?: string;
  orderContext?: ClientOrderItemCriterionDto[];
  legacyForm?: string;
  fromODS?: boolean;
  createdAt: string;
  updatedAt: string;
}
