/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { CaptureComponentDto } from './captureComponentDto';
import type { CapturePanoramaComponentDto } from './capturePanoramaComponentDto';
import type { CapturePanoramaV2ComponentDto } from './capturePanoramaV2ComponentDto';
import type { ConnectionComponentDto } from './connectionComponentDto';
import type { DeconnectionComponentDto } from './deconnectionComponentDto';
import type { ExportComponentDto } from './exportComponentDto';
import type { ExtractRoomplanComponentDto } from './extractRoomplanComponentDto';
import type { FormComponentDto } from './formComponentDto';
import type { ListComponentDto } from './listComponentDto';
import type { Player360ComponentDto } from './player360ComponentDto';
import type { PlayerVideoComponentDto } from './playerVideoComponentDto';
import type { ReportComponentDto } from './reportComponentDto';
import type { AnnotationPanoramaComponentDto } from './annotationPanoramaComponentDto';
import type { SwitchComponentDto } from './switchComponentDto';

export type ComponentsDtoItem =
  | CaptureComponentDto
  | CapturePanoramaComponentDto
  | CapturePanoramaV2ComponentDto
  | ConnectionComponentDto
  | DeconnectionComponentDto
  | ExportComponentDto
  | ExtractRoomplanComponentDto
  | FormComponentDto
  | ListComponentDto
  | Player360ComponentDto
  | PlayerVideoComponentDto
  | ReportComponentDto
  | AnnotationPanoramaComponentDto
  | SwitchComponentDto;
