/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { AssetType } from './assetType';
import type { CreateAddressDto } from './createAddressDto';
import type { CreateAssetAccessDto } from './createAssetAccessDto';
import type { CreateAssetTagDto } from './createAssetTagDto';
import type { CreateAssetDtoExternalInformation } from './createAssetDtoExternalInformation';
import type { AssetCriterionDto } from './assetCriterionDto';
import type { CreateAssetDtoOrderKeys } from './createAssetDtoOrderKeys';

export interface CreateAssetDto {
  /** @minLength 2 */
  name: string;
  type: AssetType;
  address: CreateAddressDto;
  client: string;
  access?: CreateAssetAccessDto;
  tags: CreateAssetTagDto[];
  externalInformation?: CreateAssetDtoExternalInformation;
  criteria?: AssetCriterionDto[];
  orderKeys: CreateAssetDtoOrderKeys;
}
