/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { PipelineJsonDto } from './pipelineJsonDto';

export interface CreatePipelineDto {
  /**
   * The name of the pipeline
   * @minLength 2
   */
  name: string;
  /**
   * The description of the pipeline
   * @minLength 2
   */
  description?: string;
  json: PipelineJsonDto;
}
