/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { FlowJsonDto } from './flowJsonDto';

export interface CreateFlowDto {
  /** @minLength 2 */
  name: string;
  /** @minLength 2 */
  description?: string;
  imageUrl?: string;
  json: FlowJsonDto;
}
