/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { DeliverableMaskDto } from './deliverableMaskDto';
import type { DeliverableCubemapDto } from './deliverableCubemapDto';
import type { DeliverableAnnotationDto } from './deliverableAnnotationDto';
import type { DeliverableVisibilityDto } from './deliverableVisibilityDto';

export interface DeliverablePanoramaDto {
  panorama_uuid: string;
  icon_path: string;
  masks?: DeliverableMaskDto[];
  cubemaps: DeliverableCubemapDto[];
  annotations: DeliverableAnnotationDto[];
  visibilities: DeliverableVisibilityDto[];
}
