/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { DeliverableSceneDtoGeometryUuidPose3d } from './deliverableSceneDtoGeometryUuidPose3d';
import type { DeliverableSceneDtoPanoramaUuidsPoses3dItem } from './deliverableSceneDtoPanoramaUuidsPoses3dItem';

export interface DeliverableSceneDto {
  scene_object_uuid: string;
  geometry_uuid_pose_3d?: DeliverableSceneDtoGeometryUuidPose3d;
  panorama_uuids_poses_3d: DeliverableSceneDtoPanoramaUuidsPoses3dItem[];
}
