/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { DeliverableAnnotationDtoReferenceUuid } from './deliverableAnnotationDtoReferenceUuid';
import type { DeliverableAnnotationDtoSrcType } from './deliverableAnnotationDtoSrcType';
import type { DeliverablePose3d } from './deliverablePose3d';

export interface DeliverableAnnotationDto {
  annotation_uuid: string;
  reference_uuid: DeliverableAnnotationDtoReferenceUuid;
  src_type: DeliverableAnnotationDtoSrcType;
  pose_3d: DeliverablePose3d;
  geometry_uuid?: string;
  label?: string;
}
