/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */

export type DeliverableGeometryDtoType =
  (typeof DeliverableGeometryDtoType)[keyof typeof DeliverableGeometryDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeliverableGeometryDtoType = {
  potree_v1: 'potree_v1',
  potree_v2: 'potree_v2',
  gltf: 'gltf',
  obj: 'obj',
} as const;
