/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */

export interface DeliverableAabb {
  /**
   * @minItems 3
   * @maxItems 3
   */
  pmin: number[];
  /**
   * @minItems 3
   * @maxItems 3
   */
  pmax: number[];
}
