/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { ExportedCaptureDtoType } from './exportedCaptureDtoType';
import type { Device } from './device';
import type { ExportedCaptureCategory } from './exportedCaptureCategory';

export interface ExportedCaptureDto {
  id: string;
  type: ExportedCaptureDtoType;
  device: Device;
  category: ExportedCaptureCategory;
}
