/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { ExportedAnnotationPanoramaDtoType } from './exportedAnnotationPanoramaDtoType';
import type { SubmittedFormDto } from './submittedFormDto';
import type { ExportedAnnotationPanoramaPosition } from './exportedAnnotationPanoramaPosition';

export interface ExportedAnnotationPanoramaDto {
  id: string;
  type: ExportedAnnotationPanoramaDtoType;
  forms: SubmittedFormDto[];
  panoramaId: string;
  position: ExportedAnnotationPanoramaPosition;
}
