/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { OrderResultJsonDto } from './orderResultJsonDto';

export interface FeeDto {
  /** Id for the created client fee */
  clientFeeId: string;
  articleId: string;
  orderResult: OrderResultJsonDto;
  clientAmount?: number;
  supplierAmount: number;
  /** Supplier Order Item Id to link the fee to */
  supplierOrderItemId: string;
  amend: boolean;
}
