/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { MissionDetailsDto } from './missionDetailsDto';
import type { ComponentsDto } from './componentsDto';

export interface FlowJsonDto {
  missionDetails?: MissionDetailsDto;
  tasks?: string[];
  equipments?: string[];
  components: ComponentsDto;
}
