/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */

export type GetAssetsParams = {
  /**
   * @minimum 1
   * @maximum 100
   */
  perPage?: number;
  /**
   * @minimum 1
   */
  page?: number;
  sortBy?: string;
  reference?: string;
  owner?: string;
  city?: string;
};
