/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { ClientOrderItemStatus } from './clientOrderItemStatus';
import type { OrderItemInvoicingStatus } from './orderItemInvoicingStatus';

export type GetClientOrderItemsParams = {
  /**
   * @minimum 1
   * @maximum 100
   */
  perPage?: number;
  /**
   * @minimum 1
   */
  page?: number;
  sortBy?: string;
  article?: string;
  client?: string;
  operationalStatus?: ClientOrderItemStatus[];
  invoicingStatus?: OrderItemInvoicingStatus[];
  itemNumber?: string;
  orderNumber?: string;
  assetReference?: string;
  articleName?: string;
  createdAt?: string;
  ids?: string[];
};
