/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { Paginated } from './paginated';
import type { GetProjects200AllOf } from './getProjects200AllOf';

export type GetProjects200 = Paginated & GetProjects200AllOf;
