/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { SupplierOrderItemStatus } from './supplierOrderItemStatus';

export type GetSupplierOrderItemsParams = {
  /**
   * @minimum 1
   * @maximum 100
   */
  perPage?: number;
  /**
   * @minimum 1
   */
  page?: number;
  sortBy?: string;
  supplierOrderItemNumber?: string;
  suplierOrderNumber?: string;
  supplierId?: string;
  clientId?: string;
  clientOrderItemNumber?: string;
  assetName?: string;
  supplierOrderItemStatus?: SupplierOrderItemStatus[];
  dueBefore?: string;
};
