/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { SupplierOrderStatus } from './supplierOrderStatus';

export type GetSupplierOrdersBySupplierIdParams = {
  /**
   * @minimum 1
   * @maximum 100
   */
  perPage?: number;
  /**
   * @minimum 1
   */
  page?: number;
  sortBy?: string;
  supplierOrderStatus?: SupplierOrderStatus[];
  supplierOrderNumber?: string;
  createdAfter?: string;
  createdBefore?: string;
};
