/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */

export type LegalStatus = (typeof LegalStatus)[keyof typeof LegalStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LegalStatus = {
  SARL: 'SARL',
  SA: 'SA',
  EURL: 'EURL',
  SAS: 'SAS',
  SASU: 'SASU',
  SCI: 'SCI',
  EI: 'EI',
} as const;
