/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */

export type OrderItemInvoicingStatus =
  (typeof OrderItemInvoicingStatus)[keyof typeof OrderItemInvoicingStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderItemInvoicingStatus = {
  PENDING: 'PENDING',
  BILLABLE: 'BILLABLE',
  BILLED: 'BILLED',
  PAID: 'PAID',
  NOT_BILLABLE: 'NOT_BILLABLE',
} as const;
