/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { DeliverableType } from './deliverableType';
import type { ClientOrderItemStatus } from './clientOrderItemStatus';

export interface PaginatedProjectDto {
  id: string;
  projectName: string;
  isActive: boolean;
  user: string;
  articleName: string;
  deliverableTypes?: DeliverableType[];
  status: ClientOrderItemStatus;
}
