/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { Player360ComponentDtoAnnotationsItem } from './player360ComponentDtoAnnotationsItem';
import type { Player360ComponentDtoType } from './player360ComponentDtoType';

export interface Player360ComponentDto {
  position: number;
  navigation?: string;
  annotations?: Player360ComponentDtoAnnotationsItem[];
  type: Player360ComponentDtoType;
}
