/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */

export type SupplierOrderItemStatus =
  (typeof SupplierOrderItemStatus)[keyof typeof SupplierOrderItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SupplierOrderItemStatus = {
  SCHEDULED: 'SCHEDULED',
  ACCEPTED: 'ACCEPTED',
  REFUSED: 'REFUSED',
  AMENDED: 'AMENDED',
  CANCELED: 'CANCELED',
  RECEIVED: 'RECEIVED',
  COMPLETED: 'COMPLETED',
  ERROR: 'ERROR',
} as const;
