/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { ClientOrderItemDto } from './clientOrderItemDto';
import type { SupplierOrderDto } from './supplierOrderDto';
import type { ArticleDto } from './articleDto';
import type { SupplierOrderItemStatus } from './supplierOrderItemStatus';
import type { OrderItemInvoicingStatus } from './orderItemInvoicingStatus';

export interface SupplierOrderItemDto {
  id: string;
  itemNumber: string;
  price: number;
  date: string;
  vat: number;
  clientOrderItem?: ClientOrderItemDto;
  supplierOrder: SupplierOrderDto;
  article: ArticleDto;
  operationalStatus: SupplierOrderItemStatus;
  invoicingStatus: OrderItemInvoicingStatus;
  invoiceNumber?: string;
  createdAt: string;
  updatedAt: string;
  archiveUrl: string;
}
