/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { TutorialDtoScreensItem } from './tutorialDtoScreensItem';

export interface TutorialDto {
  /** @minLength 2 */
  title: string;
  /** @minItems 1 */
  screens: TutorialDtoScreensItem[];
}
