/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { AssetType } from './assetType';
import type { UpdateAddressDto } from './updateAddressDto';
import type { CreateAssetAccessDto } from './createAssetAccessDto';
import type { UpdateAssetDtoTagsItem } from './updateAssetDtoTagsItem';
import type { UpdateAssetDtoExternalInformation } from './updateAssetDtoExternalInformation';
import type { AssetCriterionDto } from './assetCriterionDto';
import type { UpdateAssetDtoOrderKeys } from './updateAssetDtoOrderKeys';

export interface UpdateAssetDto {
  /** @minLength 2 */
  name: string;
  type: AssetType;
  address: UpdateAddressDto;
  client: string;
  access?: CreateAssetAccessDto;
  tags: UpdateAssetDtoTagsItem[];
  externalInformation?: UpdateAssetDtoExternalInformation;
  criteria?: AssetCriterionDto[];
  orderKeys: UpdateAssetDtoOrderKeys;
  id: string;
}
