/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { CreateContactDto } from './createContactDto';
import type { CreateAddressDto } from './createAddressDto';

export interface UpdateAssetAccessDto {
  contact?: CreateContactDto;
  address?: CreateAddressDto;
  remote: boolean;
  description?: string;
  id: string;
}
