/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Swagger Petstore - OpenAPI 3.0
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
You can now help us improve the API whether it's by making changes to the definition itself or to the code.
That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

Some useful links:
- [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
- [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 * OpenAPI spec version: 1.0.27-SNAPSHOT
 */
import {
  FindPetsByStatusParams,
  FindPetsByTagsParams,
  UpdatePetWithFormParams,
  LoginUserParams,
} from './http-schemas';

import {
  findPetsByStatus,
  findPetsByTags,
  getPetById,
  updatePetWithForm,
  deletePet,
  getInventory,
  getOrderById,
  deleteOrder,
  loginUser,
  logoutUser,
  getUserByName,
  deleteUser,
} from './http-client';

import { RequestHandlerExtra } from '@modelcontextprotocol/sdk/shared/protocol.js';
import {
  ServerNotification,
  ServerRequest,
} from '@modelcontextprotocol/sdk/types.js';
/**
 * Multiple status values can be provided with comma separated strings.
 * @summary Finds Pets by status.
 */

export type findPetsByStatusArgs = {
  queryParams: FindPetsByStatusParams;
  options?: RequestInit;
};

export const findPetsByStatusHandler = async (
  args: findPetsByStatusArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await findPetsByStatus(args.queryParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags.
 */

export type findPetsByTagsArgs = {
  queryParams: FindPetsByTagsParams;
  options?: RequestInit;
};

export const findPetsByTagsHandler = async (
  args: findPetsByTagsArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await findPetsByTags(args.queryParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * Returns a single pet.
 * @summary Find pet by ID.
 */

export type getPetByIdArgs = {
  pathParams: {
    petId: number;
  };
  options?: RequestInit;
};

export const getPetByIdHandler = async (
  args: getPetByIdArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getPetById(args.pathParams.petId, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * Updates a pet resource based on the form data.
 * @summary Updates a pet in the store with form data.
 */

export type updatePetWithFormArgs = {
  pathParams: {
    petId: number;
  };
  queryParams: UpdatePetWithFormParams;
  options?: RequestInit;
};

export const updatePetWithFormHandler = async (
  args: updatePetWithFormArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await updatePetWithForm(
    args.pathParams.petId,
    args.queryParams,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * Delete a pet.
 * @summary Deletes a pet.
 */

export type deletePetArgs = {
  pathParams: {
    petId: number;
  };
  options?: RequestInit;
};

export const deletePetHandler = async (
  args: deletePetArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await deletePet(args.pathParams.petId, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * Returns a map of status codes to quantities.
 * @summary Returns pet inventories by status.
 */

export type getInventoryArgs = {
  options?: RequestInit;
};

export const getInventoryHandler = async (
  args: getInventoryArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getInventory(options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
 * @summary Find purchase order by ID.
 */

export type getOrderByIdArgs = {
  pathParams: {
    orderId: number;
  };
  options?: RequestInit;
};

export const getOrderByIdHandler = async (
  args: getOrderByIdArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getOrderById(args.pathParams.orderId, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * For valid response try integer IDs with value < 1000. Anything above 1000 or non-integers will generate API errors.
 * @summary Delete purchase order by identifier.
 */

export type deleteOrderArgs = {
  pathParams: {
    orderId: number;
  };
  options?: RequestInit;
};

export const deleteOrderHandler = async (
  args: deleteOrderArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await deleteOrder(args.pathParams.orderId, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * Log into the system.
 * @summary Logs user into the system.
 */

export type loginUserArgs = {
  queryParams: LoginUserParams;
  options?: RequestInit;
};

export const loginUserHandler = async (
  args: loginUserArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await loginUser(args.queryParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * Log user out of the system.
 * @summary Logs out current logged in user session.
 */

export type logoutUserArgs = {
  options?: RequestInit;
};

export const logoutUserHandler = async (
  args: logoutUserArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await logoutUser(options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * Get user detail based on username.
 * @summary Get user by user name.
 */

export type getUserByNameArgs = {
  pathParams: {
    username: string;
  };
  options?: RequestInit;
};

export const getUserByNameHandler = async (
  args: getUserByNameArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getUserByName(args.pathParams.username, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * This can only be done by the logged in user.
 * @summary Delete user resource.
 */

export type deleteUserArgs = {
  pathParams: {
    username: string;
  };
  options?: RequestInit;
};

export const deleteUserHandler = async (
  args: deleteUserArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await deleteUser(args.pathParams.username, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};
