/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import { customFetch } from '../../custom-fetch';
import {
  GetClientsParams,
  ClientCreateDto,
  ClientUpdateDto,
  GetAllClientDeliverableParametersParams,
  ClientDeliverableParametersCreateDto,
  ClientDeliverableParametersUpdateDto,
  GetGroupsParams,
  GroupCreateDto,
  GroupUpdateDto,
  GetSuppliersParams,
  SupplierCreateDto,
  SupplierUpdateDto,
  GetUsersParams,
  UserCreateDto,
  UserUpdateDto,
  UpdateAssetDto,
  GetAssetsParams,
  CreateAssetDto,
  GetArticlesParams,
  ArticleCreateDto,
  ArticleUpdateDto,
  ArticleValidateDto,
  GetDeliverablesParams,
  RejectDeliverableDto,
  ImportDeliverableBody,
  UploadRoomplansBody,
  DeliverableVirtualTourDto,
  SubmittedFormDto,
  UpdateExportedFlowParams,
  ExportedFlowJsonDto,
  OrderResultJsonDto,
  GetClientOrderItemsParams,
  ClientOrderItemCreateDto,
  ClientOrderItemUpdateDto,
  ClientOrderItemBatchUpdateInvoicingStatusDto,
  GetResourceUrlParams,
  UploadResourceParams,
  UploadResourceBody,
  ClientOrderItemRateBodyDto,
  GetSupplierOrdersBySupplierIdParams,
  SupplierOrderUpdateDto,
  GetAllSupplierOrdersParams,
  SupplierOrderCreateDto,
  AmendSupplierOrderDto,
  GetAllClientOrdersByOrderIdParams,
  GetAllClientOrdersParams,
  ClientOrderCreateDto,
  GetSupplierOrderItemsParams,
  SupplierOrderItemBatchUpdateInvoicingStatusDto,
  ImportClientOrdersBody,
  InvoicePreferencesCreateDto,
  InvoicePreferencesUpdateDto,
  GetProjectsParams,
} from './http-schemas';

import {
  getClients,
  createClient,
  getClientByAccountNumber,
  getClientById,
  updateClient,
  getAllClientDeliverableParameters,
  createClientDeliverableParameters,
  getClientDeliverableParametersById,
  updateClientDeliverableParameters,
  getGroups,
  createGroup,
  getGroupByAccountNumber,
  getGroupById,
  updateGroup,
  getSuppliers,
  createSupplier,
  getSupplierByAccountNumber,
  getSupplierById,
  updateSupplier,
  getUsers,
  createUser,
  getUserById,
  updateUser,
  assignUserToAccount,
  unassignUserFromAccount,
  getAssetById,
  updateAsset,
  getAssets,
  createAsset,
  getArticles,
  createArticle,
  getArticleById,
  updateArticle,
  assignArticleToBillableAccount,
  validateArticleConfiguration,
  getRateFromSkuAndAccount,
  getDeliverables,
  getDeliverableById,
  publishDeliverable,
  rejectDeliverable,
  importDeliverable,
  getRoomplans,
  uploadRoomplans,
  cancelDeliverable,
  relaunchDeliverable,
  forceProcessedStatus,
  getVirtualTour,
  editVirtualTour,
  removeWindows,
  resetVirtualTour,
  maskWindows,
  validateDeliverable,
  getFlow,
  getFlowByClientOrderItemId,
  getSubmittedForms,
  updateSubmittedForms,
  getExportedFlow,
  updateExportedFlow,
  getOrderResult,
  updateOrderResult,
  healthCheck,
  getClientOrderItems,
  createClientOrderItem,
  getClientOrderItemById,
  updateClientOrderItemById,
  updateClientOrderItemsInvoicingStatus,
  getResourceUrl,
  uploadResource,
  rateForClientOrderItem,
  cancelClientOrderItem,
  getSupplierOrdersBySupplierId,
  getSupplierOrderById,
  updateSupplierOrderById,
  getAllSupplierOrders,
  createSupplierOrder,
  cancelSupplierOrderById,
  acceptSupplierOrderById,
  refuseSupplierOrderById,
  amendSupplierOrder,
  reproposeSupplierOrder,
  getAllClientOrdersByOrderId,
  getClientOrderById,
  getAllClientOrders,
  createClientOrder,
  getSupplierOrderItems,
  getSupplierOrderItemById,
  updateSupplierOrderItemsInvoicingStatus,
  cancelSupplierOrderItem,
  importClientOrders,
  exportBillableSupplierOrderItems,
  getInvoicePreferencesByAccountNumber,
  createInvoicePreferences,
  updateInvoicePreferences,
  refreshInvoicePreferencesByAccountNumber,
  getProjects,
  getProjectById,
} from './http-client';

/**
 * @summary Get all clients
 */

export type getClientsArgs = {
  queryParams: GetClientsParams;
  options?: RequestInit;
};

export const getClientsHandler = async (args: getClientsArgs) => {
  const res = await getClients(args.queryParams, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create client
 */

export type createClientArgs = {
  bodyParams: ClientCreateDto;
  options?: RequestInit;
};

export const createClientHandler = async (args: createClientArgs) => {
  const res = await createClient(args.bodyParams, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get client by account number
 */

export type getClientByAccountNumberArgs = {
  pathParams: {
    accountNumber: string;
  };
  options?: RequestInit;
};

export const getClientByAccountNumberHandler = async (
  args: getClientByAccountNumberArgs,
) => {
  const res = await getClientByAccountNumber(
    args.pathParams.accountNumber,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get client by Id
 */

export type getClientByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const getClientByIdHandler = async (args: getClientByIdArgs) => {
  const res = await getClientById(args.pathParams.id, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update client
 */

export type updateClientArgs = {
  pathParams: {
    id: string;
  };
  bodyParams: ClientUpdateDto;
  options?: RequestInit;
};

export const updateClientHandler = async (args: updateClientArgs) => {
  const res = await updateClient(
    args.pathParams.id,
    args.bodyParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all client deliverable parameters
 */

export type getAllClientDeliverableParametersArgs = {
  pathParams: {
    clientId: string;
  };
  queryParams: GetAllClientDeliverableParametersParams;
  options?: RequestInit;
};

export const getAllClientDeliverableParametersHandler = async (
  args: getAllClientDeliverableParametersArgs,
) => {
  const res = await getAllClientDeliverableParameters(
    args.pathParams.clientId,
    args.queryParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create client deliverable parameters
 */

export type createClientDeliverableParametersArgs = {
  pathParams: {
    clientId: string;
  };
  bodyParams: ClientDeliverableParametersCreateDto;
  options?: RequestInit;
};

export const createClientDeliverableParametersHandler = async (
  args: createClientDeliverableParametersArgs,
) => {
  const res = await createClientDeliverableParameters(
    args.pathParams.clientId,
    args.bodyParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get client deliverable parameters by Id
 */

export type getClientDeliverableParametersByIdArgs = {
  pathParams: {
    clientId: string;
    id: string;
  };
  options?: RequestInit;
};

export const getClientDeliverableParametersByIdHandler = async (
  args: getClientDeliverableParametersByIdArgs,
) => {
  const res = await getClientDeliverableParametersById(
    args.pathParams.clientId,
    args.pathParams.id,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update client deliverable parameters
 */

export type updateClientDeliverableParametersArgs = {
  pathParams: {
    clientId: string;
    id: string;
  };
  bodyParams: ClientDeliverableParametersUpdateDto;
  options?: RequestInit;
};

export const updateClientDeliverableParametersHandler = async (
  args: updateClientDeliverableParametersArgs,
) => {
  const res = await updateClientDeliverableParameters(
    args.pathParams.clientId,
    args.pathParams.id,
    args.bodyParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all groups
 */

export type getGroupsArgs = {
  queryParams: GetGroupsParams;
  options?: RequestInit;
};

export const getGroupsHandler = async (args: getGroupsArgs) => {
  const res = await getGroups(args.queryParams, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create group
 */

export type createGroupArgs = {
  bodyParams: GroupCreateDto;
  options?: RequestInit;
};

export const createGroupHandler = async (args: createGroupArgs) => {
  const res = await createGroup(args.bodyParams, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get group by account number
 */

export type getGroupByAccountNumberArgs = {
  pathParams: {
    accountNumber: string;
  };
  options?: RequestInit;
};

export const getGroupByAccountNumberHandler = async (
  args: getGroupByAccountNumberArgs,
) => {
  const res = await getGroupByAccountNumber(
    args.pathParams.accountNumber,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get group by Id
 */

export type getGroupByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const getGroupByIdHandler = async (args: getGroupByIdArgs) => {
  const res = await getGroupById(args.pathParams.id, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update group
 */

export type updateGroupArgs = {
  pathParams: {
    id: string;
  };
  bodyParams: GroupUpdateDto;
  options?: RequestInit;
};

export const updateGroupHandler = async (args: updateGroupArgs) => {
  const res = await updateGroup(
    args.pathParams.id,
    args.bodyParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all suppliers
 */

export type getSuppliersArgs = {
  queryParams: GetSuppliersParams;
  options?: RequestInit;
};

export const getSuppliersHandler = async (args: getSuppliersArgs) => {
  const res = await getSuppliers(args.queryParams, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create supplier
 */

export type createSupplierArgs = {
  bodyParams: SupplierCreateDto;
  options?: RequestInit;
};

export const createSupplierHandler = async (args: createSupplierArgs) => {
  const res = await createSupplier(args.bodyParams, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get supplier by account number
 */

export type getSupplierByAccountNumberArgs = {
  pathParams: {
    accountNumber: string;
  };
  options?: RequestInit;
};

export const getSupplierByAccountNumberHandler = async (
  args: getSupplierByAccountNumberArgs,
) => {
  const res = await getSupplierByAccountNumber(
    args.pathParams.accountNumber,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get client by Id
 */

export type getSupplierByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const getSupplierByIdHandler = async (args: getSupplierByIdArgs) => {
  const res = await getSupplierById(args.pathParams.id, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update supplier
 */

export type updateSupplierArgs = {
  pathParams: {
    id: string;
  };
  bodyParams: SupplierUpdateDto;
  options?: RequestInit;
};

export const updateSupplierHandler = async (args: updateSupplierArgs) => {
  const res = await updateSupplier(
    args.pathParams.id,
    args.bodyParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all users
 */

export type getUsersArgs = {
  queryParams: GetUsersParams;
  options?: RequestInit;
};

export const getUsersHandler = async (args: getUsersArgs) => {
  const res = await getUsers(args.queryParams, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create a new user
 */

export type createUserArgs = {
  bodyParams: UserCreateDto;
  options?: RequestInit;
};

export const createUserHandler = async (args: createUserArgs) => {
  const res = await createUser(args.bodyParams, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get user by Id
 */

export type getUserByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const getUserByIdHandler = async (args: getUserByIdArgs) => {
  const res = await getUserById(args.pathParams.id, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update an existing user
 */

export type updateUserArgs = {
  pathParams: {
    id: string;
  };
  bodyParams: UserUpdateDto;
  options?: RequestInit;
};

export const updateUserHandler = async (args: updateUserArgs) => {
  const res = await updateUser(
    args.pathParams.id,
    args.bodyParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Assign an user to account
 */

export type assignUserToAccountArgs = {
  pathParams: {
    id: string;
    accountNumber: string;
  };
  options?: RequestInit;
};

export const assignUserToAccountHandler = async (
  args: assignUserToAccountArgs,
) => {
  const res = await assignUserToAccount(
    args.pathParams.id,
    args.pathParams.accountNumber,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Unassign an user from account
 */

export type unassignUserFromAccountArgs = {
  pathParams: {
    id: string;
    accountNumber: string;
  };
  options?: RequestInit;
};

export const unassignUserFromAccountHandler = async (
  args: unassignUserFromAccountArgs,
) => {
  const res = await unassignUserFromAccount(
    args.pathParams.id,
    args.pathParams.accountNumber,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get an asset by id
 */

export type getAssetByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const getAssetByIdHandler = async (args: getAssetByIdArgs) => {
  const res = await getAssetById(args.pathParams.id, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update an asset
 */

export type updateAssetArgs = {
  pathParams: {
    id: string;
  };
  bodyParams: UpdateAssetDto;
  options?: RequestInit;
};

export const updateAssetHandler = async (args: updateAssetArgs) => {
  const res = await updateAsset(
    args.pathParams.id,
    args.bodyParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all assets
 */

export type getAssetsArgs = {
  queryParams: GetAssetsParams;
  options?: RequestInit;
};

export const getAssetsHandler = async (args: getAssetsArgs) => {
  const res = await getAssets(args.queryParams, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create a new Asset
 */

export type createAssetArgs = {
  bodyParams: CreateAssetDto;
  options?: RequestInit;
};

export const createAssetHandler = async (args: createAssetArgs) => {
  const res = await createAsset(args.bodyParams, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all articles
 */

export type getArticlesArgs = {
  queryParams: GetArticlesParams;
  options?: RequestInit;
};

export const getArticlesHandler = async (args: getArticlesArgs) => {
  const res = await getArticles(args.queryParams, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create a new article
 */

export type createArticleArgs = {
  bodyParams: ArticleCreateDto;
  options?: RequestInit;
};

export const createArticleHandler = async (args: createArticleArgs) => {
  const res = await createArticle(args.bodyParams, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get article by ID
 */

export type getArticleByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const getArticleByIdHandler = async (args: getArticleByIdArgs) => {
  const res = await getArticleById(args.pathParams.id, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update an article
 */

export type updateArticleArgs = {
  pathParams: {
    id: string;
  };
  bodyParams: ArticleUpdateDto;
  options?: RequestInit;
};

export const updateArticleHandler = async (args: updateArticleArgs) => {
  const res = await updateArticle(
    args.pathParams.id,
    args.bodyParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Assign an article to billable account
 */

export type assignArticleToBillableAccountArgs = {
  pathParams: {
    id: string;
    accountNumber: string;
  };
  options?: RequestInit;
};

export const assignArticleToBillableAccountHandler = async (
  args: assignArticleToBillableAccountArgs,
) => {
  const res = await assignArticleToBillableAccount(
    args.pathParams.id,
    args.pathParams.accountNumber,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Validate an article configuration
 */

export type validateArticleConfigurationArgs = {
  bodyParams: ArticleValidateDto;
  options?: RequestInit;
};

export const validateArticleConfigurationHandler = async (
  args: validateArticleConfigurationArgs,
) => {
  const res = await validateArticleConfiguration(args.bodyParams, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * This endpoint is used to get the rate for a given SKU and account. If a price book is associated with the account, it will be used to determine the rate.
 * @summary Get ZohoItem given a SKU and an account
 */

export type getRateFromSkuAndAccountArgs = {
  options?: RequestInit;
};

export const getRateFromSkuAndAccountHandler = async (
  args: getRateFromSkuAndAccountArgs,
) => {
  const res = await getRateFromSkuAndAccount(args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all deliverables
 */

export type getDeliverablesArgs = {
  queryParams: GetDeliverablesParams;
  options?: RequestInit;
};

export const getDeliverablesHandler = async (args: getDeliverablesArgs) => {
  const res = await getDeliverables(args.queryParams, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get deliverable by Id
 */

export type getDeliverableByIdArgs = {
  pathParams: {
    deliverableId: string;
  };
  options?: RequestInit;
};

export const getDeliverableByIdHandler = async (
  args: getDeliverableByIdArgs,
) => {
  const res = await getDeliverableById(
    args.pathParams.deliverableId,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Set Deliverable status to validated and trigger publication
 */

export type publishDeliverableArgs = {
  pathParams: {
    deliverableId: string;
  };
  options?: RequestInit;
};

export const publishDeliverableHandler = async (
  args: publishDeliverableArgs,
) => {
  const res = await publishDeliverable(
    args.pathParams.deliverableId,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Reject the deliverable in QA
 */

export type rejectDeliverableArgs = {
  pathParams: {
    deliverableId: string;
  };
  bodyParams: RejectDeliverableDto;
  options?: RequestInit;
};

export const rejectDeliverableHandler = async (args: rejectDeliverableArgs) => {
  const res = await rejectDeliverable(
    args.pathParams.deliverableId,
    args.bodyParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Import a new deliverable
 */

export type importDeliverableArgs = {
  pathParams: {
    clientOrderItemId: string;
    type:
      | 'SHOWROOM'
      | 'ROOMPLANS'
      | 'VIRTUAL_TOUR'
      | 'GAUSSIAN_SPLATTING'
      | 'FLYTHROUGH'
      | 'REPORT'
      | 'COSTING'
      | 'LINK'
      | 'ENERGY_PERFORMANCE_DIAGNOSTICS';
  };
  bodyParams: ImportDeliverableBody;
  options?: RequestInit;
};

export const importDeliverableHandler = async (args: importDeliverableArgs) => {
  const res = await importDeliverable(
    args.pathParams.clientOrderItemId,
    args.pathParams.type,
    args.bodyParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get the current roomplans for a deliverable
 */

export type getRoomplansArgs = {
  pathParams: {
    deliverableId: string;
  };
  options?: RequestInit;
};

export const getRoomplansHandler = async (args: getRoomplansArgs) => {
  const res = await getRoomplans(args.pathParams.deliverableId, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Upload a new roomplans for a deliverable
 */

export type uploadRoomplansArgs = {
  pathParams: {
    deliverableId: string;
  };
  bodyParams: UploadRoomplansBody;
  options?: RequestInit;
};

export const uploadRoomplansHandler = async (args: uploadRoomplansArgs) => {
  const res = await uploadRoomplans(
    args.pathParams.deliverableId,
    args.bodyParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Cancel a deliverable
 */

export type cancelDeliverableArgs = {
  pathParams: {
    deliverableId: string;
  };
  options?: RequestInit;
};

export const cancelDeliverableHandler = async (args: cancelDeliverableArgs) => {
  const res = await cancelDeliverable(
    args.pathParams.deliverableId,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Relaunch a deliverable
 */

export type relaunchDeliverableArgs = {
  pathParams: {
    deliverableId: string;
  };
  options?: RequestInit;
};

export const relaunchDeliverableHandler = async (
  args: relaunchDeliverableArgs,
) => {
  const res = await relaunchDeliverable(
    args.pathParams.deliverableId,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Force a deliverable to processed status
 */

export type forceProcessedStatusArgs = {
  pathParams: {
    deliverableId: string;
  };
  options?: RequestInit;
};

export const forceProcessedStatusHandler = async (
  args: forceProcessedStatusArgs,
) => {
  const res = await forceProcessedStatus(
    args.pathParams.deliverableId,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get the virtual tour
 */

export type getVirtualTourArgs = {
  pathParams: {
    deliverableId: string;
  };
  options?: RequestInit;
};

export const getVirtualTourHandler = async (args: getVirtualTourArgs) => {
  const res = await getVirtualTour(args.pathParams.deliverableId, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Edit the virtual tour
 */

export type editVirtualTourArgs = {
  pathParams: {
    deliverableId: string;
  };
  bodyParams: DeliverableVirtualTourDto;
  options?: RequestInit;
};

export const editVirtualTourHandler = async (args: editVirtualTourArgs) => {
  const res = await editVirtualTour(
    args.pathParams.deliverableId,
    args.bodyParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Remove windows from the virtual tour
 */

export type removeWindowsArgs = {
  pathParams: {
    deliverableId: string;
  };
  bodyParams: DeliverableVirtualTourDto;
  options?: RequestInit;
};

export const removeWindowsHandler = async (args: removeWindowsArgs) => {
  const res = await removeWindows(
    args.pathParams.deliverableId,
    args.bodyParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Reset the virtual tour (remove all edits)
 */

export type resetVirtualTourArgs = {
  pathParams: {
    deliverableId: string;
  };
  options?: RequestInit;
};

export const resetVirtualTourHandler = async (args: resetVirtualTourArgs) => {
  const res = await resetVirtualTour(
    args.pathParams.deliverableId,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Mask windows in the virtual tour
 */

export type maskWindowsArgs = {
  pathParams: {
    deliverableId: string;
  };
  options?: RequestInit;
};

export const maskWindowsHandler = async (args: maskWindowsArgs) => {
  const res = await maskWindows(args.pathParams.deliverableId, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Validate a deliverable
 */

export type validateDeliverableArgs = {
  pathParams: {
    deliverableId: string;
  };
  options?: RequestInit;
};

export const validateDeliverableHandler = async (
  args: validateDeliverableArgs,
) => {
  const res = await validateDeliverable(
    args.pathParams.deliverableId,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get a flow by id
 */

export type getFlowArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const getFlowHandler = async (args: getFlowArgs) => {
  const res = await getFlow(args.pathParams.id, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get a flow by client order item id
 */

export type getFlowByClientOrderItemIdArgs = {
  pathParams: {
    clientOrderItemId: string;
  };
  options?: RequestInit;
};

export const getFlowByClientOrderItemIdHandler = async (
  args: getFlowByClientOrderItemIdArgs,
) => {
  const res = await getFlowByClientOrderItemId(
    args.pathParams.clientOrderItemId,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get submitted forms by client order item id
 */

export type getSubmittedFormsArgs = {
  pathParams: {
    clientOrderItemId: string;
  };
  options?: RequestInit;
};

export const getSubmittedFormsHandler = async (args: getSubmittedFormsArgs) => {
  const res = await getSubmittedForms(
    args.pathParams.clientOrderItemId,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create a new submitted form
 */

export type updateSubmittedFormsArgs = {
  pathParams: {
    clientOrderItemId: string;
  };
  bodyParams: SubmittedFormDto[];
  options?: RequestInit;
};

export const updateSubmittedFormsHandler = async (
  args: updateSubmittedFormsArgs,
) => {
  const res = await updateSubmittedForms(
    args.pathParams.clientOrderItemId,
    args.bodyParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get exported flow json by client order item id
 */

export type getExportedFlowArgs = {
  pathParams: {
    clientOrderItemId: string;
  };
  options?: RequestInit;
};

export const getExportedFlowHandler = async (args: getExportedFlowArgs) => {
  const res = await getExportedFlow(
    args.pathParams.clientOrderItemId,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update exported flow json by client order item id
 */

export type updateExportedFlowArgs = {
  pathParams: {
    clientOrderItemId: string;
  };
  queryParams: UpdateExportedFlowParams;
  bodyParams: ExportedFlowJsonDto;
  options?: RequestInit;
};

export const updateExportedFlowHandler = async (
  args: updateExportedFlowArgs,
) => {
  const res = await updateExportedFlow(
    args.pathParams.clientOrderItemId,
    args.bodyParams,
    args.queryParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get order result json by client order item id
 */

export type getOrderResultArgs = {
  pathParams: {
    clientOrderItemId: string;
  };
  options?: RequestInit;
};

export const getOrderResultHandler = async (args: getOrderResultArgs) => {
  const res = await getOrderResult(
    args.pathParams.clientOrderItemId,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update order result json by client order item id
 */

export type updateOrderResultArgs = {
  pathParams: {
    clientOrderItemId: string;
  };
  bodyParams: OrderResultJsonDto;
  options?: RequestInit;
};

export const updateOrderResultHandler = async (args: updateOrderResultArgs) => {
  const res = await updateOrderResult(
    args.pathParams.clientOrderItemId,
    args.bodyParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Health check
 */

export type healthCheckArgs = {
  options?: RequestInit;
};

export const healthCheckHandler = async (args: healthCheckArgs) => {
  const res = await healthCheck(args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all client order items
 */

export type getClientOrderItemsArgs = {
  queryParams: GetClientOrderItemsParams;
  options?: RequestInit;
};

export const getClientOrderItemsHandler = async (
  args: getClientOrderItemsArgs,
) => {
  const res = await getClientOrderItems(args.queryParams, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create a client order item
 */

export type createClientOrderItemArgs = {
  bodyParams: ClientOrderItemCreateDto;
  options?: RequestInit;
};

export const createClientOrderItemHandler = async (
  args: createClientOrderItemArgs,
) => {
  const res = await createClientOrderItem(args.bodyParams, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get a client order item by Id
 */

export type getClientOrderItemByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const getClientOrderItemByIdHandler = async (
  args: getClientOrderItemByIdArgs,
) => {
  const res = await getClientOrderItemById(args.pathParams.id, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update a client order item by Id
 */

export type updateClientOrderItemByIdArgs = {
  pathParams: {
    id: string;
  };
  bodyParams: ClientOrderItemUpdateDto;
  options?: RequestInit;
};

export const updateClientOrderItemByIdHandler = async (
  args: updateClientOrderItemByIdArgs,
) => {
  const res = await updateClientOrderItemById(
    args.pathParams.id,
    args.bodyParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update invoicing status of client order items
 */

export type updateClientOrderItemsInvoicingStatusArgs = {
  bodyParams: ClientOrderItemBatchUpdateInvoicingStatusDto;
  options?: RequestInit;
};

export const updateClientOrderItemsInvoicingStatusHandler = async (
  args: updateClientOrderItemsInvoicingStatusArgs,
) => {
  const res = await updateClientOrderItemsInvoicingStatus(
    args.bodyParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get a resource by client order item id
 */

export type getResourceUrlArgs = {
  pathParams: {
    clientOrderItemId: string;
  };
  queryParams: GetResourceUrlParams;
  options?: RequestInit;
};

export const getResourceUrlHandler = async (args: getResourceUrlArgs) => {
  const res = await getResourceUrl(
    args.pathParams.clientOrderItemId,
    args.queryParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Upload a resource by client order item id
 */

export type uploadResourceArgs = {
  pathParams: {
    clientOrderItemId: string;
  };
  queryParams: UploadResourceParams;
  bodyParams: UploadResourceBody;
  options?: RequestInit;
};

export const uploadResourceHandler = async (args: uploadResourceArgs) => {
  const res = await uploadResource(
    args.pathParams.clientOrderItemId,
    args.bodyParams,
    args.queryParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get rate for a client order item
 */

export type rateForClientOrderItemArgs = {
  bodyParams: ClientOrderItemRateBodyDto;
  options?: RequestInit;
};

export const rateForClientOrderItemHandler = async (
  args: rateForClientOrderItemArgs,
) => {
  const res = await rateForClientOrderItem(args.bodyParams, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Client order item canceled
 */

export type cancelClientOrderItemArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const cancelClientOrderItemHandler = async (
  args: cancelClientOrderItemArgs,
) => {
  const res = await cancelClientOrderItem(args.pathParams.id, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all supplier orders by Supplier Id
 */

export type getSupplierOrdersBySupplierIdArgs = {
  pathParams: {
    supplierId: string;
  };
  queryParams: GetSupplierOrdersBySupplierIdParams;
  options?: RequestInit;
};

export const getSupplierOrdersBySupplierIdHandler = async (
  args: getSupplierOrdersBySupplierIdArgs,
) => {
  const res = await getSupplierOrdersBySupplierId(
    args.pathParams.supplierId,
    args.queryParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get a supplier order by Id
 */

export type getSupplierOrderByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const getSupplierOrderByIdHandler = async (
  args: getSupplierOrderByIdArgs,
) => {
  const res = await getSupplierOrderById(args.pathParams.id, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update a supplier order by Id
 */

export type updateSupplierOrderByIdArgs = {
  pathParams: {
    id: string;
  };
  bodyParams: SupplierOrderUpdateDto;
  options?: RequestInit;
};

export const updateSupplierOrderByIdHandler = async (
  args: updateSupplierOrderByIdArgs,
) => {
  const res = await updateSupplierOrderById(
    args.pathParams.id,
    args.bodyParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all supplier orders
 */

export type getAllSupplierOrdersArgs = {
  queryParams: GetAllSupplierOrdersParams;
  options?: RequestInit;
};

export const getAllSupplierOrdersHandler = async (
  args: getAllSupplierOrdersArgs,
) => {
  const res = await getAllSupplierOrders(args.queryParams, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create a new supplier order
 */

export type createSupplierOrderArgs = {
  bodyParams: SupplierOrderCreateDto;
  options?: RequestInit;
};

export const createSupplierOrderHandler = async (
  args: createSupplierOrderArgs,
) => {
  const res = await createSupplierOrder(args.bodyParams, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Cancel a supplier order by Id
 */

export type cancelSupplierOrderByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const cancelSupplierOrderByIdHandler = async (
  args: cancelSupplierOrderByIdArgs,
) => {
  const res = await cancelSupplierOrderById(args.pathParams.id, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Accept a supplier order by Id
 */

export type acceptSupplierOrderByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const acceptSupplierOrderByIdHandler = async (
  args: acceptSupplierOrderByIdArgs,
) => {
  const res = await acceptSupplierOrderById(args.pathParams.id, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Accept a supplier order by Id
 */

export type refuseSupplierOrderByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const refuseSupplierOrderByIdHandler = async (
  args: refuseSupplierOrderByIdArgs,
) => {
  const res = await refuseSupplierOrderById(args.pathParams.id, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Amend Supplier order
 */

export type amendSupplierOrderArgs = {
  pathParams: {
    id: string;
  };
  bodyParams: AmendSupplierOrderDto;
  options?: RequestInit;
};

export const amendSupplierOrderHandler = async (
  args: amendSupplierOrderArgs,
) => {
  const res = await amendSupplierOrder(
    args.pathParams.id,
    args.bodyParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create a new supplier order with new conditions. Cancels the previous one.
 */

export type reproposeSupplierOrderArgs = {
  pathParams: {
    id: string;
  };
  bodyParams: SupplierOrderCreateDto;
  options?: RequestInit;
};

export const reproposeSupplierOrderHandler = async (
  args: reproposeSupplierOrderArgs,
) => {
  const res = await reproposeSupplierOrder(
    args.pathParams.id,
    args.bodyParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all client orders by Client Id
 */

export type getAllClientOrdersByOrderIdArgs = {
  pathParams: {
    clientId: string;
  };
  queryParams: GetAllClientOrdersByOrderIdParams;
  options?: RequestInit;
};

export const getAllClientOrdersByOrderIdHandler = async (
  args: getAllClientOrdersByOrderIdArgs,
) => {
  const res = await getAllClientOrdersByOrderId(
    args.pathParams.clientId,
    args.queryParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get a client order by Id
 */

export type getClientOrderByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const getClientOrderByIdHandler = async (
  args: getClientOrderByIdArgs,
) => {
  const res = await getClientOrderById(args.pathParams.id, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all client orders
 */

export type getAllClientOrdersArgs = {
  queryParams: GetAllClientOrdersParams;
  options?: RequestInit;
};

export const getAllClientOrdersHandler = async (
  args: getAllClientOrdersArgs,
) => {
  const res = await getAllClientOrders(args.queryParams, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create a new client order
 */

export type createClientOrderArgs = {
  bodyParams: ClientOrderCreateDto;
  options?: RequestInit;
};

export const createClientOrderHandler = async (args: createClientOrderArgs) => {
  const res = await createClientOrder(args.bodyParams, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all supplier order items
 */

export type getSupplierOrderItemsArgs = {
  queryParams: GetSupplierOrderItemsParams;
  options?: RequestInit;
};

export const getSupplierOrderItemsHandler = async (
  args: getSupplierOrderItemsArgs,
) => {
  const res = await getSupplierOrderItems(args.queryParams, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get a supplier order item by Id
 */

export type getSupplierOrderItemByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const getSupplierOrderItemByIdHandler = async (
  args: getSupplierOrderItemByIdArgs,
) => {
  const res = await getSupplierOrderItemById(args.pathParams.id, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update invoicing status of supplier order items
 */

export type updateSupplierOrderItemsInvoicingStatusArgs = {
  bodyParams: SupplierOrderItemBatchUpdateInvoicingStatusDto;
  options?: RequestInit;
};

export const updateSupplierOrderItemsInvoicingStatusHandler = async (
  args: updateSupplierOrderItemsInvoicingStatusArgs,
) => {
  const res = await updateSupplierOrderItemsInvoicingStatus(
    args.bodyParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Supplier order item canceled
 */

export type cancelSupplierOrderItemArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const cancelSupplierOrderItemHandler = async (
  args: cancelSupplierOrderItemArgs,
) => {
  const res = await cancelSupplierOrderItem(args.pathParams.id, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Import new client orders
 */

export type importClientOrdersArgs = {
  pathParams: {
    clientId: string;
  };
  bodyParams: ImportClientOrdersBody;
  options?: RequestInit;
};

export const importClientOrdersHandler = async (
  args: importClientOrdersArgs,
) => {
  const res = await importClientOrders(
    args.pathParams.clientId,
    args.bodyParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Export billable supplier order items
 */

export type exportBillableSupplierOrderItemsArgs = {
  options?: RequestInit;
};

export const exportBillableSupplierOrderItemsHandler = async (
  args: exportBillableSupplierOrderItemsArgs,
) => {
  const res = await exportBillableSupplierOrderItems(args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get invoice preferences by account number
 */

export type getInvoicePreferencesByAccountNumberArgs = {
  pathParams: {
    accountNumber: string;
  };
  options?: RequestInit;
};

export const getInvoicePreferencesByAccountNumberHandler = async (
  args: getInvoicePreferencesByAccountNumberArgs,
) => {
  const res = await getInvoicePreferencesByAccountNumber(
    args.pathParams.accountNumber,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create invoice preferences
 */

export type createInvoicePreferencesArgs = {
  bodyParams: InvoicePreferencesCreateDto;
  options?: RequestInit;
};

export const createInvoicePreferencesHandler = async (
  args: createInvoicePreferencesArgs,
) => {
  const res = await createInvoicePreferences(args.bodyParams, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update invoice preferences
 */

export type updateInvoicePreferencesArgs = {
  pathParams: {
    invoicePreferenceId: string;
  };
  bodyParams: InvoicePreferencesUpdateDto;
  options?: RequestInit;
};

export const updateInvoicePreferencesHandler = async (
  args: updateInvoicePreferencesArgs,
) => {
  const res = await updateInvoicePreferences(
    args.pathParams.invoicePreferenceId,
    args.bodyParams,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Refresh invoice preferences by account number
 */

export type refreshInvoicePreferencesByAccountNumberArgs = {
  pathParams: {
    accountNumber: string;
  };
  options?: RequestInit;
};

export const refreshInvoicePreferencesByAccountNumberHandler = async (
  args: refreshInvoicePreferencesByAccountNumberArgs,
) => {
  const res = await refreshInvoicePreferencesByAccountNumber(
    args.pathParams.accountNumber,
    args.options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all projects
 */

export type getProjectsArgs = {
  queryParams: GetProjectsParams;
  options?: RequestInit;
};

export const getProjectsHandler = async (args: getProjectsArgs) => {
  const res = await getProjects(args.queryParams, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get project by Id
 */

export type getProjectByIdArgs = {
  pathParams: {
    projectId: string;
  };
  options?: RequestInit;
};

export const getProjectByIdHandler = async (args: getProjectByIdArgs) => {
  const res = await getProjectById(args.pathParams.projectId, args.options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};
