/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */

import { customFetch } from '../../custom-fetch';

import {
  GetClients200,
  GetClientsParams,
  ClientDto,
  ClientCreateDto,
  ClientUpdateDto,
  GetAllClientDeliverableParameters200,
  GetAllClientDeliverableParametersParams,
  ClientDeliverableParametersDto,
  ClientDeliverableParametersCreateDto,
  ClientDeliverableParametersUpdateDto,
  GetGroups200,
  GetGroupsParams,
  GroupDto,
  GroupCreateDto,
  GroupUpdateDto,
  GetSuppliers200,
  GetSuppliersParams,
  SupplierDto,
  SupplierCreateDto,
  SupplierUpdateDto,
  GetUsers200,
  GetUsersParams,
  UserDto,
  UserCreateDto,
  UpdateUser201,
  UserUpdateDto,
  AssetDto,
  UpdateAssetDto,
  GetAssets200,
  GetAssetsParams,
  CreateAssetDto,
  GetArticles200,
  GetArticlesParams,
  ArticleDto,
  CreateArticle201,
  ArticleCreateDto,
  UpdateArticle201,
  ArticleUpdateDto,
  ArticleValidateResultDto,
  ArticleValidateDto,
  ZohoItemDto,
  ErrorDto,
  GetDeliverables200,
  GetDeliverablesParams,
  DeliverableDto,
  RejectDeliverableDto,
  ImportDeliverableBody,
  UploadRoomplansBody,
  DeliverableVirtualTourDto,
  FlowDto,
  SubmittedFormDto,
  ExportedFlowJsonDto,
  UpdateExportedFlow201,
  UpdateExportedFlowParams,
  OrderResultJsonDto,
  UpdateOrderResult201,
  GetClientOrderItems200,
  GetClientOrderItemsParams,
  ClientOrderItemDto,
  ClientOrderItemCreateDto,
  ClientOrderItemUpdateDto,
  ClientOrderItemBatchUpdateInvoicingStatusDto,
  GetResourceUrlParams,
  UploadResourceBody,
  UploadResourceParams,
  ClientOrderItemRateResponseDto,
  ClientOrderItemRateBodyDto,
  GetSupplierOrdersBySupplierId200,
  GetSupplierOrdersBySupplierIdParams,
  SupplierOrderDto,
  SupplierOrderUpdateDto,
  GetAllSupplierOrders200,
  GetAllSupplierOrdersParams,
  SupplierOrderCreateDto,
  AmendSupplierOrderDto,
  GetAllClientOrdersByOrderId200,
  GetAllClientOrdersByOrderIdParams,
  ClientOrderDto,
  GetAllClientOrders200,
  GetAllClientOrdersParams,
  ClientOrderCreateDto,
  GetSupplierOrderItems200,
  GetSupplierOrderItemsParams,
  SupplierOrderItemDto,
  SupplierOrderItemBatchUpdateInvoicingStatusDto,
  ImportClientOrdersBody,
  InvoicePreferencesDto,
  InvoicePreferencesCreateDto,
  InvoicePreferencesUpdateDto,
  GetProjects200,
  GetProjectsParams,
  ProjectDto,
} from './http-schemas';

export type getClientsResponse200 = {
  data: GetClients200;
  status: 200;
};

export type getClientsResponseSuccess = getClientsResponse200 & {
  headers: Headers;
};
export type getClientsResponse = getClientsResponseSuccess;

export const getGetClientsUrl = (params?: GetClientsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/clients?${stringifiedParams}`
    : `/v1/clients`;
};

export const getClients = async (
  params?: GetClientsParams,
  options?: RequestInit,
): Promise<getClientsResponse> => {
  return customFetch<getClientsResponse>(getGetClientsUrl(params), {
    ...options,
    method: 'GET',
  });
};

export type createClientResponse201 = {
  data: ClientDto;
  status: 201;
};

export type createClientResponseSuccess = createClientResponse201 & {
  headers: Headers;
};
export type createClientResponse = createClientResponseSuccess;

export const getCreateClientUrl = () => {
  return `/v1/clients`;
};

export const createClient = async (
  clientCreateDto: ClientCreateDto,
  options?: RequestInit,
): Promise<createClientResponse> => {
  return customFetch<createClientResponse>(getCreateClientUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(clientCreateDto),
  });
};

export type getClientByAccountNumberResponse200 = {
  data: ClientDto;
  status: 200;
};

export type getClientByAccountNumberResponseSuccess =
  getClientByAccountNumberResponse200 & {
    headers: Headers;
  };
export type getClientByAccountNumberResponse =
  getClientByAccountNumberResponseSuccess;

export const getGetClientByAccountNumberUrl = (accountNumber: string) => {
  return `/v1/clients/by-account-number/${accountNumber}`;
};

export const getClientByAccountNumber = async (
  accountNumber: string,
  options?: RequestInit,
): Promise<getClientByAccountNumberResponse> => {
  return customFetch<getClientByAccountNumberResponse>(
    getGetClientByAccountNumberUrl(accountNumber),
    {
      ...options,
      method: 'GET',
    },
  );
};

export type getClientByIdResponse200 = {
  data: ClientDto;
  status: 200;
};

export type getClientByIdResponseSuccess = getClientByIdResponse200 & {
  headers: Headers;
};
export type getClientByIdResponse = getClientByIdResponseSuccess;

export const getGetClientByIdUrl = (id: string) => {
  return `/v1/clients/${id}`;
};

export const getClientById = async (
  id: string,
  options?: RequestInit,
): Promise<getClientByIdResponse> => {
  return customFetch<getClientByIdResponse>(getGetClientByIdUrl(id), {
    ...options,
    method: 'GET',
  });
};

export type updateClientResponse200 = {
  data: ClientDto;
  status: 200;
};

export type updateClientResponseSuccess = updateClientResponse200 & {
  headers: Headers;
};
export type updateClientResponse = updateClientResponseSuccess;

export const getUpdateClientUrl = (id: string) => {
  return `/v1/clients/${id}`;
};

export const updateClient = async (
  id: string,
  clientUpdateDto: ClientUpdateDto,
  options?: RequestInit,
): Promise<updateClientResponse> => {
  return customFetch<updateClientResponse>(getUpdateClientUrl(id), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(clientUpdateDto),
  });
};

export type getAllClientDeliverableParametersResponse200 = {
  data: GetAllClientDeliverableParameters200;
  status: 200;
};

export type getAllClientDeliverableParametersResponseSuccess =
  getAllClientDeliverableParametersResponse200 & {
    headers: Headers;
  };
export type getAllClientDeliverableParametersResponse =
  getAllClientDeliverableParametersResponseSuccess;

export const getGetAllClientDeliverableParametersUrl = (
  clientId: string,
  params?: GetAllClientDeliverableParametersParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/clients/${clientId}/deliverable/parameters?${stringifiedParams}`
    : `/v1/clients/${clientId}/deliverable/parameters`;
};

export const getAllClientDeliverableParameters = async (
  clientId: string,
  params?: GetAllClientDeliverableParametersParams,
  options?: RequestInit,
): Promise<getAllClientDeliverableParametersResponse> => {
  return customFetch<getAllClientDeliverableParametersResponse>(
    getGetAllClientDeliverableParametersUrl(clientId, params),
    {
      ...options,
      method: 'GET',
    },
  );
};

export type createClientDeliverableParametersResponse201 = {
  data: ClientDeliverableParametersDto;
  status: 201;
};

export type createClientDeliverableParametersResponseSuccess =
  createClientDeliverableParametersResponse201 & {
    headers: Headers;
  };
export type createClientDeliverableParametersResponse =
  createClientDeliverableParametersResponseSuccess;

export const getCreateClientDeliverableParametersUrl = (clientId: string) => {
  return `/v1/clients/${clientId}/deliverable/parameters`;
};

export const createClientDeliverableParameters = async (
  clientId: string,
  clientDeliverableParametersCreateDto: ClientDeliverableParametersCreateDto,
  options?: RequestInit,
): Promise<createClientDeliverableParametersResponse> => {
  return customFetch<createClientDeliverableParametersResponse>(
    getCreateClientDeliverableParametersUrl(clientId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(clientDeliverableParametersCreateDto),
    },
  );
};

export type getClientDeliverableParametersByIdResponse200 = {
  data: ClientDeliverableParametersDto;
  status: 200;
};

export type getClientDeliverableParametersByIdResponseSuccess =
  getClientDeliverableParametersByIdResponse200 & {
    headers: Headers;
  };
export type getClientDeliverableParametersByIdResponse =
  getClientDeliverableParametersByIdResponseSuccess;

export const getGetClientDeliverableParametersByIdUrl = (
  clientId: string,
  id: string,
) => {
  return `/v1/clients/${clientId}/deliverable/parameters/${id}`;
};

export const getClientDeliverableParametersById = async (
  clientId: string,
  id: string,
  options?: RequestInit,
): Promise<getClientDeliverableParametersByIdResponse> => {
  return customFetch<getClientDeliverableParametersByIdResponse>(
    getGetClientDeliverableParametersByIdUrl(clientId, id),
    {
      ...options,
      method: 'GET',
    },
  );
};

export type updateClientDeliverableParametersResponse200 = {
  data: ClientDeliverableParametersDto;
  status: 200;
};

export type updateClientDeliverableParametersResponseSuccess =
  updateClientDeliverableParametersResponse200 & {
    headers: Headers;
  };
export type updateClientDeliverableParametersResponse =
  updateClientDeliverableParametersResponseSuccess;

export const getUpdateClientDeliverableParametersUrl = (
  clientId: string,
  id: string,
) => {
  return `/v1/clients/${clientId}/deliverable/parameters/${id}`;
};

export const updateClientDeliverableParameters = async (
  clientId: string,
  id: string,
  clientDeliverableParametersUpdateDto: ClientDeliverableParametersUpdateDto,
  options?: RequestInit,
): Promise<updateClientDeliverableParametersResponse> => {
  return customFetch<updateClientDeliverableParametersResponse>(
    getUpdateClientDeliverableParametersUrl(clientId, id),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(clientDeliverableParametersUpdateDto),
    },
  );
};

export type getGroupsResponse200 = {
  data: GetGroups200;
  status: 200;
};

export type getGroupsResponseSuccess = getGroupsResponse200 & {
  headers: Headers;
};
export type getGroupsResponse = getGroupsResponseSuccess;

export const getGetGroupsUrl = (params?: GetGroupsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/groups?${stringifiedParams}`
    : `/v1/groups`;
};

export const getGroups = async (
  params?: GetGroupsParams,
  options?: RequestInit,
): Promise<getGroupsResponse> => {
  return customFetch<getGroupsResponse>(getGetGroupsUrl(params), {
    ...options,
    method: 'GET',
  });
};

export type createGroupResponse201 = {
  data: GroupDto;
  status: 201;
};

export type createGroupResponseSuccess = createGroupResponse201 & {
  headers: Headers;
};
export type createGroupResponse = createGroupResponseSuccess;

export const getCreateGroupUrl = () => {
  return `/v1/groups`;
};

export const createGroup = async (
  groupCreateDto: GroupCreateDto,
  options?: RequestInit,
): Promise<createGroupResponse> => {
  return customFetch<createGroupResponse>(getCreateGroupUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(groupCreateDto),
  });
};

export type getGroupByAccountNumberResponse200 = {
  data: GroupDto;
  status: 200;
};

export type getGroupByAccountNumberResponseSuccess =
  getGroupByAccountNumberResponse200 & {
    headers: Headers;
  };
export type getGroupByAccountNumberResponse =
  getGroupByAccountNumberResponseSuccess;

export const getGetGroupByAccountNumberUrl = (accountNumber: string) => {
  return `/v1/groups/by-account-number/${accountNumber}`;
};

export const getGroupByAccountNumber = async (
  accountNumber: string,
  options?: RequestInit,
): Promise<getGroupByAccountNumberResponse> => {
  return customFetch<getGroupByAccountNumberResponse>(
    getGetGroupByAccountNumberUrl(accountNumber),
    {
      ...options,
      method: 'GET',
    },
  );
};

export type getGroupByIdResponse200 = {
  data: GroupDto;
  status: 200;
};

export type getGroupByIdResponseSuccess = getGroupByIdResponse200 & {
  headers: Headers;
};
export type getGroupByIdResponse = getGroupByIdResponseSuccess;

export const getGetGroupByIdUrl = (id: string) => {
  return `/v1/groups/${id}`;
};

export const getGroupById = async (
  id: string,
  options?: RequestInit,
): Promise<getGroupByIdResponse> => {
  return customFetch<getGroupByIdResponse>(getGetGroupByIdUrl(id), {
    ...options,
    method: 'GET',
  });
};

export type updateGroupResponse200 = {
  data: GroupDto;
  status: 200;
};

export type updateGroupResponseSuccess = updateGroupResponse200 & {
  headers: Headers;
};
export type updateGroupResponse = updateGroupResponseSuccess;

export const getUpdateGroupUrl = (id: string) => {
  return `/v1/groups/${id}`;
};

export const updateGroup = async (
  id: string,
  groupUpdateDto: GroupUpdateDto,
  options?: RequestInit,
): Promise<updateGroupResponse> => {
  return customFetch<updateGroupResponse>(getUpdateGroupUrl(id), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(groupUpdateDto),
  });
};

export type getSuppliersResponse200 = {
  data: GetSuppliers200;
  status: 200;
};

export type getSuppliersResponseSuccess = getSuppliersResponse200 & {
  headers: Headers;
};
export type getSuppliersResponse = getSuppliersResponseSuccess;

export const getGetSuppliersUrl = (params?: GetSuppliersParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/suppliers?${stringifiedParams}`
    : `/v1/suppliers`;
};

export const getSuppliers = async (
  params?: GetSuppliersParams,
  options?: RequestInit,
): Promise<getSuppliersResponse> => {
  return customFetch<getSuppliersResponse>(getGetSuppliersUrl(params), {
    ...options,
    method: 'GET',
  });
};

export type createSupplierResponse201 = {
  data: SupplierDto;
  status: 201;
};

export type createSupplierResponseSuccess = createSupplierResponse201 & {
  headers: Headers;
};
export type createSupplierResponse = createSupplierResponseSuccess;

export const getCreateSupplierUrl = () => {
  return `/v1/suppliers`;
};

export const createSupplier = async (
  supplierCreateDto: SupplierCreateDto,
  options?: RequestInit,
): Promise<createSupplierResponse> => {
  return customFetch<createSupplierResponse>(getCreateSupplierUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(supplierCreateDto),
  });
};

export type getSupplierByAccountNumberResponse200 = {
  data: SupplierDto;
  status: 200;
};

export type getSupplierByAccountNumberResponseSuccess =
  getSupplierByAccountNumberResponse200 & {
    headers: Headers;
  };
export type getSupplierByAccountNumberResponse =
  getSupplierByAccountNumberResponseSuccess;

export const getGetSupplierByAccountNumberUrl = (accountNumber: string) => {
  return `/v1/suppliers/by-account-number/${accountNumber}`;
};

export const getSupplierByAccountNumber = async (
  accountNumber: string,
  options?: RequestInit,
): Promise<getSupplierByAccountNumberResponse> => {
  return customFetch<getSupplierByAccountNumberResponse>(
    getGetSupplierByAccountNumberUrl(accountNumber),
    {
      ...options,
      method: 'GET',
    },
  );
};

export type getSupplierByIdResponse200 = {
  data: SupplierDto;
  status: 200;
};

export type getSupplierByIdResponseSuccess = getSupplierByIdResponse200 & {
  headers: Headers;
};
export type getSupplierByIdResponse = getSupplierByIdResponseSuccess;

export const getGetSupplierByIdUrl = (id: string) => {
  return `/v1/suppliers/${id}`;
};

export const getSupplierById = async (
  id: string,
  options?: RequestInit,
): Promise<getSupplierByIdResponse> => {
  return customFetch<getSupplierByIdResponse>(getGetSupplierByIdUrl(id), {
    ...options,
    method: 'GET',
  });
};

export type updateSupplierResponse200 = {
  data: SupplierDto;
  status: 200;
};

export type updateSupplierResponseSuccess = updateSupplierResponse200 & {
  headers: Headers;
};
export type updateSupplierResponse = updateSupplierResponseSuccess;

export const getUpdateSupplierUrl = (id: string) => {
  return `/v1/suppliers/${id}`;
};

export const updateSupplier = async (
  id: string,
  supplierUpdateDto: SupplierUpdateDto,
  options?: RequestInit,
): Promise<updateSupplierResponse> => {
  return customFetch<updateSupplierResponse>(getUpdateSupplierUrl(id), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(supplierUpdateDto),
  });
};

export type getUsersResponse200 = {
  data: GetUsers200;
  status: 200;
};

export type getUsersResponseSuccess = getUsersResponse200 & {
  headers: Headers;
};
export type getUsersResponse = getUsersResponseSuccess;

export const getGetUsersUrl = (params?: GetUsersParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/users?${stringifiedParams}`
    : `/v1/users`;
};

export const getUsers = async (
  params?: GetUsersParams,
  options?: RequestInit,
): Promise<getUsersResponse> => {
  return customFetch<getUsersResponse>(getGetUsersUrl(params), {
    ...options,
    method: 'GET',
  });
};

export type createUserResponse201 = {
  data: UserDto;
  status: 201;
};

export type createUserResponseSuccess = createUserResponse201 & {
  headers: Headers;
};
export type createUserResponse = createUserResponseSuccess;

export const getCreateUserUrl = () => {
  return `/v1/users`;
};

export const createUser = async (
  userCreateDto: UserCreateDto,
  options?: RequestInit,
): Promise<createUserResponse> => {
  return customFetch<createUserResponse>(getCreateUserUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userCreateDto),
  });
};

export type getUserByIdResponse200 = {
  data: UserDto;
  status: 200;
};

export type getUserByIdResponseSuccess = getUserByIdResponse200 & {
  headers: Headers;
};
export type getUserByIdResponse = getUserByIdResponseSuccess;

export const getGetUserByIdUrl = (id: string) => {
  return `/v1/users/${id}`;
};

export const getUserById = async (
  id: string,
  options?: RequestInit,
): Promise<getUserByIdResponse> => {
  return customFetch<getUserByIdResponse>(getGetUserByIdUrl(id), {
    ...options,
    method: 'GET',
  });
};

export type updateUserResponse200 = {
  data: UserDto;
  status: 200;
};

export type updateUserResponse201 = {
  data: UpdateUser201;
  status: 201;
};

export type updateUserResponseSuccess = (
  | updateUserResponse200
  | updateUserResponse201
) & {
  headers: Headers;
};
export type updateUserResponse = updateUserResponseSuccess;

export const getUpdateUserUrl = (id: string) => {
  return `/v1/users/${id}`;
};

export const updateUser = async (
  id: string,
  userUpdateDto: UserUpdateDto,
  options?: RequestInit,
): Promise<updateUserResponse> => {
  return customFetch<updateUserResponse>(getUpdateUserUrl(id), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userUpdateDto),
  });
};

export type assignUserToAccountResponse200 = {
  data: UserDto;
  status: 200;
};

export type assignUserToAccountResponseSuccess =
  assignUserToAccountResponse200 & {
    headers: Headers;
  };
export type assignUserToAccountResponse = assignUserToAccountResponseSuccess;

export const getAssignUserToAccountUrl = (
  id: string,
  accountNumber: string,
) => {
  return `/v1/users/${id}/assign/${accountNumber}`;
};

export const assignUserToAccount = async (
  id: string,
  accountNumber: string,
  options?: RequestInit,
): Promise<assignUserToAccountResponse> => {
  return customFetch<assignUserToAccountResponse>(
    getAssignUserToAccountUrl(id, accountNumber),
    {
      ...options,
      method: 'PUT',
    },
  );
};

export type unassignUserFromAccountResponse200 = {
  data: UserDto;
  status: 200;
};

export type unassignUserFromAccountResponseSuccess =
  unassignUserFromAccountResponse200 & {
    headers: Headers;
  };
export type unassignUserFromAccountResponse =
  unassignUserFromAccountResponseSuccess;

export const getUnassignUserFromAccountUrl = (
  id: string,
  accountNumber: string,
) => {
  return `/v1/users/${id}/unassign/${accountNumber}`;
};

export const unassignUserFromAccount = async (
  id: string,
  accountNumber: string,
  options?: RequestInit,
): Promise<unassignUserFromAccountResponse> => {
  return customFetch<unassignUserFromAccountResponse>(
    getUnassignUserFromAccountUrl(id, accountNumber),
    {
      ...options,
      method: 'PUT',
    },
  );
};

export type getAssetByIdResponse200 = {
  data: AssetDto;
  status: 200;
};

export type getAssetByIdResponse404 = {
  data: void;
  status: 404;
};

export type getAssetByIdResponseSuccess = getAssetByIdResponse200 & {
  headers: Headers;
};
export type getAssetByIdResponseError = getAssetByIdResponse404 & {
  headers: Headers;
};

export type getAssetByIdResponse =
  | getAssetByIdResponseSuccess
  | getAssetByIdResponseError;

export const getGetAssetByIdUrl = (id: string) => {
  return `/v1/assets/${id}`;
};

export const getAssetById = async (
  id: string,
  options?: RequestInit,
): Promise<getAssetByIdResponse> => {
  return customFetch<getAssetByIdResponse>(getGetAssetByIdUrl(id), {
    ...options,
    method: 'GET',
  });
};

export type updateAssetResponse200 = {
  data: AssetDto;
  status: 200;
};

export type updateAssetResponseSuccess = updateAssetResponse200 & {
  headers: Headers;
};
export type updateAssetResponse = updateAssetResponseSuccess;

export const getUpdateAssetUrl = (id: string) => {
  return `/v1/assets/${id}`;
};

export const updateAsset = async (
  id: string,
  updateAssetDto: UpdateAssetDto,
  options?: RequestInit,
): Promise<updateAssetResponse> => {
  return customFetch<updateAssetResponse>(getUpdateAssetUrl(id), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateAssetDto),
  });
};

export type getAssetsResponse200 = {
  data: GetAssets200;
  status: 200;
};

export type getAssetsResponseSuccess = getAssetsResponse200 & {
  headers: Headers;
};
export type getAssetsResponse = getAssetsResponseSuccess;

export const getGetAssetsUrl = (params?: GetAssetsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/assets?${stringifiedParams}`
    : `/v1/assets`;
};

export const getAssets = async (
  params?: GetAssetsParams,
  options?: RequestInit,
): Promise<getAssetsResponse> => {
  return customFetch<getAssetsResponse>(getGetAssetsUrl(params), {
    ...options,
    method: 'GET',
  });
};

export type createAssetResponse201 = {
  data: AssetDto;
  status: 201;
};

export type createAssetResponseSuccess = createAssetResponse201 & {
  headers: Headers;
};
export type createAssetResponse = createAssetResponseSuccess;

export const getCreateAssetUrl = () => {
  return `/v1/assets`;
};

export const createAsset = async (
  createAssetDto: CreateAssetDto,
  options?: RequestInit,
): Promise<createAssetResponse> => {
  return customFetch<createAssetResponse>(getCreateAssetUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createAssetDto),
  });
};

export type getArticlesResponse200 = {
  data: GetArticles200;
  status: 200;
};

export type getArticlesResponseSuccess = getArticlesResponse200 & {
  headers: Headers;
};
export type getArticlesResponse = getArticlesResponseSuccess;

export const getGetArticlesUrl = (params?: GetArticlesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/articles?${stringifiedParams}`
    : `/v1/articles`;
};

export const getArticles = async (
  params?: GetArticlesParams,
  options?: RequestInit,
): Promise<getArticlesResponse> => {
  return customFetch<getArticlesResponse>(getGetArticlesUrl(params), {
    ...options,
    method: 'GET',
  });
};

export type createArticleResponse200 = {
  data: ArticleDto;
  status: 200;
};

export type createArticleResponse201 = {
  data: CreateArticle201;
  status: 201;
};

export type createArticleResponseSuccess = (
  | createArticleResponse200
  | createArticleResponse201
) & {
  headers: Headers;
};
export type createArticleResponse = createArticleResponseSuccess;

export const getCreateArticleUrl = () => {
  return `/v1/articles`;
};

export const createArticle = async (
  articleCreateDto: ArticleCreateDto,
  options?: RequestInit,
): Promise<createArticleResponse> => {
  return customFetch<createArticleResponse>(getCreateArticleUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(articleCreateDto),
  });
};

export type getArticleByIdResponse200 = {
  data: ArticleDto;
  status: 200;
};

export type getArticleByIdResponseSuccess = getArticleByIdResponse200 & {
  headers: Headers;
};
export type getArticleByIdResponse = getArticleByIdResponseSuccess;

export const getGetArticleByIdUrl = (id: string) => {
  return `/v1/articles/${id}`;
};

export const getArticleById = async (
  id: string,
  options?: RequestInit,
): Promise<getArticleByIdResponse> => {
  return customFetch<getArticleByIdResponse>(getGetArticleByIdUrl(id), {
    ...options,
    method: 'GET',
  });
};

export type updateArticleResponse200 = {
  data: ArticleDto;
  status: 200;
};

export type updateArticleResponse201 = {
  data: UpdateArticle201;
  status: 201;
};

export type updateArticleResponseSuccess = (
  | updateArticleResponse200
  | updateArticleResponse201
) & {
  headers: Headers;
};
export type updateArticleResponse = updateArticleResponseSuccess;

export const getUpdateArticleUrl = (id: string) => {
  return `/v1/articles/${id}`;
};

export const updateArticle = async (
  id: string,
  articleUpdateDto: ArticleUpdateDto,
  options?: RequestInit,
): Promise<updateArticleResponse> => {
  return customFetch<updateArticleResponse>(getUpdateArticleUrl(id), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(articleUpdateDto),
  });
};

export type assignArticleToBillableAccountResponse200 = {
  data: void;
  status: 200;
};

export type assignArticleToBillableAccountResponseSuccess =
  assignArticleToBillableAccountResponse200 & {
    headers: Headers;
  };
export type assignArticleToBillableAccountResponse =
  assignArticleToBillableAccountResponseSuccess;

export const getAssignArticleToBillableAccountUrl = (
  id: string,
  accountNumber: string,
) => {
  return `/v1/articles/${id}/assign/${accountNumber}`;
};

export const assignArticleToBillableAccount = async (
  id: string,
  accountNumber: string,
  options?: RequestInit,
): Promise<assignArticleToBillableAccountResponse> => {
  return customFetch<assignArticleToBillableAccountResponse>(
    getAssignArticleToBillableAccountUrl(id, accountNumber),
    {
      ...options,
      method: 'PUT',
    },
  );
};

export type validateArticleConfigurationResponse200 = {
  data: ArticleValidateResultDto;
  status: 200;
};

export type validateArticleConfigurationResponseSuccess =
  validateArticleConfigurationResponse200 & {
    headers: Headers;
  };
export type validateArticleConfigurationResponse =
  validateArticleConfigurationResponseSuccess;

export const getValidateArticleConfigurationUrl = () => {
  return `/v1/articles/validate`;
};

export const validateArticleConfiguration = async (
  articleValidateDto: ArticleValidateDto,
  options?: RequestInit,
): Promise<validateArticleConfigurationResponse> => {
  return customFetch<validateArticleConfigurationResponse>(
    getValidateArticleConfigurationUrl(),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(articleValidateDto),
    },
  );
};

export type getRateFromSkuAndAccountResponse200 = {
  data: void;
  status: 200;
};

export type getRateFromSkuAndAccountResponse201 = {
  data: ZohoItemDto;
  status: 201;
};

export type getRateFromSkuAndAccountResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type getRateFromSkuAndAccountResponseSuccess = (
  | getRateFromSkuAndAccountResponse200
  | getRateFromSkuAndAccountResponse201
) & {
  headers: Headers;
};
export type getRateFromSkuAndAccountResponseError =
  getRateFromSkuAndAccountResponse400 & {
    headers: Headers;
  };

export type getRateFromSkuAndAccountResponse =
  | getRateFromSkuAndAccountResponseSuccess
  | getRateFromSkuAndAccountResponseError;

export const getGetRateFromSkuAndAccountUrl = () => {
  return `/v1/pricing/rate`;
};

export const getRateFromSkuAndAccount = async (
  options?: RequestInit,
): Promise<getRateFromSkuAndAccountResponse> => {
  return customFetch<getRateFromSkuAndAccountResponse>(
    getGetRateFromSkuAndAccountUrl(),
    {
      ...options,
      method: 'POST',
    },
  );
};

export type getDeliverablesResponse200 = {
  data: GetDeliverables200;
  status: 200;
};

export type getDeliverablesResponseSuccess = getDeliverablesResponse200 & {
  headers: Headers;
};
export type getDeliverablesResponse = getDeliverablesResponseSuccess;

export const getGetDeliverablesUrl = (params?: GetDeliverablesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/deliverables?${stringifiedParams}`
    : `/v1/deliverables`;
};

export const getDeliverables = async (
  params?: GetDeliverablesParams,
  options?: RequestInit,
): Promise<getDeliverablesResponse> => {
  return customFetch<getDeliverablesResponse>(getGetDeliverablesUrl(params), {
    ...options,
    method: 'GET',
  });
};

export type getDeliverableByIdResponse200 = {
  data: DeliverableDto;
  status: 200;
};

export type getDeliverableByIdResponseSuccess =
  getDeliverableByIdResponse200 & {
    headers: Headers;
  };
export type getDeliverableByIdResponse = getDeliverableByIdResponseSuccess;

export const getGetDeliverableByIdUrl = (deliverableId: string) => {
  return `/v1/deliverables/${deliverableId}`;
};

export const getDeliverableById = async (
  deliverableId: string,
  options?: RequestInit,
): Promise<getDeliverableByIdResponse> => {
  return customFetch<getDeliverableByIdResponse>(
    getGetDeliverableByIdUrl(deliverableId),
    {
      ...options,
      method: 'GET',
    },
  );
};

export type publishDeliverableResponse200 = {
  data: DeliverableDto;
  status: 200;
};

export type publishDeliverableResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type publishDeliverableResponse404 = {
  data: ErrorDto;
  status: 404;
};

export type publishDeliverableResponseSuccess =
  publishDeliverableResponse200 & {
    headers: Headers;
  };
export type publishDeliverableResponseError = (
  | publishDeliverableResponse400
  | publishDeliverableResponse404
) & {
  headers: Headers;
};

export type publishDeliverableResponse =
  | publishDeliverableResponseSuccess
  | publishDeliverableResponseError;

export const getPublishDeliverableUrl = (deliverableId: string) => {
  return `/v1/deliverables/${deliverableId}/publish`;
};

export const publishDeliverable = async (
  deliverableId: string,
  options?: RequestInit,
): Promise<publishDeliverableResponse> => {
  return customFetch<publishDeliverableResponse>(
    getPublishDeliverableUrl(deliverableId),
    {
      ...options,
      method: 'PATCH',
    },
  );
};

export type rejectDeliverableResponse200 = {
  data: DeliverableDto;
  status: 200;
};

export type rejectDeliverableResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type rejectDeliverableResponse404 = {
  data: ErrorDto;
  status: 404;
};

export type rejectDeliverableResponseSuccess = rejectDeliverableResponse200 & {
  headers: Headers;
};
export type rejectDeliverableResponseError = (
  | rejectDeliverableResponse400
  | rejectDeliverableResponse404
) & {
  headers: Headers;
};

export type rejectDeliverableResponse =
  | rejectDeliverableResponseSuccess
  | rejectDeliverableResponseError;

export const getRejectDeliverableUrl = (deliverableId: string) => {
  return `/v1/deliverables/${deliverableId}/reject`;
};

export const rejectDeliverable = async (
  deliverableId: string,
  rejectDeliverableDto: RejectDeliverableDto,
  options?: RequestInit,
): Promise<rejectDeliverableResponse> => {
  return customFetch<rejectDeliverableResponse>(
    getRejectDeliverableUrl(deliverableId),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(rejectDeliverableDto),
    },
  );
};

export type importDeliverableResponse201 = {
  data: void;
  status: 201;
};

export type importDeliverableResponseSuccess = importDeliverableResponse201 & {
  headers: Headers;
};
export type importDeliverableResponse = importDeliverableResponseSuccess;

export const getImportDeliverableUrl = (
  clientOrderItemId: string,
  type:
    | 'SHOWROOM'
    | 'ROOMPLANS'
    | 'VIRTUAL_TOUR'
    | 'GAUSSIAN_SPLATTING'
    | 'FLYTHROUGH'
    | 'REPORT'
    | 'COSTING'
    | 'LINK'
    | 'ENERGY_PERFORMANCE_DIAGNOSTICS',
) => {
  return `/v1/deliverables/import/${clientOrderItemId}/${type}`;
};

export const importDeliverable = async (
  clientOrderItemId: string,
  type:
    | 'SHOWROOM'
    | 'ROOMPLANS'
    | 'VIRTUAL_TOUR'
    | 'GAUSSIAN_SPLATTING'
    | 'FLYTHROUGH'
    | 'REPORT'
    | 'COSTING'
    | 'LINK'
    | 'ENERGY_PERFORMANCE_DIAGNOSTICS',
  importDeliverableBody: ImportDeliverableBody,
  options?: RequestInit,
): Promise<importDeliverableResponse> => {
  const formData = new FormData();
  if (importDeliverableBody.file !== undefined) {
    formData.append(`file`, importDeliverableBody.file);
  }

  return customFetch<importDeliverableResponse>(
    getImportDeliverableUrl(clientOrderItemId, type),
    {
      ...options,
      method: 'POST',
      body: formData,
    },
  );
};

export type getRoomplansResponse200 = {
  data: string;
  status: 200;
};

export type getRoomplansResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type getRoomplansResponse404 = {
  data: ErrorDto;
  status: 404;
};

export type getRoomplansResponseSuccess = getRoomplansResponse200 & {
  headers: Headers;
};
export type getRoomplansResponseError = (
  | getRoomplansResponse400
  | getRoomplansResponse404
) & {
  headers: Headers;
};

export type getRoomplansResponse =
  | getRoomplansResponseSuccess
  | getRoomplansResponseError;

export const getGetRoomplansUrl = (deliverableId: string) => {
  return `/v1/deliverables/${deliverableId}/roomplans`;
};

export const getRoomplans = async (
  deliverableId: string,
  options?: RequestInit,
): Promise<getRoomplansResponse> => {
  return customFetch<getRoomplansResponse>(getGetRoomplansUrl(deliverableId), {
    ...options,
    method: 'GET',
  });
};

export type uploadRoomplansResponse201 = {
  data: string;
  status: 201;
};

export type uploadRoomplansResponseSuccess = uploadRoomplansResponse201 & {
  headers: Headers;
};
export type uploadRoomplansResponse = uploadRoomplansResponseSuccess;

export const getUploadRoomplansUrl = (deliverableId: string) => {
  return `/v1/deliverables/${deliverableId}/roomplans`;
};

export const uploadRoomplans = async (
  deliverableId: string,
  uploadRoomplansBody: UploadRoomplansBody,
  options?: RequestInit,
): Promise<uploadRoomplansResponse> => {
  const formData = new FormData();
  if (uploadRoomplansBody.file !== undefined) {
    formData.append(`file`, uploadRoomplansBody.file);
  }

  return customFetch<uploadRoomplansResponse>(
    getUploadRoomplansUrl(deliverableId),
    {
      ...options,
      method: 'POST',
      body: formData,
    },
  );
};

export type cancelDeliverableResponse200 = {
  data: DeliverableDto;
  status: 200;
};

export type cancelDeliverableResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type cancelDeliverableResponse404 = {
  data: ErrorDto;
  status: 404;
};

export type cancelDeliverableResponseSuccess = cancelDeliverableResponse200 & {
  headers: Headers;
};
export type cancelDeliverableResponseError = (
  | cancelDeliverableResponse400
  | cancelDeliverableResponse404
) & {
  headers: Headers;
};

export type cancelDeliverableResponse =
  | cancelDeliverableResponseSuccess
  | cancelDeliverableResponseError;

export const getCancelDeliverableUrl = (deliverableId: string) => {
  return `/v1/deliverables/${deliverableId}/cancel`;
};

export const cancelDeliverable = async (
  deliverableId: string,
  options?: RequestInit,
): Promise<cancelDeliverableResponse> => {
  return customFetch<cancelDeliverableResponse>(
    getCancelDeliverableUrl(deliverableId),
    {
      ...options,
      method: 'PATCH',
    },
  );
};

export type relaunchDeliverableResponse200 = {
  data: DeliverableDto;
  status: 200;
};

export type relaunchDeliverableResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type relaunchDeliverableResponse404 = {
  data: ErrorDto;
  status: 404;
};

export type relaunchDeliverableResponseSuccess =
  relaunchDeliverableResponse200 & {
    headers: Headers;
  };
export type relaunchDeliverableResponseError = (
  | relaunchDeliverableResponse400
  | relaunchDeliverableResponse404
) & {
  headers: Headers;
};

export type relaunchDeliverableResponse =
  | relaunchDeliverableResponseSuccess
  | relaunchDeliverableResponseError;

export const getRelaunchDeliverableUrl = (deliverableId: string) => {
  return `/v1/deliverables/${deliverableId}/relaunch`;
};

export const relaunchDeliverable = async (
  deliverableId: string,
  options?: RequestInit,
): Promise<relaunchDeliverableResponse> => {
  return customFetch<relaunchDeliverableResponse>(
    getRelaunchDeliverableUrl(deliverableId),
    {
      ...options,
      method: 'PATCH',
    },
  );
};

export type forceProcessedStatusResponse200 = {
  data: DeliverableDto;
  status: 200;
};

export type forceProcessedStatusResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type forceProcessedStatusResponse404 = {
  data: ErrorDto;
  status: 404;
};

export type forceProcessedStatusResponseSuccess =
  forceProcessedStatusResponse200 & {
    headers: Headers;
  };
export type forceProcessedStatusResponseError = (
  | forceProcessedStatusResponse400
  | forceProcessedStatusResponse404
) & {
  headers: Headers;
};

export type forceProcessedStatusResponse =
  | forceProcessedStatusResponseSuccess
  | forceProcessedStatusResponseError;

export const getForceProcessedStatusUrl = (deliverableId: string) => {
  return `/v1/deliverables/${deliverableId}/force-processed-status`;
};

export const forceProcessedStatus = async (
  deliverableId: string,
  options?: RequestInit,
): Promise<forceProcessedStatusResponse> => {
  return customFetch<forceProcessedStatusResponse>(
    getForceProcessedStatusUrl(deliverableId),
    {
      ...options,
      method: 'PATCH',
    },
  );
};

export type getVirtualTourResponse200 = {
  data: DeliverableVirtualTourDto;
  status: 200;
};

export type getVirtualTourResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type getVirtualTourResponse404 = {
  data: ErrorDto;
  status: 404;
};

export type getVirtualTourResponseSuccess = getVirtualTourResponse200 & {
  headers: Headers;
};
export type getVirtualTourResponseError = (
  | getVirtualTourResponse400
  | getVirtualTourResponse404
) & {
  headers: Headers;
};

export type getVirtualTourResponse =
  | getVirtualTourResponseSuccess
  | getVirtualTourResponseError;

export const getGetVirtualTourUrl = (deliverableId: string) => {
  return `/v1/deliverables/${deliverableId}/virtual-tour`;
};

export const getVirtualTour = async (
  deliverableId: string,
  options?: RequestInit,
): Promise<getVirtualTourResponse> => {
  return customFetch<getVirtualTourResponse>(
    getGetVirtualTourUrl(deliverableId),
    {
      ...options,
      method: 'GET',
    },
  );
};

export type editVirtualTourResponse200 = {
  data: DeliverableVirtualTourDto;
  status: 200;
};

export type editVirtualTourResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type editVirtualTourResponse404 = {
  data: ErrorDto;
  status: 404;
};

export type editVirtualTourResponseSuccess = editVirtualTourResponse200 & {
  headers: Headers;
};
export type editVirtualTourResponseError = (
  | editVirtualTourResponse400
  | editVirtualTourResponse404
) & {
  headers: Headers;
};

export type editVirtualTourResponse =
  | editVirtualTourResponseSuccess
  | editVirtualTourResponseError;

export const getEditVirtualTourUrl = (deliverableId: string) => {
  return `/v1/deliverables/${deliverableId}/edit-virtual-tour`;
};

export const editVirtualTour = async (
  deliverableId: string,
  deliverableVirtualTourDto: DeliverableVirtualTourDto,
  options?: RequestInit,
): Promise<editVirtualTourResponse> => {
  return customFetch<editVirtualTourResponse>(
    getEditVirtualTourUrl(deliverableId),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(deliverableVirtualTourDto),
    },
  );
};

export type removeWindowsResponse200 = {
  data: DeliverableVirtualTourDto;
  status: 200;
};

export type removeWindowsResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type removeWindowsResponse404 = {
  data: ErrorDto;
  status: 404;
};

export type removeWindowsResponseSuccess = removeWindowsResponse200 & {
  headers: Headers;
};
export type removeWindowsResponseError = (
  | removeWindowsResponse400
  | removeWindowsResponse404
) & {
  headers: Headers;
};

export type removeWindowsResponse =
  | removeWindowsResponseSuccess
  | removeWindowsResponseError;

export const getRemoveWindowsUrl = (deliverableId: string) => {
  return `/v1/deliverables/${deliverableId}/remove-windows`;
};

export const removeWindows = async (
  deliverableId: string,
  deliverableVirtualTourDto: DeliverableVirtualTourDto,
  options?: RequestInit,
): Promise<removeWindowsResponse> => {
  return customFetch<removeWindowsResponse>(
    getRemoveWindowsUrl(deliverableId),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(deliverableVirtualTourDto),
    },
  );
};

export type resetVirtualTourResponse200 = {
  data: void;
  status: 200;
};

export type resetVirtualTourResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type resetVirtualTourResponse404 = {
  data: ErrorDto;
  status: 404;
};

export type resetVirtualTourResponseSuccess = resetVirtualTourResponse200 & {
  headers: Headers;
};
export type resetVirtualTourResponseError = (
  | resetVirtualTourResponse400
  | resetVirtualTourResponse404
) & {
  headers: Headers;
};

export type resetVirtualTourResponse =
  | resetVirtualTourResponseSuccess
  | resetVirtualTourResponseError;

export const getResetVirtualTourUrl = (deliverableId: string) => {
  return `/v1/deliverables/${deliverableId}/reset-virtual-tour`;
};

export const resetVirtualTour = async (
  deliverableId: string,
  options?: RequestInit,
): Promise<resetVirtualTourResponse> => {
  return customFetch<resetVirtualTourResponse>(
    getResetVirtualTourUrl(deliverableId),
    {
      ...options,
      method: 'PATCH',
    },
  );
};

export type maskWindowsResponse200 = {
  data: void;
  status: 200;
};

export type maskWindowsResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type maskWindowsResponse404 = {
  data: ErrorDto;
  status: 404;
};

export type maskWindowsResponseSuccess = maskWindowsResponse200 & {
  headers: Headers;
};
export type maskWindowsResponseError = (
  | maskWindowsResponse400
  | maskWindowsResponse404
) & {
  headers: Headers;
};

export type maskWindowsResponse =
  | maskWindowsResponseSuccess
  | maskWindowsResponseError;

export const getMaskWindowsUrl = (deliverableId: string) => {
  return `/v1/deliverables/${deliverableId}/mask-windows`;
};

export const maskWindows = async (
  deliverableId: string,
  options?: RequestInit,
): Promise<maskWindowsResponse> => {
  return customFetch<maskWindowsResponse>(getMaskWindowsUrl(deliverableId), {
    ...options,
    method: 'PATCH',
  });
};

export type validateDeliverableResponse200 = {
  data: DeliverableDto;
  status: 200;
};

export type validateDeliverableResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type validateDeliverableResponse404 = {
  data: ErrorDto;
  status: 404;
};

export type validateDeliverableResponseSuccess =
  validateDeliverableResponse200 & {
    headers: Headers;
  };
export type validateDeliverableResponseError = (
  | validateDeliverableResponse400
  | validateDeliverableResponse404
) & {
  headers: Headers;
};

export type validateDeliverableResponse =
  | validateDeliverableResponseSuccess
  | validateDeliverableResponseError;

export const getValidateDeliverableUrl = (deliverableId: string) => {
  return `/v1/deliverables/${deliverableId}/validate`;
};

export const validateDeliverable = async (
  deliverableId: string,
  options?: RequestInit,
): Promise<validateDeliverableResponse> => {
  return customFetch<validateDeliverableResponse>(
    getValidateDeliverableUrl(deliverableId),
    {
      ...options,
      method: 'PATCH',
    },
  );
};

export type getFlowResponse200 = {
  data: FlowDto;
  status: 200;
};

export type getFlowResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type getFlowResponse404 = {
  data: ErrorDto;
  status: 404;
};

export type getFlowResponseSuccess = getFlowResponse200 & {
  headers: Headers;
};
export type getFlowResponseError = (getFlowResponse400 | getFlowResponse404) & {
  headers: Headers;
};

export type getFlowResponse = getFlowResponseSuccess | getFlowResponseError;

export const getGetFlowUrl = (id: string) => {
  return `/v1/flows/${id}`;
};

export const getFlow = async (
  id: string,
  options?: RequestInit,
): Promise<getFlowResponse> => {
  return customFetch<getFlowResponse>(getGetFlowUrl(id), {
    ...options,
    method: 'GET',
  });
};

export type getFlowByClientOrderItemIdResponse200 = {
  data: FlowDto;
  status: 200;
};

export type getFlowByClientOrderItemIdResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type getFlowByClientOrderItemIdResponse404 = {
  data: ErrorDto;
  status: 404;
};

export type getFlowByClientOrderItemIdResponseSuccess =
  getFlowByClientOrderItemIdResponse200 & {
    headers: Headers;
  };
export type getFlowByClientOrderItemIdResponseError = (
  | getFlowByClientOrderItemIdResponse400
  | getFlowByClientOrderItemIdResponse404
) & {
  headers: Headers;
};

export type getFlowByClientOrderItemIdResponse =
  | getFlowByClientOrderItemIdResponseSuccess
  | getFlowByClientOrderItemIdResponseError;

export const getGetFlowByClientOrderItemIdUrl = (clientOrderItemId: string) => {
  return `/v1/flows/by-client-order-item/${clientOrderItemId}`;
};

export const getFlowByClientOrderItemId = async (
  clientOrderItemId: string,
  options?: RequestInit,
): Promise<getFlowByClientOrderItemIdResponse> => {
  return customFetch<getFlowByClientOrderItemIdResponse>(
    getGetFlowByClientOrderItemIdUrl(clientOrderItemId),
    {
      ...options,
      method: 'GET',
    },
  );
};

export type getSubmittedFormsResponse200 = {
  data: SubmittedFormDto[];
  status: 200;
};

export type getSubmittedFormsResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type getSubmittedFormsResponse404 = {
  data: ErrorDto;
  status: 404;
};

export type getSubmittedFormsResponseSuccess = getSubmittedFormsResponse200 & {
  headers: Headers;
};
export type getSubmittedFormsResponseError = (
  | getSubmittedFormsResponse400
  | getSubmittedFormsResponse404
) & {
  headers: Headers;
};

export type getSubmittedFormsResponse =
  | getSubmittedFormsResponseSuccess
  | getSubmittedFormsResponseError;

export const getGetSubmittedFormsUrl = (clientOrderItemId: string) => {
  return `/v1/exported-flows/${clientOrderItemId}/submitted-forms`;
};

export const getSubmittedForms = async (
  clientOrderItemId: string,
  options?: RequestInit,
): Promise<getSubmittedFormsResponse> => {
  return customFetch<getSubmittedFormsResponse>(
    getGetSubmittedFormsUrl(clientOrderItemId),
    {
      ...options,
      method: 'GET',
    },
  );
};

export type updateSubmittedFormsResponse201 = {
  data: SubmittedFormDto[];
  status: 201;
};

export type updateSubmittedFormsResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type updateSubmittedFormsResponse404 = {
  data: ErrorDto;
  status: 404;
};

export type updateSubmittedFormsResponseSuccess =
  updateSubmittedFormsResponse201 & {
    headers: Headers;
  };
export type updateSubmittedFormsResponseError = (
  | updateSubmittedFormsResponse400
  | updateSubmittedFormsResponse404
) & {
  headers: Headers;
};

export type updateSubmittedFormsResponse =
  | updateSubmittedFormsResponseSuccess
  | updateSubmittedFormsResponseError;

export const getUpdateSubmittedFormsUrl = (clientOrderItemId: string) => {
  return `/v1/exported-flows/${clientOrderItemId}/submitted-forms`;
};

export const updateSubmittedForms = async (
  clientOrderItemId: string,
  submittedFormDto: SubmittedFormDto[],
  options?: RequestInit,
): Promise<updateSubmittedFormsResponse> => {
  return customFetch<updateSubmittedFormsResponse>(
    getUpdateSubmittedFormsUrl(clientOrderItemId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(submittedFormDto),
    },
  );
};

export type getExportedFlowResponse200 = {
  data: ExportedFlowJsonDto;
  status: 200;
};

export type getExportedFlowResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type getExportedFlowResponse404 = {
  data: ErrorDto;
  status: 404;
};

export type getExportedFlowResponseSuccess = getExportedFlowResponse200 & {
  headers: Headers;
};
export type getExportedFlowResponseError = (
  | getExportedFlowResponse400
  | getExportedFlowResponse404
) & {
  headers: Headers;
};

export type getExportedFlowResponse =
  | getExportedFlowResponseSuccess
  | getExportedFlowResponseError;

export const getGetExportedFlowUrl = (clientOrderItemId: string) => {
  return `/v1/exported-flows/${clientOrderItemId}/exported-flow`;
};

export const getExportedFlow = async (
  clientOrderItemId: string,
  options?: RequestInit,
): Promise<getExportedFlowResponse> => {
  return customFetch<getExportedFlowResponse>(
    getGetExportedFlowUrl(clientOrderItemId),
    {
      ...options,
      method: 'GET',
    },
  );
};

export type updateExportedFlowResponse200 = {
  data: ExportedFlowJsonDto;
  status: 200;
};

export type updateExportedFlowResponse201 = {
  data: UpdateExportedFlow201;
  status: 201;
};

export type updateExportedFlowResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type updateExportedFlowResponse404 = {
  data: ErrorDto;
  status: 404;
};

export type updateExportedFlowResponseSuccess = (
  | updateExportedFlowResponse200
  | updateExportedFlowResponse201
) & {
  headers: Headers;
};
export type updateExportedFlowResponseError = (
  | updateExportedFlowResponse400
  | updateExportedFlowResponse404
) & {
  headers: Headers;
};

export type updateExportedFlowResponse =
  | updateExportedFlowResponseSuccess
  | updateExportedFlowResponseError;

export const getUpdateExportedFlowUrl = (
  clientOrderItemId: string,
  params: UpdateExportedFlowParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/exported-flows/${clientOrderItemId}/exported-flow?${stringifiedParams}`
    : `/v1/exported-flows/${clientOrderItemId}/exported-flow`;
};

export const updateExportedFlow = async (
  clientOrderItemId: string,
  exportedFlowJsonDto: ExportedFlowJsonDto,
  params: UpdateExportedFlowParams,
  options?: RequestInit,
): Promise<updateExportedFlowResponse> => {
  return customFetch<updateExportedFlowResponse>(
    getUpdateExportedFlowUrl(clientOrderItemId, params),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(exportedFlowJsonDto),
    },
  );
};

export type getOrderResultResponse200 = {
  data: OrderResultJsonDto;
  status: 200;
};

export type getOrderResultResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type getOrderResultResponse404 = {
  data: ErrorDto;
  status: 404;
};

export type getOrderResultResponseSuccess = getOrderResultResponse200 & {
  headers: Headers;
};
export type getOrderResultResponseError = (
  | getOrderResultResponse400
  | getOrderResultResponse404
) & {
  headers: Headers;
};

export type getOrderResultResponse =
  | getOrderResultResponseSuccess
  | getOrderResultResponseError;

export const getGetOrderResultUrl = (clientOrderItemId: string) => {
  return `/v1/order-result/${clientOrderItemId}/order-result`;
};

export const getOrderResult = async (
  clientOrderItemId: string,
  options?: RequestInit,
): Promise<getOrderResultResponse> => {
  return customFetch<getOrderResultResponse>(
    getGetOrderResultUrl(clientOrderItemId),
    {
      ...options,
      method: 'GET',
    },
  );
};

export type updateOrderResultResponse200 = {
  data: OrderResultJsonDto;
  status: 200;
};

export type updateOrderResultResponse201 = {
  data: UpdateOrderResult201;
  status: 201;
};

export type updateOrderResultResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type updateOrderResultResponse404 = {
  data: ErrorDto;
  status: 404;
};

export type updateOrderResultResponseSuccess = (
  | updateOrderResultResponse200
  | updateOrderResultResponse201
) & {
  headers: Headers;
};
export type updateOrderResultResponseError = (
  | updateOrderResultResponse400
  | updateOrderResultResponse404
) & {
  headers: Headers;
};

export type updateOrderResultResponse =
  | updateOrderResultResponseSuccess
  | updateOrderResultResponseError;

export const getUpdateOrderResultUrl = (clientOrderItemId: string) => {
  return `/v1/order-result/${clientOrderItemId}/order-result`;
};

export const updateOrderResult = async (
  clientOrderItemId: string,
  orderResultJsonDto: OrderResultJsonDto,
  options?: RequestInit,
): Promise<updateOrderResultResponse> => {
  return customFetch<updateOrderResultResponse>(
    getUpdateOrderResultUrl(clientOrderItemId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(orderResultJsonDto),
    },
  );
};

export type healthCheckResponse200 = {
  data: void;
  status: 200;
};

export type healthCheckResponseSuccess = healthCheckResponse200 & {
  headers: Headers;
};
export type healthCheckResponse = healthCheckResponseSuccess;

export const getHealthCheckUrl = () => {
  return `/v1/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<healthCheckResponse> => {
  return customFetch<healthCheckResponse>(getHealthCheckUrl(), {
    ...options,
    method: 'GET',
  });
};

export type getClientOrderItemsResponse200 = {
  data: GetClientOrderItems200;
  status: 200;
};

export type getClientOrderItemsResponseSuccess =
  getClientOrderItemsResponse200 & {
    headers: Headers;
  };
export type getClientOrderItemsResponse = getClientOrderItemsResponseSuccess;

export const getGetClientOrderItemsUrl = (
  params?: GetClientOrderItemsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/client-order-items?${stringifiedParams}`
    : `/v1/client-order-items`;
};

export const getClientOrderItems = async (
  params?: GetClientOrderItemsParams,
  options?: RequestInit,
): Promise<getClientOrderItemsResponse> => {
  return customFetch<getClientOrderItemsResponse>(
    getGetClientOrderItemsUrl(params),
    {
      ...options,
      method: 'GET',
    },
  );
};

export type createClientOrderItemResponse201 = {
  data: ClientOrderItemDto;
  status: 201;
};

export type createClientOrderItemResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type createClientOrderItemResponseSuccess =
  createClientOrderItemResponse201 & {
    headers: Headers;
  };
export type createClientOrderItemResponseError =
  createClientOrderItemResponse400 & {
    headers: Headers;
  };

export type createClientOrderItemResponse =
  | createClientOrderItemResponseSuccess
  | createClientOrderItemResponseError;

export const getCreateClientOrderItemUrl = () => {
  return `/v1/client-order-items`;
};

export const createClientOrderItem = async (
  clientOrderItemCreateDto: ClientOrderItemCreateDto,
  options?: RequestInit,
): Promise<createClientOrderItemResponse> => {
  return customFetch<createClientOrderItemResponse>(
    getCreateClientOrderItemUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(clientOrderItemCreateDto),
    },
  );
};

export type getClientOrderItemByIdResponse200 = {
  data: ClientOrderItemDto;
  status: 200;
};

export type getClientOrderItemByIdResponse404 = {
  data: void;
  status: 404;
};

export type getClientOrderItemByIdResponseSuccess =
  getClientOrderItemByIdResponse200 & {
    headers: Headers;
  };
export type getClientOrderItemByIdResponseError =
  getClientOrderItemByIdResponse404 & {
    headers: Headers;
  };

export type getClientOrderItemByIdResponse =
  | getClientOrderItemByIdResponseSuccess
  | getClientOrderItemByIdResponseError;

export const getGetClientOrderItemByIdUrl = (id: string) => {
  return `/v1/client-order-items/${id}`;
};

export const getClientOrderItemById = async (
  id: string,
  options?: RequestInit,
): Promise<getClientOrderItemByIdResponse> => {
  return customFetch<getClientOrderItemByIdResponse>(
    getGetClientOrderItemByIdUrl(id),
    {
      ...options,
      method: 'GET',
    },
  );
};

export type updateClientOrderItemByIdResponse200 = {
  data: ClientOrderItemDto;
  status: 200;
};

export type updateClientOrderItemByIdResponse404 = {
  data: void;
  status: 404;
};

export type updateClientOrderItemByIdResponseSuccess =
  updateClientOrderItemByIdResponse200 & {
    headers: Headers;
  };
export type updateClientOrderItemByIdResponseError =
  updateClientOrderItemByIdResponse404 & {
    headers: Headers;
  };

export type updateClientOrderItemByIdResponse =
  | updateClientOrderItemByIdResponseSuccess
  | updateClientOrderItemByIdResponseError;

export const getUpdateClientOrderItemByIdUrl = (id: string) => {
  return `/v1/client-order-items/${id}`;
};

export const updateClientOrderItemById = async (
  id: string,
  clientOrderItemUpdateDto: ClientOrderItemUpdateDto,
  options?: RequestInit,
): Promise<updateClientOrderItemByIdResponse> => {
  return customFetch<updateClientOrderItemByIdResponse>(
    getUpdateClientOrderItemByIdUrl(id),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(clientOrderItemUpdateDto),
    },
  );
};

export type updateClientOrderItemsInvoicingStatusResponse200 = {
  data: ClientOrderItemDto;
  status: 200;
};

export type updateClientOrderItemsInvoicingStatusResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type updateClientOrderItemsInvoicingStatusResponse404 = {
  data: ErrorDto;
  status: 404;
};

export type updateClientOrderItemsInvoicingStatusResponseSuccess =
  updateClientOrderItemsInvoicingStatusResponse200 & {
    headers: Headers;
  };
export type updateClientOrderItemsInvoicingStatusResponseError = (
  | updateClientOrderItemsInvoicingStatusResponse400
  | updateClientOrderItemsInvoicingStatusResponse404
) & {
  headers: Headers;
};

export type updateClientOrderItemsInvoicingStatusResponse =
  | updateClientOrderItemsInvoicingStatusResponseSuccess
  | updateClientOrderItemsInvoicingStatusResponseError;

export const getUpdateClientOrderItemsInvoicingStatusUrl = () => {
  return `/v1/client-order-items/invoicing-status`;
};

export const updateClientOrderItemsInvoicingStatus = async (
  clientOrderItemBatchUpdateInvoicingStatusDto: ClientOrderItemBatchUpdateInvoicingStatusDto,
  options?: RequestInit,
): Promise<updateClientOrderItemsInvoicingStatusResponse> => {
  return customFetch<updateClientOrderItemsInvoicingStatusResponse>(
    getUpdateClientOrderItemsInvoicingStatusUrl(),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(clientOrderItemBatchUpdateInvoicingStatusDto),
    },
  );
};

export type getResourceUrlResponse200 = {
  data: string;
  status: 200;
};

export type getResourceUrlResponseSuccess = getResourceUrlResponse200 & {
  headers: Headers;
};
export type getResourceUrlResponse = getResourceUrlResponseSuccess;

export const getGetResourceUrlUrl = (
  clientOrderItemId: string,
  params: GetResourceUrlParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/client-order-items/${clientOrderItemId}/resource?${stringifiedParams}`
    : `/v1/client-order-items/${clientOrderItemId}/resource`;
};

export const getResourceUrl = async (
  clientOrderItemId: string,
  params: GetResourceUrlParams,
  options?: RequestInit,
): Promise<getResourceUrlResponse> => {
  return customFetch<getResourceUrlResponse>(
    getGetResourceUrlUrl(clientOrderItemId, params),
    {
      ...options,
      method: 'GET',
    },
  );
};

export type uploadResourceResponse201 = {
  data: string;
  status: 201;
};

export type uploadResourceResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type uploadResourceResponse404 = {
  data: ErrorDto;
  status: 404;
};

export type uploadResourceResponseSuccess = uploadResourceResponse201 & {
  headers: Headers;
};
export type uploadResourceResponseError = (
  | uploadResourceResponse400
  | uploadResourceResponse404
) & {
  headers: Headers;
};

export type uploadResourceResponse =
  | uploadResourceResponseSuccess
  | uploadResourceResponseError;

export const getUploadResourceUrl = (
  clientOrderItemId: string,
  params: UploadResourceParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/client-order-items/${clientOrderItemId}/resource?${stringifiedParams}`
    : `/v1/client-order-items/${clientOrderItemId}/resource`;
};

export const uploadResource = async (
  clientOrderItemId: string,
  uploadResourceBody: UploadResourceBody,
  params: UploadResourceParams,
  options?: RequestInit,
): Promise<uploadResourceResponse> => {
  const formData = new FormData();
  if (uploadResourceBody.file !== undefined) {
    formData.append(`file`, uploadResourceBody.file);
  }

  return customFetch<uploadResourceResponse>(
    getUploadResourceUrl(clientOrderItemId, params),
    {
      ...options,
      method: 'POST',
      body: formData,
    },
  );
};

export type rateForClientOrderItemResponse200 = {
  data: ClientOrderItemRateResponseDto;
  status: 200;
};

export type rateForClientOrderItemResponse201 = {
  data: ClientOrderItemRateResponseDto;
  status: 201;
};

export type rateForClientOrderItemResponse400 = {
  data: void;
  status: 400;
};

export type rateForClientOrderItemResponseSuccess = (
  | rateForClientOrderItemResponse200
  | rateForClientOrderItemResponse201
) & {
  headers: Headers;
};
export type rateForClientOrderItemResponseError =
  rateForClientOrderItemResponse400 & {
    headers: Headers;
  };

export type rateForClientOrderItemResponse =
  | rateForClientOrderItemResponseSuccess
  | rateForClientOrderItemResponseError;

export const getRateForClientOrderItemUrl = () => {
  return `/v1/client-order-items/rate`;
};

export const rateForClientOrderItem = async (
  clientOrderItemRateBodyDto: ClientOrderItemRateBodyDto,
  options?: RequestInit,
): Promise<rateForClientOrderItemResponse> => {
  return customFetch<rateForClientOrderItemResponse>(
    getRateForClientOrderItemUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(clientOrderItemRateBodyDto),
    },
  );
};

export type cancelClientOrderItemResponse200 = {
  data: ClientOrderItemDto;
  status: 200;
};

export type cancelClientOrderItemResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type cancelClientOrderItemResponse404 = {
  data: ErrorDto;
  status: 404;
};

export type cancelClientOrderItemResponseSuccess =
  cancelClientOrderItemResponse200 & {
    headers: Headers;
  };
export type cancelClientOrderItemResponseError = (
  | cancelClientOrderItemResponse400
  | cancelClientOrderItemResponse404
) & {
  headers: Headers;
};

export type cancelClientOrderItemResponse =
  | cancelClientOrderItemResponseSuccess
  | cancelClientOrderItemResponseError;

export const getCancelClientOrderItemUrl = (id: string) => {
  return `/v1/client-order-items/${id}/cancel`;
};

export const cancelClientOrderItem = async (
  id: string,
  options?: RequestInit,
): Promise<cancelClientOrderItemResponse> => {
  return customFetch<cancelClientOrderItemResponse>(
    getCancelClientOrderItemUrl(id),
    {
      ...options,
      method: 'PATCH',
    },
  );
};

export type getSupplierOrdersBySupplierIdResponse200 = {
  data: GetSupplierOrdersBySupplierId200;
  status: 200;
};

export type getSupplierOrdersBySupplierIdResponseSuccess =
  getSupplierOrdersBySupplierIdResponse200 & {
    headers: Headers;
  };
export type getSupplierOrdersBySupplierIdResponse =
  getSupplierOrdersBySupplierIdResponseSuccess;

export const getGetSupplierOrdersBySupplierIdUrl = (
  supplierId: string,
  params?: GetSupplierOrdersBySupplierIdParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/supplier-orders/by-supplier/${supplierId}?${stringifiedParams}`
    : `/v1/supplier-orders/by-supplier/${supplierId}`;
};

export const getSupplierOrdersBySupplierId = async (
  supplierId: string,
  params?: GetSupplierOrdersBySupplierIdParams,
  options?: RequestInit,
): Promise<getSupplierOrdersBySupplierIdResponse> => {
  return customFetch<getSupplierOrdersBySupplierIdResponse>(
    getGetSupplierOrdersBySupplierIdUrl(supplierId, params),
    {
      ...options,
      method: 'GET',
    },
  );
};

export type getSupplierOrderByIdResponse200 = {
  data: SupplierOrderDto;
  status: 200;
};

export type getSupplierOrderByIdResponse404 = {
  data: void;
  status: 404;
};

export type getSupplierOrderByIdResponseSuccess =
  getSupplierOrderByIdResponse200 & {
    headers: Headers;
  };
export type getSupplierOrderByIdResponseError =
  getSupplierOrderByIdResponse404 & {
    headers: Headers;
  };

export type getSupplierOrderByIdResponse =
  | getSupplierOrderByIdResponseSuccess
  | getSupplierOrderByIdResponseError;

export const getGetSupplierOrderByIdUrl = (id: string) => {
  return `/v1/supplier-orders/${id}`;
};

export const getSupplierOrderById = async (
  id: string,
  options?: RequestInit,
): Promise<getSupplierOrderByIdResponse> => {
  return customFetch<getSupplierOrderByIdResponse>(
    getGetSupplierOrderByIdUrl(id),
    {
      ...options,
      method: 'GET',
    },
  );
};

export type updateSupplierOrderByIdResponse200 = {
  data: SupplierOrderDto;
  status: 200;
};

export type updateSupplierOrderByIdResponse404 = {
  data: void;
  status: 404;
};

export type updateSupplierOrderByIdResponseSuccess =
  updateSupplierOrderByIdResponse200 & {
    headers: Headers;
  };
export type updateSupplierOrderByIdResponseError =
  updateSupplierOrderByIdResponse404 & {
    headers: Headers;
  };

export type updateSupplierOrderByIdResponse =
  | updateSupplierOrderByIdResponseSuccess
  | updateSupplierOrderByIdResponseError;

export const getUpdateSupplierOrderByIdUrl = (id: string) => {
  return `/v1/supplier-orders/${id}`;
};

export const updateSupplierOrderById = async (
  id: string,
  supplierOrderUpdateDto: SupplierOrderUpdateDto,
  options?: RequestInit,
): Promise<updateSupplierOrderByIdResponse> => {
  return customFetch<updateSupplierOrderByIdResponse>(
    getUpdateSupplierOrderByIdUrl(id),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(supplierOrderUpdateDto),
    },
  );
};

export type getAllSupplierOrdersResponse200 = {
  data: GetAllSupplierOrders200;
  status: 200;
};

export type getAllSupplierOrdersResponseSuccess =
  getAllSupplierOrdersResponse200 & {
    headers: Headers;
  };
export type getAllSupplierOrdersResponse = getAllSupplierOrdersResponseSuccess;

export const getGetAllSupplierOrdersUrl = (
  params?: GetAllSupplierOrdersParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/supplier-orders?${stringifiedParams}`
    : `/v1/supplier-orders`;
};

export const getAllSupplierOrders = async (
  params?: GetAllSupplierOrdersParams,
  options?: RequestInit,
): Promise<getAllSupplierOrdersResponse> => {
  return customFetch<getAllSupplierOrdersResponse>(
    getGetAllSupplierOrdersUrl(params),
    {
      ...options,
      method: 'GET',
    },
  );
};

export type createSupplierOrderResponse201 = {
  data: SupplierOrderDto;
  status: 201;
};

export type createSupplierOrderResponse400 = {
  data: void;
  status: 400;
};

export type createSupplierOrderResponseSuccess =
  createSupplierOrderResponse201 & {
    headers: Headers;
  };
export type createSupplierOrderResponseError =
  createSupplierOrderResponse400 & {
    headers: Headers;
  };

export type createSupplierOrderResponse =
  | createSupplierOrderResponseSuccess
  | createSupplierOrderResponseError;

export const getCreateSupplierOrderUrl = () => {
  return `/v1/supplier-orders`;
};

export const createSupplierOrder = async (
  supplierOrderCreateDto: SupplierOrderCreateDto,
  options?: RequestInit,
): Promise<createSupplierOrderResponse> => {
  return customFetch<createSupplierOrderResponse>(getCreateSupplierOrderUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(supplierOrderCreateDto),
  });
};

export type cancelSupplierOrderByIdResponse200 = {
  data: void;
  status: 200;
};

export type cancelSupplierOrderByIdResponse404 = {
  data: void;
  status: 404;
};

export type cancelSupplierOrderByIdResponseSuccess =
  cancelSupplierOrderByIdResponse200 & {
    headers: Headers;
  };
export type cancelSupplierOrderByIdResponseError =
  cancelSupplierOrderByIdResponse404 & {
    headers: Headers;
  };

export type cancelSupplierOrderByIdResponse =
  | cancelSupplierOrderByIdResponseSuccess
  | cancelSupplierOrderByIdResponseError;

export const getCancelSupplierOrderByIdUrl = (id: string) => {
  return `/v1/supplier-orders/${id}/cancel`;
};

export const cancelSupplierOrderById = async (
  id: string,
  options?: RequestInit,
): Promise<cancelSupplierOrderByIdResponse> => {
  return customFetch<cancelSupplierOrderByIdResponse>(
    getCancelSupplierOrderByIdUrl(id),
    {
      ...options,
      method: 'PUT',
    },
  );
};

export type acceptSupplierOrderByIdResponse200 = {
  data: void;
  status: 200;
};

export type acceptSupplierOrderByIdResponse404 = {
  data: void;
  status: 404;
};

export type acceptSupplierOrderByIdResponseSuccess =
  acceptSupplierOrderByIdResponse200 & {
    headers: Headers;
  };
export type acceptSupplierOrderByIdResponseError =
  acceptSupplierOrderByIdResponse404 & {
    headers: Headers;
  };

export type acceptSupplierOrderByIdResponse =
  | acceptSupplierOrderByIdResponseSuccess
  | acceptSupplierOrderByIdResponseError;

export const getAcceptSupplierOrderByIdUrl = (id: string) => {
  return `/v1/supplier-orders/${id}/accept`;
};

export const acceptSupplierOrderById = async (
  id: string,
  options?: RequestInit,
): Promise<acceptSupplierOrderByIdResponse> => {
  return customFetch<acceptSupplierOrderByIdResponse>(
    getAcceptSupplierOrderByIdUrl(id),
    {
      ...options,
      method: 'PUT',
    },
  );
};

export type refuseSupplierOrderByIdResponse200 = {
  data: void;
  status: 200;
};

export type refuseSupplierOrderByIdResponse404 = {
  data: void;
  status: 404;
};

export type refuseSupplierOrderByIdResponseSuccess =
  refuseSupplierOrderByIdResponse200 & {
    headers: Headers;
  };
export type refuseSupplierOrderByIdResponseError =
  refuseSupplierOrderByIdResponse404 & {
    headers: Headers;
  };

export type refuseSupplierOrderByIdResponse =
  | refuseSupplierOrderByIdResponseSuccess
  | refuseSupplierOrderByIdResponseError;

export const getRefuseSupplierOrderByIdUrl = (id: string) => {
  return `/v1/supplier-orders/${id}/refuse`;
};

export const refuseSupplierOrderById = async (
  id: string,
  options?: RequestInit,
): Promise<refuseSupplierOrderByIdResponse> => {
  return customFetch<refuseSupplierOrderByIdResponse>(
    getRefuseSupplierOrderByIdUrl(id),
    {
      ...options,
      method: 'PUT',
    },
  );
};

export type amendSupplierOrderResponse200 = {
  data: SupplierOrderDto;
  status: 200;
};

export type amendSupplierOrderResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type amendSupplierOrderResponse404 = {
  data: void;
  status: 404;
};

export type amendSupplierOrderResponseSuccess =
  amendSupplierOrderResponse200 & {
    headers: Headers;
  };
export type amendSupplierOrderResponseError = (
  | amendSupplierOrderResponse400
  | amendSupplierOrderResponse404
) & {
  headers: Headers;
};

export type amendSupplierOrderResponse =
  | amendSupplierOrderResponseSuccess
  | amendSupplierOrderResponseError;

export const getAmendSupplierOrderUrl = (id: string) => {
  return `/v1/supplier-orders/${id}/amend`;
};

export const amendSupplierOrder = async (
  id: string,
  amendSupplierOrderDto: AmendSupplierOrderDto,
  options?: RequestInit,
): Promise<amendSupplierOrderResponse> => {
  return customFetch<amendSupplierOrderResponse>(getAmendSupplierOrderUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(amendSupplierOrderDto),
  });
};

export type reproposeSupplierOrderResponse201 = {
  data: SupplierOrderDto;
  status: 201;
};

export type reproposeSupplierOrderResponse400 = {
  data: void;
  status: 400;
};

export type reproposeSupplierOrderResponseSuccess =
  reproposeSupplierOrderResponse201 & {
    headers: Headers;
  };
export type reproposeSupplierOrderResponseError =
  reproposeSupplierOrderResponse400 & {
    headers: Headers;
  };

export type reproposeSupplierOrderResponse =
  | reproposeSupplierOrderResponseSuccess
  | reproposeSupplierOrderResponseError;

export const getReproposeSupplierOrderUrl = (id: string) => {
  return `/v1/supplier-orders/${id}/repropose`;
};

export const reproposeSupplierOrder = async (
  id: string,
  supplierOrderCreateDto: SupplierOrderCreateDto,
  options?: RequestInit,
): Promise<reproposeSupplierOrderResponse> => {
  return customFetch<reproposeSupplierOrderResponse>(
    getReproposeSupplierOrderUrl(id),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(supplierOrderCreateDto),
    },
  );
};

export type getAllClientOrdersByOrderIdResponse200 = {
  data: GetAllClientOrdersByOrderId200;
  status: 200;
};

export type getAllClientOrdersByOrderIdResponseSuccess =
  getAllClientOrdersByOrderIdResponse200 & {
    headers: Headers;
  };
export type getAllClientOrdersByOrderIdResponse =
  getAllClientOrdersByOrderIdResponseSuccess;

export const getGetAllClientOrdersByOrderIdUrl = (
  clientId: string,
  params?: GetAllClientOrdersByOrderIdParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/client-orders/by-client/${clientId}?${stringifiedParams}`
    : `/v1/client-orders/by-client/${clientId}`;
};

export const getAllClientOrdersByOrderId = async (
  clientId: string,
  params?: GetAllClientOrdersByOrderIdParams,
  options?: RequestInit,
): Promise<getAllClientOrdersByOrderIdResponse> => {
  return customFetch<getAllClientOrdersByOrderIdResponse>(
    getGetAllClientOrdersByOrderIdUrl(clientId, params),
    {
      ...options,
      method: 'GET',
    },
  );
};

export type getClientOrderByIdResponse200 = {
  data: ClientOrderDto;
  status: 200;
};

export type getClientOrderByIdResponse404 = {
  data: void;
  status: 404;
};

export type getClientOrderByIdResponseSuccess =
  getClientOrderByIdResponse200 & {
    headers: Headers;
  };
export type getClientOrderByIdResponseError = getClientOrderByIdResponse404 & {
  headers: Headers;
};

export type getClientOrderByIdResponse =
  | getClientOrderByIdResponseSuccess
  | getClientOrderByIdResponseError;

export const getGetClientOrderByIdUrl = (id: string) => {
  return `/v1/client-orders/${id}`;
};

export const getClientOrderById = async (
  id: string,
  options?: RequestInit,
): Promise<getClientOrderByIdResponse> => {
  return customFetch<getClientOrderByIdResponse>(getGetClientOrderByIdUrl(id), {
    ...options,
    method: 'GET',
  });
};

export type getAllClientOrdersResponse200 = {
  data: GetAllClientOrders200;
  status: 200;
};

export type getAllClientOrdersResponseSuccess =
  getAllClientOrdersResponse200 & {
    headers: Headers;
  };
export type getAllClientOrdersResponse = getAllClientOrdersResponseSuccess;

export const getGetAllClientOrdersUrl = (params?: GetAllClientOrdersParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/client-orders?${stringifiedParams}`
    : `/v1/client-orders`;
};

export const getAllClientOrders = async (
  params?: GetAllClientOrdersParams,
  options?: RequestInit,
): Promise<getAllClientOrdersResponse> => {
  return customFetch<getAllClientOrdersResponse>(
    getGetAllClientOrdersUrl(params),
    {
      ...options,
      method: 'GET',
    },
  );
};

export type createClientOrderResponse201 = {
  data: ClientOrderDto;
  status: 201;
};

export type createClientOrderResponse400 = {
  data: void;
  status: 400;
};

export type createClientOrderResponseSuccess = createClientOrderResponse201 & {
  headers: Headers;
};
export type createClientOrderResponseError = createClientOrderResponse400 & {
  headers: Headers;
};

export type createClientOrderResponse =
  | createClientOrderResponseSuccess
  | createClientOrderResponseError;

export const getCreateClientOrderUrl = () => {
  return `/v1/client-orders`;
};

export const createClientOrder = async (
  clientOrderCreateDto: ClientOrderCreateDto,
  options?: RequestInit,
): Promise<createClientOrderResponse> => {
  return customFetch<createClientOrderResponse>(getCreateClientOrderUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(clientOrderCreateDto),
  });
};

export type getSupplierOrderItemsResponse200 = {
  data: GetSupplierOrderItems200;
  status: 200;
};

export type getSupplierOrderItemsResponseSuccess =
  getSupplierOrderItemsResponse200 & {
    headers: Headers;
  };
export type getSupplierOrderItemsResponse =
  getSupplierOrderItemsResponseSuccess;

export const getGetSupplierOrderItemsUrl = (
  params?: GetSupplierOrderItemsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/supplier-order-items?${stringifiedParams}`
    : `/v1/supplier-order-items`;
};

export const getSupplierOrderItems = async (
  params?: GetSupplierOrderItemsParams,
  options?: RequestInit,
): Promise<getSupplierOrderItemsResponse> => {
  return customFetch<getSupplierOrderItemsResponse>(
    getGetSupplierOrderItemsUrl(params),
    {
      ...options,
      method: 'GET',
    },
  );
};

export type getSupplierOrderItemByIdResponse200 = {
  data: SupplierOrderItemDto;
  status: 200;
};

export type getSupplierOrderItemByIdResponse404 = {
  data: void;
  status: 404;
};

export type getSupplierOrderItemByIdResponseSuccess =
  getSupplierOrderItemByIdResponse200 & {
    headers: Headers;
  };
export type getSupplierOrderItemByIdResponseError =
  getSupplierOrderItemByIdResponse404 & {
    headers: Headers;
  };

export type getSupplierOrderItemByIdResponse =
  | getSupplierOrderItemByIdResponseSuccess
  | getSupplierOrderItemByIdResponseError;

export const getGetSupplierOrderItemByIdUrl = (id: string) => {
  return `/v1/supplier-order-items/${id}`;
};

export const getSupplierOrderItemById = async (
  id: string,
  options?: RequestInit,
): Promise<getSupplierOrderItemByIdResponse> => {
  return customFetch<getSupplierOrderItemByIdResponse>(
    getGetSupplierOrderItemByIdUrl(id),
    {
      ...options,
      method: 'GET',
    },
  );
};

export type updateSupplierOrderItemsInvoicingStatusResponse200 = {
  data: SupplierOrderItemDto[];
  status: 200;
};

export type updateSupplierOrderItemsInvoicingStatusResponse400 = {
  data: void;
  status: 400;
};

export type updateSupplierOrderItemsInvoicingStatusResponse404 = {
  data: void;
  status: 404;
};

export type updateSupplierOrderItemsInvoicingStatusResponseSuccess =
  updateSupplierOrderItemsInvoicingStatusResponse200 & {
    headers: Headers;
  };
export type updateSupplierOrderItemsInvoicingStatusResponseError = (
  | updateSupplierOrderItemsInvoicingStatusResponse400
  | updateSupplierOrderItemsInvoicingStatusResponse404
) & {
  headers: Headers;
};

export type updateSupplierOrderItemsInvoicingStatusResponse =
  | updateSupplierOrderItemsInvoicingStatusResponseSuccess
  | updateSupplierOrderItemsInvoicingStatusResponseError;

export const getUpdateSupplierOrderItemsInvoicingStatusUrl = () => {
  return `/v1/supplier-order-items/invoicing-status`;
};

export const updateSupplierOrderItemsInvoicingStatus = async (
  supplierOrderItemBatchUpdateInvoicingStatusDto: SupplierOrderItemBatchUpdateInvoicingStatusDto,
  options?: RequestInit,
): Promise<updateSupplierOrderItemsInvoicingStatusResponse> => {
  return customFetch<updateSupplierOrderItemsInvoicingStatusResponse>(
    getUpdateSupplierOrderItemsInvoicingStatusUrl(),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(supplierOrderItemBatchUpdateInvoicingStatusDto),
    },
  );
};

export type cancelSupplierOrderItemResponse200 = {
  data: SupplierOrderItemDto;
  status: 200;
};

export type cancelSupplierOrderItemResponse400 = {
  data: ErrorDto;
  status: 400;
};

export type cancelSupplierOrderItemResponse404 = {
  data: ErrorDto;
  status: 404;
};

export type cancelSupplierOrderItemResponseSuccess =
  cancelSupplierOrderItemResponse200 & {
    headers: Headers;
  };
export type cancelSupplierOrderItemResponseError = (
  | cancelSupplierOrderItemResponse400
  | cancelSupplierOrderItemResponse404
) & {
  headers: Headers;
};

export type cancelSupplierOrderItemResponse =
  | cancelSupplierOrderItemResponseSuccess
  | cancelSupplierOrderItemResponseError;

export const getCancelSupplierOrderItemUrl = (id: string) => {
  return `/v1/supplier-order-items/${id}/cancel`;
};

export const cancelSupplierOrderItem = async (
  id: string,
  options?: RequestInit,
): Promise<cancelSupplierOrderItemResponse> => {
  return customFetch<cancelSupplierOrderItemResponse>(
    getCancelSupplierOrderItemUrl(id),
    {
      ...options,
      method: 'PATCH',
    },
  );
};

export type importClientOrdersResponse201 = {
  data: void;
  status: 201;
};

export type importClientOrdersResponseSuccess =
  importClientOrdersResponse201 & {
    headers: Headers;
  };
export type importClientOrdersResponse = importClientOrdersResponseSuccess;

export const getImportClientOrdersUrl = (clientId: string) => {
  return `/v1/imports/client-order/${clientId}`;
};

export const importClientOrders = async (
  clientId: string,
  importClientOrdersBody: ImportClientOrdersBody,
  options?: RequestInit,
): Promise<importClientOrdersResponse> => {
  const formData = new FormData();
  if (importClientOrdersBody.file !== undefined) {
    formData.append(`file`, importClientOrdersBody.file);
  }

  return customFetch<importClientOrdersResponse>(
    getImportClientOrdersUrl(clientId),
    {
      ...options,
      method: 'POST',
      body: formData,
    },
  );
};

export type exportBillableSupplierOrderItemsResponse200 = {
  data: void;
  status: 200;
};

export type exportBillableSupplierOrderItemsResponse201 = {
  data: void;
  status: 201;
};

export type exportBillableSupplierOrderItemsResponseSuccess = (
  | exportBillableSupplierOrderItemsResponse200
  | exportBillableSupplierOrderItemsResponse201
) & {
  headers: Headers;
};
export type exportBillableSupplierOrderItemsResponse =
  exportBillableSupplierOrderItemsResponseSuccess;

export const getExportBillableSupplierOrderItemsUrl = () => {
  return `/v1/exports/supplier-order-items/billable`;
};

export const exportBillableSupplierOrderItems = async (
  options?: RequestInit,
): Promise<exportBillableSupplierOrderItemsResponse> => {
  return customFetch<exportBillableSupplierOrderItemsResponse>(
    getExportBillableSupplierOrderItemsUrl(),
    {
      ...options,
      method: 'POST',
    },
  );
};

export type getInvoicePreferencesByAccountNumberResponse200 = {
  data: InvoicePreferencesDto;
  status: 200;
};

export type getInvoicePreferencesByAccountNumberResponseSuccess =
  getInvoicePreferencesByAccountNumberResponse200 & {
    headers: Headers;
  };
export type getInvoicePreferencesByAccountNumberResponse =
  getInvoicePreferencesByAccountNumberResponseSuccess;

export const getGetInvoicePreferencesByAccountNumberUrl = (
  accountNumber: string,
) => {
  return `/v1/invoice-preferences/${accountNumber}`;
};

export const getInvoicePreferencesByAccountNumber = async (
  accountNumber: string,
  options?: RequestInit,
): Promise<getInvoicePreferencesByAccountNumberResponse> => {
  return customFetch<getInvoicePreferencesByAccountNumberResponse>(
    getGetInvoicePreferencesByAccountNumberUrl(accountNumber),
    {
      ...options,
      method: 'GET',
    },
  );
};

export type createInvoicePreferencesResponse201 = {
  data: InvoicePreferencesDto;
  status: 201;
};

export type createInvoicePreferencesResponseSuccess =
  createInvoicePreferencesResponse201 & {
    headers: Headers;
  };
export type createInvoicePreferencesResponse =
  createInvoicePreferencesResponseSuccess;

export const getCreateInvoicePreferencesUrl = () => {
  return `/v1/invoice-preferences`;
};

export const createInvoicePreferences = async (
  invoicePreferencesCreateDto: InvoicePreferencesCreateDto,
  options?: RequestInit,
): Promise<createInvoicePreferencesResponse> => {
  return customFetch<createInvoicePreferencesResponse>(
    getCreateInvoicePreferencesUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(invoicePreferencesCreateDto),
    },
  );
};

export type updateInvoicePreferencesResponse200 = {
  data: InvoicePreferencesDto;
  status: 200;
};

export type updateInvoicePreferencesResponseSuccess =
  updateInvoicePreferencesResponse200 & {
    headers: Headers;
  };
export type updateInvoicePreferencesResponse =
  updateInvoicePreferencesResponseSuccess;

export const getUpdateInvoicePreferencesUrl = (invoicePreferenceId: string) => {
  return `/v1/invoice-preferences/${invoicePreferenceId}`;
};

export const updateInvoicePreferences = async (
  invoicePreferenceId: string,
  invoicePreferencesUpdateDto: InvoicePreferencesUpdateDto,
  options?: RequestInit,
): Promise<updateInvoicePreferencesResponse> => {
  return customFetch<updateInvoicePreferencesResponse>(
    getUpdateInvoicePreferencesUrl(invoicePreferenceId),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(invoicePreferencesUpdateDto),
    },
  );
};

export type refreshInvoicePreferencesByAccountNumberResponse201 = {
  data: void;
  status: 201;
};

export type refreshInvoicePreferencesByAccountNumberResponseSuccess =
  refreshInvoicePreferencesByAccountNumberResponse201 & {
    headers: Headers;
  };
export type refreshInvoicePreferencesByAccountNumberResponse =
  refreshInvoicePreferencesByAccountNumberResponseSuccess;

export const getRefreshInvoicePreferencesByAccountNumberUrl = (
  accountNumber: string,
) => {
  return `/v1/invoice-preferences/${accountNumber}/refresh`;
};

export const refreshInvoicePreferencesByAccountNumber = async (
  accountNumber: string,
  options?: RequestInit,
): Promise<refreshInvoicePreferencesByAccountNumberResponse> => {
  return customFetch<refreshInvoicePreferencesByAccountNumberResponse>(
    getRefreshInvoicePreferencesByAccountNumberUrl(accountNumber),
    {
      ...options,
      method: 'POST',
    },
  );
};

export type getProjectsResponse200 = {
  data: GetProjects200;
  status: 200;
};

export type getProjectsResponseSuccess = getProjectsResponse200 & {
  headers: Headers;
};
export type getProjectsResponse = getProjectsResponseSuccess;

export const getGetProjectsUrl = (params?: GetProjectsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/projects?${stringifiedParams}`
    : `/v1/projects`;
};

export const getProjects = async (
  params?: GetProjectsParams,
  options?: RequestInit,
): Promise<getProjectsResponse> => {
  return customFetch<getProjectsResponse>(getGetProjectsUrl(params), {
    ...options,
    method: 'GET',
  });
};

export type getProjectByIdResponse200 = {
  data: ProjectDto;
  status: 200;
};

export type getProjectByIdResponseSuccess = getProjectByIdResponse200 & {
  headers: Headers;
};
export type getProjectByIdResponse = getProjectByIdResponseSuccess;

export const getGetProjectByIdUrl = (projectId: string) => {
  return `/v1/projects/${projectId}`;
};

export const getProjectById = async (
  projectId: string,
  options?: RequestInit,
): Promise<getProjectByIdResponse> => {
  return customFetch<getProjectByIdResponse>(getGetProjectByIdUrl(projectId), {
    ...options,
    method: 'GET',
  });
};
