/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';

import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';

import {
  getClientsHandler,
  createClientHandler,
  getClientByAccountNumberHandler,
  getClientByIdHandler,
  updateClientHandler,
  getAllClientDeliverableParametersHandler,
  createClientDeliverableParametersHandler,
  getClientDeliverableParametersByIdHandler,
  updateClientDeliverableParametersHandler,
  getGroupsHandler,
  createGroupHandler,
  getGroupByAccountNumberHandler,
  getGroupByIdHandler,
  updateGroupHandler,
  getSuppliersHandler,
  createSupplierHandler,
  getSupplierByAccountNumberHandler,
  getSupplierByIdHandler,
  updateSupplierHandler,
  getUsersHandler,
  createUserHandler,
  getUserByIdHandler,
  updateUserHandler,
  assignUserToAccountHandler,
  unassignUserFromAccountHandler,
  getAssetByIdHandler,
  updateAssetHandler,
  getAssetsHandler,
  createAssetHandler,
  getArticlesHandler,
  createArticleHandler,
  getArticleByIdHandler,
  updateArticleHandler,
  assignArticleToBillableAccountHandler,
  validateArticleConfigurationHandler,
  getRateFromSkuAndAccountHandler,
  getDeliverablesHandler,
  getDeliverableByIdHandler,
  publishDeliverableHandler,
  rejectDeliverableHandler,
  importDeliverableHandler,
  getRoomplansHandler,
  uploadRoomplansHandler,
  cancelDeliverableHandler,
  relaunchDeliverableHandler,
  forceProcessedStatusHandler,
  getVirtualTourHandler,
  editVirtualTourHandler,
  removeWindowsHandler,
  resetVirtualTourHandler,
  maskWindowsHandler,
  validateDeliverableHandler,
  getFlowHandler,
  getFlowByClientOrderItemIdHandler,
  getSubmittedFormsHandler,
  updateSubmittedFormsHandler,
  getExportedFlowHandler,
  updateExportedFlowHandler,
  getOrderResultHandler,
  updateOrderResultHandler,
  healthCheckHandler,
  getClientOrderItemsHandler,
  createClientOrderItemHandler,
  getClientOrderItemByIdHandler,
  updateClientOrderItemByIdHandler,
  updateClientOrderItemsInvoicingStatusHandler,
  getResourceUrlHandler,
  uploadResourceHandler,
  rateForClientOrderItemHandler,
  cancelClientOrderItemHandler,
  getSupplierOrdersBySupplierIdHandler,
  getSupplierOrderByIdHandler,
  updateSupplierOrderByIdHandler,
  getAllSupplierOrdersHandler,
  createSupplierOrderHandler,
  cancelSupplierOrderByIdHandler,
  acceptSupplierOrderByIdHandler,
  refuseSupplierOrderByIdHandler,
  amendSupplierOrderHandler,
  reproposeSupplierOrderHandler,
  getAllClientOrdersByOrderIdHandler,
  getClientOrderByIdHandler,
  getAllClientOrdersHandler,
  createClientOrderHandler,
  getSupplierOrderItemsHandler,
  getSupplierOrderItemByIdHandler,
  updateSupplierOrderItemsInvoicingStatusHandler,
  cancelSupplierOrderItemHandler,
  importClientOrdersHandler,
  exportBillableSupplierOrderItemsHandler,
  getInvoicePreferencesByAccountNumberHandler,
  createInvoicePreferencesHandler,
  updateInvoicePreferencesHandler,
  refreshInvoicePreferencesByAccountNumberHandler,
  getProjectsHandler,
  getProjectByIdHandler,
} from './handlers';
import {
  getClientsQueryParams,
  createClientBody,
  getClientByAccountNumberParams,
  getClientByIdParams,
  updateClientParams,
  updateClientBody,
  getAllClientDeliverableParametersParams,
  getAllClientDeliverableParametersQueryParams,
  createClientDeliverableParametersParams,
  createClientDeliverableParametersBody,
  getClientDeliverableParametersByIdParams,
  updateClientDeliverableParametersParams,
  updateClientDeliverableParametersBody,
  getGroupsQueryParams,
  createGroupBody,
  getGroupByAccountNumberParams,
  getGroupByIdParams,
  updateGroupParams,
  updateGroupBody,
  getSuppliersQueryParams,
  createSupplierBody,
  getSupplierByAccountNumberParams,
  getSupplierByIdParams,
  updateSupplierParams,
  updateSupplierBody,
  getUsersQueryParams,
  createUserBody,
  getUserByIdParams,
  updateUserParams,
  updateUserBody,
  assignUserToAccountParams,
  unassignUserFromAccountParams,
  getAssetByIdParams,
  updateAssetParams,
  updateAssetBody,
  getAssetsQueryParams,
  createAssetBody,
  getArticlesQueryParams,
  createArticleBody,
  getArticleByIdParams,
  updateArticleParams,
  updateArticleBody,
  assignArticleToBillableAccountParams,
  validateArticleConfigurationBody,
  getDeliverablesQueryParams,
  getDeliverableByIdParams,
  publishDeliverableParams,
  rejectDeliverableParams,
  rejectDeliverableBody,
  importDeliverableParams,
  importDeliverableBody,
  getRoomplansParams,
  uploadRoomplansParams,
  uploadRoomplansBody,
  cancelDeliverableParams,
  relaunchDeliverableParams,
  forceProcessedStatusParams,
  getVirtualTourParams,
  editVirtualTourParams,
  editVirtualTourBody,
  removeWindowsParams,
  removeWindowsBody,
  resetVirtualTourParams,
  maskWindowsParams,
  validateDeliverableParams,
  getFlowParams,
  getFlowByClientOrderItemIdParams,
  getSubmittedFormsParams,
  updateSubmittedFormsParams,
  updateSubmittedFormsBody,
  getExportedFlowParams,
  updateExportedFlowParams,
  updateExportedFlowQueryParams,
  updateExportedFlowBody,
  getOrderResultParams,
  updateOrderResultParams,
  updateOrderResultBody,
  getClientOrderItemsQueryParams,
  createClientOrderItemBody,
  getClientOrderItemByIdParams,
  updateClientOrderItemByIdParams,
  updateClientOrderItemByIdBody,
  updateClientOrderItemsInvoicingStatusBody,
  getResourceUrlParams,
  getResourceUrlQueryParams,
  uploadResourceParams,
  uploadResourceQueryParams,
  uploadResourceBody,
  rateForClientOrderItemBody,
  cancelClientOrderItemParams,
  getSupplierOrdersBySupplierIdParams,
  getSupplierOrdersBySupplierIdQueryParams,
  getSupplierOrderByIdParams,
  updateSupplierOrderByIdParams,
  updateSupplierOrderByIdBody,
  getAllSupplierOrdersQueryParams,
  createSupplierOrderBody,
  cancelSupplierOrderByIdParams,
  acceptSupplierOrderByIdParams,
  refuseSupplierOrderByIdParams,
  amendSupplierOrderParams,
  amendSupplierOrderBody,
  reproposeSupplierOrderParams,
  reproposeSupplierOrderBody,
  getAllClientOrdersByOrderIdParams,
  getAllClientOrdersByOrderIdQueryParams,
  getClientOrderByIdParams,
  getAllClientOrdersQueryParams,
  createClientOrderBody,
  getSupplierOrderItemsQueryParams,
  getSupplierOrderItemByIdParams,
  updateSupplierOrderItemsInvoicingStatusBody,
  cancelSupplierOrderItemParams,
  importClientOrdersParams,
  importClientOrdersBody,
  getInvoicePreferencesByAccountNumberParams,
  createInvoicePreferencesBody,
  updateInvoicePreferencesParams,
  updateInvoicePreferencesBody,
  refreshInvoicePreferencesByAccountNumberParams,
  getProjectsQueryParams,
  getProjectByIdParams,
} from './tool-schemas.zod';

const server = new McpServer({
  name: 'magmaAPIServer',
  version: '1.0.0',
});

server.tool(
  'getClients',
  'Get all clients',
  {
    queryParams: getClientsQueryParams,
  },
  getClientsHandler,
);

server.tool(
  'createClient',
  'Create client',
  {
    bodyParams: createClientBody,
  },
  createClientHandler,
);

server.tool(
  'getClientByAccountNumber',
  'Get client by account number',
  {
    pathParams: getClientByAccountNumberParams,
  },
  getClientByAccountNumberHandler,
);

server.tool(
  'getClientById',
  'Get client by Id',
  {
    pathParams: getClientByIdParams,
  },
  getClientByIdHandler,
);

server.tool(
  'updateClient',
  'Update client',
  {
    pathParams: updateClientParams,
    bodyParams: updateClientBody,
  },
  updateClientHandler,
);

server.tool(
  'getAllClientDeliverableParameters',
  'Get all client deliverable parameters',
  {
    pathParams: getAllClientDeliverableParametersParams,
    queryParams: getAllClientDeliverableParametersQueryParams,
  },
  getAllClientDeliverableParametersHandler,
);

server.tool(
  'createClientDeliverableParameters',
  'Create client deliverable parameters',
  {
    pathParams: createClientDeliverableParametersParams,
    bodyParams: createClientDeliverableParametersBody,
  },
  createClientDeliverableParametersHandler,
);

server.tool(
  'getClientDeliverableParametersById',
  'Get client deliverable parameters by Id',
  {
    pathParams: getClientDeliverableParametersByIdParams,
  },
  getClientDeliverableParametersByIdHandler,
);

server.tool(
  'updateClientDeliverableParameters',
  'Update client deliverable parameters',
  {
    pathParams: updateClientDeliverableParametersParams,
    bodyParams: updateClientDeliverableParametersBody,
  },
  updateClientDeliverableParametersHandler,
);

server.tool(
  'getGroups',
  'Get all groups',
  {
    queryParams: getGroupsQueryParams,
  },
  getGroupsHandler,
);

server.tool(
  'createGroup',
  'Create group',
  {
    bodyParams: createGroupBody,
  },
  createGroupHandler,
);

server.tool(
  'getGroupByAccountNumber',
  'Get group by account number',
  {
    pathParams: getGroupByAccountNumberParams,
  },
  getGroupByAccountNumberHandler,
);

server.tool(
  'getGroupById',
  'Get group by Id',
  {
    pathParams: getGroupByIdParams,
  },
  getGroupByIdHandler,
);

server.tool(
  'updateGroup',
  'Update group',
  {
    pathParams: updateGroupParams,
    bodyParams: updateGroupBody,
  },
  updateGroupHandler,
);

server.tool(
  'getSuppliers',
  'Get all suppliers',
  {
    queryParams: getSuppliersQueryParams,
  },
  getSuppliersHandler,
);

server.tool(
  'createSupplier',
  'Create supplier',
  {
    bodyParams: createSupplierBody,
  },
  createSupplierHandler,
);

server.tool(
  'getSupplierByAccountNumber',
  'Get supplier by account number',
  {
    pathParams: getSupplierByAccountNumberParams,
  },
  getSupplierByAccountNumberHandler,
);

server.tool(
  'getSupplierById',
  'Get client by Id',
  {
    pathParams: getSupplierByIdParams,
  },
  getSupplierByIdHandler,
);

server.tool(
  'updateSupplier',
  'Update supplier',
  {
    pathParams: updateSupplierParams,
    bodyParams: updateSupplierBody,
  },
  updateSupplierHandler,
);

server.tool(
  'getUsers',
  'Get all users',
  {
    queryParams: getUsersQueryParams,
  },
  getUsersHandler,
);

server.tool(
  'createUser',
  'Create a new user',
  {
    bodyParams: createUserBody,
  },
  createUserHandler,
);

server.tool(
  'getUserById',
  'Get user by Id',
  {
    pathParams: getUserByIdParams,
  },
  getUserByIdHandler,
);

server.tool(
  'updateUser',
  'Update an existing user',
  {
    pathParams: updateUserParams,
    bodyParams: updateUserBody,
  },
  updateUserHandler,
);

server.tool(
  'assignUserToAccount',
  'Assign an user to account',
  {
    pathParams: assignUserToAccountParams,
  },
  assignUserToAccountHandler,
);

server.tool(
  'unassignUserFromAccount',
  'Unassign an user from account',
  {
    pathParams: unassignUserFromAccountParams,
  },
  unassignUserFromAccountHandler,
);

server.tool(
  'getAssetById',
  'Get an asset by id',
  {
    pathParams: getAssetByIdParams,
  },
  getAssetByIdHandler,
);

server.tool(
  'updateAsset',
  'Update an asset',
  {
    pathParams: updateAssetParams,
    bodyParams: updateAssetBody,
  },
  updateAssetHandler,
);

server.tool(
  'getAssets',
  'Get all assets',
  {
    queryParams: getAssetsQueryParams,
  },
  getAssetsHandler,
);

server.tool(
  'createAsset',
  'Create a new Asset',
  {
    bodyParams: createAssetBody,
  },
  createAssetHandler,
);

server.tool(
  'getArticles',
  'Get all articles',
  {
    queryParams: getArticlesQueryParams,
  },
  getArticlesHandler,
);

server.tool(
  'createArticle',
  'Create a new article',
  {
    bodyParams: createArticleBody,
  },
  createArticleHandler,
);

server.tool(
  'getArticleById',
  'Get article by ID',
  {
    pathParams: getArticleByIdParams,
  },
  getArticleByIdHandler,
);

server.tool(
  'updateArticle',
  'Update an article',
  {
    pathParams: updateArticleParams,
    bodyParams: updateArticleBody,
  },
  updateArticleHandler,
);

server.tool(
  'assignArticleToBillableAccount',
  'Assign an article to billable account',
  {
    pathParams: assignArticleToBillableAccountParams,
  },
  assignArticleToBillableAccountHandler,
);

server.tool(
  'validateArticleConfiguration',
  'Validate an article configuration',
  {
    bodyParams: validateArticleConfigurationBody,
  },
  validateArticleConfigurationHandler,
);

server.tool(
  'getRateFromSkuAndAccount',
  'Get ZohoItem given a SKU and an account',
  {},
  getRateFromSkuAndAccountHandler,
);

server.tool(
  'getDeliverables',
  'Get all deliverables',
  {
    queryParams: getDeliverablesQueryParams,
  },
  getDeliverablesHandler,
);

server.tool(
  'getDeliverableById',
  'Get deliverable by Id',
  {
    pathParams: getDeliverableByIdParams,
  },
  getDeliverableByIdHandler,
);

server.tool(
  'publishDeliverable',
  'Set Deliverable status to validated and trigger publication',
  {
    pathParams: publishDeliverableParams,
  },
  publishDeliverableHandler,
);

server.tool(
  'rejectDeliverable',
  'Reject the deliverable in QA',
  {
    pathParams: rejectDeliverableParams,
    bodyParams: rejectDeliverableBody,
  },
  rejectDeliverableHandler,
);

server.tool(
  'importDeliverable',
  'Import a new deliverable',
  {
    pathParams: importDeliverableParams,
    bodyParams: importDeliverableBody,
  },
  importDeliverableHandler,
);

server.tool(
  'getRoomplans',
  'Get the current roomplans for a deliverable',
  {
    pathParams: getRoomplansParams,
  },
  getRoomplansHandler,
);

server.tool(
  'uploadRoomplans',
  'Upload a new roomplans for a deliverable',
  {
    pathParams: uploadRoomplansParams,
    bodyParams: uploadRoomplansBody,
  },
  uploadRoomplansHandler,
);

server.tool(
  'cancelDeliverable',
  'Cancel a deliverable',
  {
    pathParams: cancelDeliverableParams,
  },
  cancelDeliverableHandler,
);

server.tool(
  'relaunchDeliverable',
  'Relaunch a deliverable',
  {
    pathParams: relaunchDeliverableParams,
  },
  relaunchDeliverableHandler,
);

server.tool(
  'forceProcessedStatus',
  'Force a deliverable to processed status',
  {
    pathParams: forceProcessedStatusParams,
  },
  forceProcessedStatusHandler,
);

server.tool(
  'getVirtualTour',
  'Get the virtual tour',
  {
    pathParams: getVirtualTourParams,
  },
  getVirtualTourHandler,
);

server.tool(
  'editVirtualTour',
  'Edit the virtual tour',
  {
    pathParams: editVirtualTourParams,
    bodyParams: editVirtualTourBody,
  },
  editVirtualTourHandler,
);

server.tool(
  'removeWindows',
  'Remove windows from the virtual tour',
  {
    pathParams: removeWindowsParams,
    bodyParams: removeWindowsBody,
  },
  removeWindowsHandler,
);

server.tool(
  'resetVirtualTour',
  'Reset the virtual tour (remove all edits)',
  {
    pathParams: resetVirtualTourParams,
  },
  resetVirtualTourHandler,
);

server.tool(
  'maskWindows',
  'Mask windows in the virtual tour',
  {
    pathParams: maskWindowsParams,
  },
  maskWindowsHandler,
);

server.tool(
  'validateDeliverable',
  'Validate a deliverable',
  {
    pathParams: validateDeliverableParams,
  },
  validateDeliverableHandler,
);

server.tool(
  'getFlow',
  'Get a flow by id',
  {
    pathParams: getFlowParams,
  },
  getFlowHandler,
);

server.tool(
  'getFlowByClientOrderItemId',
  'Get a flow by client order item id',
  {
    pathParams: getFlowByClientOrderItemIdParams,
  },
  getFlowByClientOrderItemIdHandler,
);

server.tool(
  'getSubmittedForms',
  'Get submitted forms by client order item id',
  {
    pathParams: getSubmittedFormsParams,
  },
  getSubmittedFormsHandler,
);

server.tool(
  'updateSubmittedForms',
  'Create a new submitted form',
  {
    pathParams: updateSubmittedFormsParams,
    bodyParams: updateSubmittedFormsBody,
  },
  updateSubmittedFormsHandler,
);

server.tool(
  'getExportedFlow',
  'Get exported flow json by client order item id',
  {
    pathParams: getExportedFlowParams,
  },
  getExportedFlowHandler,
);

server.tool(
  'updateExportedFlow',
  'Update exported flow json by client order item id',
  {
    pathParams: updateExportedFlowParams,
    queryParams: updateExportedFlowQueryParams,
    bodyParams: updateExportedFlowBody,
  },
  updateExportedFlowHandler,
);

server.tool(
  'getOrderResult',
  'Get order result json by client order item id',
  {
    pathParams: getOrderResultParams,
  },
  getOrderResultHandler,
);

server.tool(
  'updateOrderResult',
  'Update order result json by client order item id',
  {
    pathParams: updateOrderResultParams,
    bodyParams: updateOrderResultBody,
  },
  updateOrderResultHandler,
);

server.tool('healthCheck', 'Health check', {}, healthCheckHandler);

server.tool(
  'getClientOrderItems',
  'Get all client order items',
  {
    queryParams: getClientOrderItemsQueryParams,
  },
  getClientOrderItemsHandler,
);

server.tool(
  'createClientOrderItem',
  'Create a client order item',
  {
    bodyParams: createClientOrderItemBody,
  },
  createClientOrderItemHandler,
);

server.tool(
  'getClientOrderItemById',
  'Get a client order item by Id',
  {
    pathParams: getClientOrderItemByIdParams,
  },
  getClientOrderItemByIdHandler,
);

server.tool(
  'updateClientOrderItemById',
  'Update a client order item by Id',
  {
    pathParams: updateClientOrderItemByIdParams,
    bodyParams: updateClientOrderItemByIdBody,
  },
  updateClientOrderItemByIdHandler,
);

server.tool(
  'updateClientOrderItemsInvoicingStatus',
  'Update invoicing status of client order items',
  {
    bodyParams: updateClientOrderItemsInvoicingStatusBody,
  },
  updateClientOrderItemsInvoicingStatusHandler,
);

server.tool(
  'getResourceUrl',
  'Get a resource by client order item id',
  {
    pathParams: getResourceUrlParams,
    queryParams: getResourceUrlQueryParams,
  },
  getResourceUrlHandler,
);

server.tool(
  'uploadResource',
  'Upload a resource by client order item id',
  {
    pathParams: uploadResourceParams,
    queryParams: uploadResourceQueryParams,
    bodyParams: uploadResourceBody,
  },
  uploadResourceHandler,
);

server.tool(
  'rateForClientOrderItem',
  'Get rate for a client order item',
  {
    bodyParams: rateForClientOrderItemBody,
  },
  rateForClientOrderItemHandler,
);

server.tool(
  'cancelClientOrderItem',
  'Client order item canceled',
  {
    pathParams: cancelClientOrderItemParams,
  },
  cancelClientOrderItemHandler,
);

server.tool(
  'getSupplierOrdersBySupplierId',
  'Get all supplier orders by Supplier Id',
  {
    pathParams: getSupplierOrdersBySupplierIdParams,
    queryParams: getSupplierOrdersBySupplierIdQueryParams,
  },
  getSupplierOrdersBySupplierIdHandler,
);

server.tool(
  'getSupplierOrderById',
  'Get a supplier order by Id',
  {
    pathParams: getSupplierOrderByIdParams,
  },
  getSupplierOrderByIdHandler,
);

server.tool(
  'updateSupplierOrderById',
  'Update a supplier order by Id',
  {
    pathParams: updateSupplierOrderByIdParams,
    bodyParams: updateSupplierOrderByIdBody,
  },
  updateSupplierOrderByIdHandler,
);

server.tool(
  'getAllSupplierOrders',
  'Get all supplier orders',
  {
    queryParams: getAllSupplierOrdersQueryParams,
  },
  getAllSupplierOrdersHandler,
);

server.tool(
  'createSupplierOrder',
  'Create a new supplier order',
  {
    bodyParams: createSupplierOrderBody,
  },
  createSupplierOrderHandler,
);

server.tool(
  'cancelSupplierOrderById',
  'Cancel a supplier order by Id',
  {
    pathParams: cancelSupplierOrderByIdParams,
  },
  cancelSupplierOrderByIdHandler,
);

server.tool(
  'acceptSupplierOrderById',
  'Accept a supplier order by Id',
  {
    pathParams: acceptSupplierOrderByIdParams,
  },
  acceptSupplierOrderByIdHandler,
);

server.tool(
  'refuseSupplierOrderById',
  'Accept a supplier order by Id',
  {
    pathParams: refuseSupplierOrderByIdParams,
  },
  refuseSupplierOrderByIdHandler,
);

server.tool(
  'amendSupplierOrder',
  'Amend Supplier order',
  {
    pathParams: amendSupplierOrderParams,
    bodyParams: amendSupplierOrderBody,
  },
  amendSupplierOrderHandler,
);

server.tool(
  'reproposeSupplierOrder',
  'Create a new supplier order with new conditions. Cancels the previous one.',
  {
    pathParams: reproposeSupplierOrderParams,
    bodyParams: reproposeSupplierOrderBody,
  },
  reproposeSupplierOrderHandler,
);

server.tool(
  'getAllClientOrdersByOrderId',
  'Get all client orders by Client Id',
  {
    pathParams: getAllClientOrdersByOrderIdParams,
    queryParams: getAllClientOrdersByOrderIdQueryParams,
  },
  getAllClientOrdersByOrderIdHandler,
);

server.tool(
  'getClientOrderById',
  'Get a client order by Id',
  {
    pathParams: getClientOrderByIdParams,
  },
  getClientOrderByIdHandler,
);

server.tool(
  'getAllClientOrders',
  'Get all client orders',
  {
    queryParams: getAllClientOrdersQueryParams,
  },
  getAllClientOrdersHandler,
);

server.tool(
  'createClientOrder',
  'Create a new client order',
  {
    bodyParams: createClientOrderBody,
  },
  createClientOrderHandler,
);

server.tool(
  'getSupplierOrderItems',
  'Get all supplier order items',
  {
    queryParams: getSupplierOrderItemsQueryParams,
  },
  getSupplierOrderItemsHandler,
);

server.tool(
  'getSupplierOrderItemById',
  'Get a supplier order item by Id',
  {
    pathParams: getSupplierOrderItemByIdParams,
  },
  getSupplierOrderItemByIdHandler,
);

server.tool(
  'updateSupplierOrderItemsInvoicingStatus',
  'Update invoicing status of supplier order items',
  {
    bodyParams: updateSupplierOrderItemsInvoicingStatusBody,
  },
  updateSupplierOrderItemsInvoicingStatusHandler,
);

server.tool(
  'cancelSupplierOrderItem',
  'Supplier order item canceled',
  {
    pathParams: cancelSupplierOrderItemParams,
  },
  cancelSupplierOrderItemHandler,
);

server.tool(
  'importClientOrders',
  'Import new client orders',
  {
    pathParams: importClientOrdersParams,
    bodyParams: importClientOrdersBody,
  },
  importClientOrdersHandler,
);

server.tool(
  'exportBillableSupplierOrderItems',
  'Export billable supplier order items',
  {},
  exportBillableSupplierOrderItemsHandler,
);

server.tool(
  'getInvoicePreferencesByAccountNumber',
  'Get invoice preferences by account number',
  {
    pathParams: getInvoicePreferencesByAccountNumberParams,
  },
  getInvoicePreferencesByAccountNumberHandler,
);

server.tool(
  'createInvoicePreferences',
  'Create invoice preferences',
  {
    bodyParams: createInvoicePreferencesBody,
  },
  createInvoicePreferencesHandler,
);

server.tool(
  'updateInvoicePreferences',
  'Update invoice preferences',
  {
    pathParams: updateInvoicePreferencesParams,
    bodyParams: updateInvoicePreferencesBody,
  },
  updateInvoicePreferencesHandler,
);

server.tool(
  'refreshInvoicePreferencesByAccountNumber',
  'Refresh invoice preferences by account number',
  {
    pathParams: refreshInvoicePreferencesByAccountNumberParams,
  },
  refreshInvoicePreferencesByAccountNumberHandler,
);

server.tool(
  'getProjects',
  'Get all projects',
  {
    queryParams: getProjectsQueryParams,
  },
  getProjectsHandler,
);

server.tool(
  'getProjectById',
  'Get project by Id',
  {
    pathParams: getProjectByIdParams,
  },
  getProjectByIdHandler,
);
export default server;
