/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { LegalStatus } from './legalStatus';
import type { AddressDto } from './addressDto';
import type { AccountPreferenceDto } from './accountPreferenceDto';

export interface AccountDto {
  id: string;
  accountNumber: string;
  name: string;
  description?: string;
  legalStatus?: LegalStatus;
  companyNumber?: string;
  vatNumber?: string;
  address: AddressDto;
  accountPreference: AccountPreferenceDto;
  contactEmail?: string;
  createdAt: string;
  updatedAt: string;
}
