/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { LegalStatus } from './legalStatus';
import type { UpdateAddressDto } from './updateAddressDto';
import type { UpdateAccountPreferenceDto } from './updateAccountPreferenceDto';

export interface AccountUpdateDto {
  accountNumber: string;
  /** @minLength 2 */
  name: string;
  description?: string;
  legalStatus?: LegalStatus;
  companyNumber?: string;
  vatNumber?: string;
  address: UpdateAddressDto;
  accountPreference: UpdateAccountPreferenceDto;
  contactEmail?: string;
  id: string;
  users?: string[];
}
