/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */

export interface AddressDto {
  id: string;
  name: string;
  address1: string;
  address2?: string;
  city: string;
  postCode: string;
  country: string;
  phone?: string;
  unitNumber?: string;
  floor?: number;
}
