/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { ArticleStatus } from './articleStatus';
import type { ArticleType } from './articleType';
import type { FlowDto } from './flowDto';
import type { PipelineDto } from './pipelineDto';
import type { OrderingConfigDto } from './orderingConfigDto';
import type { DeliverableType } from './deliverableType';
import type { PricingInformationDto } from './pricingInformationDto';

export interface ArticleDto {
  id: string;
  /** The name of the article */
  name: string;
  /** The description of the article */
  description?: string;
  /** The status of the article */
  status: ArticleStatus;
  type: ArticleType;
  /** Associated Acquisition Flow */
  flow: FlowDto;
  /** Associated processing pipeline */
  pipeline?: PipelineDto;
  /** Associated order configuration */
  orderingConfig: OrderingConfigDto;
  requiredDeliverableTypes?: DeliverableType[];
  pricingInformations?: PricingInformationDto;
}
