/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { ContactDto } from './contactDto';
import type { AddressDto } from './addressDto';

export interface AssetAccessDto {
  id: string;
  contact?: ContactDto;
  address?: AddressDto;
  remote: boolean;
  description?: string;
}
