/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { AssetType } from './assetType';

export interface AssetTagDto {
  id: string;
  name: string;
  slug: string;
  type: AssetType;
}
