/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { CapturePanoramaV2ComponentDtoType } from './capturePanoramaV2ComponentDtoType';
import type { TutorialDto } from './tutorialDto';
import type { CapturePanoramaV2ComponentDtoMultibracket } from './capturePanoramaV2ComponentDtoMultibracket';

export interface CapturePanoramaV2ComponentDto {
  position: number;
  navigation?: string;
  type: CapturePanoramaV2ComponentDtoType;
  tutorial: TutorialDto;
  multibracket?: CapturePanoramaV2ComponentDtoMultibracket;
}
