/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { CaptureType } from './captureType';
import type { CaptureConfigDto } from './captureConfigDto';

export interface CaptureDto {
  /** @minLength 2 */
  name: string;
  type: CaptureType;
  config: CaptureConfigDto;
}
