/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { OrderCriteria } from './orderCriteria';

export interface ClientOrderItemCriterionDto {
  /** The key can be either an AssetCriteria or OrderCriteria */
  key: OrderCriteria;
  value?: string;
}
