/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { AddressDto } from './addressDto';
import type { GroupDto } from './groupDto';
import type { AccountDto } from './accountDto';

export interface ClientDto {
  id: string;
  billingAddress?: AddressDto;
  group?: GroupDto;
  account: AccountDto;
}
