/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { ClientDto } from './clientDto';
import type { ClientOrderItemListDto } from './clientOrderItemListDto';
import type { ClientOrderStatus } from './clientOrderStatus';

export interface ClientOrderDto {
  id: string;
  orderNumber: string;
  client: ClientDto;
  items: ClientOrderItemListDto[];
  orderDate: string;
  status: ClientOrderStatus;
  totalAmount: number;
}
