/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { OrderResultJsonDto } from './orderResultJsonDto';

export interface ClientOrderItemCreateDto {
  id?: string;
  article: string;
  reference: string;
  dueDate?: string;
  price: number;
  vat: number;
  orderResult: OrderResultJsonDto;
  clientOrder: string;
}
