/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { ClientOrderStatus } from './clientOrderStatus';

export interface ClientOrderListDto {
  id: string;
  orderNumber: string;
  /** Client name */
  clientName: string;
  clientId: string;
  createdAt: string;
  articlesNames: string[];
  status: ClientOrderStatus;
  expectedDeliverableQuantity: number;
}
