/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { OrderingConfigJsonDto } from './orderingConfigJsonDto';

export interface CreateOrderingConfigDto {
  /**
   * The name of the order configuration
   * @minLength 2
   */
  name: string;
  /**
   * The description of the order configuration
   * @minLength 2
   */
  description?: string;
  json: OrderingConfigJsonDto;
}
