/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { DeliverableProvider } from './deliverableProvider';
import type { DeliverableType } from './deliverableType';
import type { DeliverableStatus } from './deliverableStatus';
import type { ClientDeliverableAction } from './clientDeliverableAction';

export interface DeliverableDto {
  id: string;
  path: string;
  provider: DeliverableProvider;
  type: DeliverableType;
  status: DeliverableStatus;
  supplierOrderItem?: string;
  clientOrderItem: string;
  postProcessingActions?: ClientDeliverableAction[];
  createdAt: string;
}
