/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */

export type DeliverableVisibilityDtoType =
  (typeof DeliverableVisibilityDtoType)[keyof typeof DeliverableVisibilityDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeliverableVisibilityDtoType = {
  indoor: 'indoor',
  outdoor: 'outdoor',
  room: 'room',
  direct: 'direct',
} as const;
