/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */

export type DeliverableCubemapDtoType =
  (typeof DeliverableCubemapDtoType)[keyof typeof DeliverableCubemapDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeliverableCubemapDtoType = {
  img_high_res: 'img_high_res',
  img_low_res: 'img_low_res',
  depth_map: 'depth_map',
  normal_map: 'normal_map',
} as const;
