/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */

export type Device = (typeof Device)[keyof typeof Device];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Device = {
  ANDROID: 'ANDROID',
  IOS: 'IOS',
} as const;
