/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { ExportedCapturePanoramaV2Dto } from './exportedCapturePanoramaV2Dto';
import type { ExportedCapturePanoramaDto } from './exportedCapturePanoramaDto';
import type { ExportedCaptureDto } from './exportedCaptureDto';
import type { ExportedExtractRoomplanDto } from './exportedExtractRoomplanDto';
import type { ExportedFormComponentDto } from './exportedFormComponentDto';
import type { ExportedListDto } from './exportedListDto';
import type { ExportedReportDto } from './exportedReportDto';
import type { ExportedAnnotationPanoramaDto } from './exportedAnnotationPanoramaDto';
import type { ExportedSwitchDto } from './exportedSwitchDto';

export type ExportedComponentsDtoItem =
  | ExportedCapturePanoramaV2Dto
  | ExportedCapturePanoramaDto
  | ExportedCaptureDto
  | ExportedExtractRoomplanDto
  | ExportedFormComponentDto
  | ExportedListDto
  | ExportedReportDto
  | ExportedAnnotationPanoramaDto
  | ExportedSwitchDto;
