/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { ExportedCapturePanoramaV2DtoType } from './exportedCapturePanoramaV2DtoType';
import type { CameraDto } from './cameraDto';

export interface ExportedCapturePanoramaV2Dto {
  id: string;
  type: ExportedCapturePanoramaV2DtoType;
  camera: CameraDto;
}
