/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */

export type FieldType = (typeof FieldType)[keyof typeof FieldType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FieldType = {
  TEXT: 'TEXT',
  SELECT: 'SELECT',
  RADIO: 'RADIO',
  CHECKBOX: 'CHECKBOX',
  FILE: 'FILE',
  EMAIL: 'EMAIL',
  PHONE: 'PHONE',
  DATE: 'DATE',
  TIME: 'TIME',
  TEXTAREA: 'TEXTAREA',
  URL: 'URL',
  NUMBER: 'NUMBER',
  DIVIDER: 'DIVIDER',
  RGBD: 'RGBD',
  SIGNATURE: 'SIGNATURE',
} as const;
