/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { FieldConfigDtoExtensionsItem } from './fieldConfigDtoExtensionsItem';

export interface FieldConfigDto {
  /** @minimum 0 */
  step?: number;
  extensions?: FieldConfigDtoExtensionsItem[];
  unit?: string;
  multiple: boolean;
  editable?: boolean;
  required: boolean;
  personalData?: boolean;
  enabled?: boolean;
  /** @minLength 1 */
  key?: string;
}
