/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { FieldType } from './fieldType';
import type { FieldOptionDto } from './fieldOptionDto';
import type { FieldConfigDto } from './fieldConfigDto';

export interface FieldDto {
  type: FieldType;
  /** @minLength 2 */
  label: string;
  /** @minLength 1 */
  placeholder?: string;
  /** @minimum 1 */
  position: number;
  /** @minItems 2 */
  options?: FieldOptionDto[];
  /** @minLength 2 */
  helpText?: string;
  config: FieldConfigDto;
}
