/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { ArticleType } from './articleType';
import type { ArticleStatus } from './articleStatus';

export type GetArticlesParams = {
  /**
   * @minimum 1
   * @maximum 100
   */
  perPage?: number;
  /**
   * @minimum 1
   */
  page?: number;
  sortBy?: string;
  type?: ArticleType[];
  status?: ArticleStatus[];
  clients?: string[];
  name?: string;
};
