/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { DeliverableStatus } from './deliverableStatus';
import type { DeliverableType } from './deliverableType';

export type GetDeliverablesParams = {
  /**
   * @minimum 1
   * @maximum 100
   */
  perPage?: number;
  /**
   * @minimum 1
   */
  page?: number;
  sortBy?: string;
  deliverableId?: string;
  supplierOrderItemId?: string;
  assetName?: string;
  supplierOrderItemNumber?: string;
  clientId?: string;
  clientNumber?: string;
  deliverableStatus?: DeliverableStatus[];
  deliverableType?: DeliverableType[];
  clientOrderId?: string;
  clientOrderItemId?: string;
  supplierOrderId?: string;
};
