/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { ClientOrderItemStatus } from './clientOrderItemStatus';
import type { DeliverableType } from './deliverableType';

export type GetProjectsParams = {
  /**
   * @minimum 1
   * @maximum 100
   */
  perPage?: number;
  /**
   * @minimum 1
   */
  page?: number;
  sortBy?: string;
  projectId?: string;
  projectName?: string;
  isActive?: boolean[];
  userId?: string;
  articleName?: string;
  clientOrderItemId?: string;
  clientOrderItemStatus?: ClientOrderItemStatus[];
  deliverableType?: DeliverableType[];
};
