/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { LegalStatus } from './legalStatus';
import type { CreateAddressDto } from './createAddressDto';
import type { AccountPreferenceCreateDto } from './accountPreferenceCreateDto';
import type { AccountCreateDto } from './accountCreateDto';

export interface GroupCreateDto {
  accountNumber: string;
  /** @minLength 2 */
  name: string;
  description?: string;
  legalStatus?: LegalStatus;
  companyNumber?: string;
  vatNumber?: string;
  address: CreateAddressDto;
  accountPreference: AccountPreferenceCreateDto;
  contactEmail?: string;
  account: AccountCreateDto;
  billingAddress?: CreateAddressDto;
}
