/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { InvoiceProvider } from './invoiceProvider';
import type { InvoiceType } from './invoiceType';
import type { InvoicePreferencesDtoMiscellaneous } from './invoicePreferencesDtoMiscellaneous';

export interface InvoicePreferencesDto {
  id: string;
  /** Billable account id */
  account: string;
  /** Invoicing provider name */
  invoiceProvider: InvoiceProvider;
  /** External invoicing solution account Id */
  invoiceAccountId: string;
  /** The invoicing periodicity for the account */
  invoiceType: InvoiceType;
  /** Whether the account is billable or not */
  billable: boolean;
  miscellaneous?: InvoicePreferencesDtoMiscellaneous;
}
