/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */

export interface PaginationMeta {
  /** @minimum 1 */
  page: number;
  /** @minimum 1 */
  perPage: number;
  /** @minimum 1 */
  totalCount: number;
  /** @minimum 1 */
  pageCount: number;
  hasPreviousPage: boolean;
  hasNextPage: boolean;
}
