/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { DeliverableProvider } from './deliverableProvider';
import type { DeliverableType } from './deliverableType';
import type { DeliverableStatus } from './deliverableStatus';
import type { AssetDto } from './assetDto';

export interface PaginatedDeliverableDto {
  id: string;
  path: string;
  provider: DeliverableProvider;
  type: DeliverableType;
  status: DeliverableStatus;
  asset?: AssetDto;
  supplierOrderItem?: string;
  supplierOrderItemNumber?: string;
  clientOrderItem: string;
  clientOrderItemNumber: string;
  createdAt: string;
}
