/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */

export interface PaginatedUserDto {
  id: string;
  email: string;
  firstname: string;
  lastname: string;
}
