/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */

export interface PipelineRoomCategoriesDto {
  livingRoom?: string[];
  waterRoom?: string[];
  storageRoom?: string[];
  technicalRoom?: string[];
  ancillaryRoom?: string[];
  circulation?: string[];
  outdoor?: string[];
  commonArea?: string[];
  other?: string[];
}
