/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */

export type PipelineFlowDtoListOrderItem =
  (typeof PipelineFlowDtoListOrderItem)[keyof typeof PipelineFlowDtoListOrderItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PipelineFlowDtoListOrderItem = {
  PROJECT: 'PROJECT',
  ZONE: 'ZONE',
  ROOM: 'ROOM',
  SURFACE: 'SURFACE',
  DAMAGE: 'DAMAGE',
} as const;
