/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { SupplierOrderStatus } from './supplierOrderStatus';
import type { SupplierOrderItemListDto } from './supplierOrderItemListDto';

export interface SupplierOrderDto {
  id: string;
  orderNumber: string;
  supplierName: string;
  supplierAccountNumber: string;
  createdAt: string;
  startDate: string;
  endDate: string;
  totalAmount: number;
  status: SupplierOrderStatus;
  items: SupplierOrderItemListDto[];
  bypassAcceptation?: boolean;
}
