/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { SupplierOrderItemStatus } from './supplierOrderItemStatus';
import type { OrderItemInvoicingStatus } from './orderItemInvoicingStatus';

export interface SupplierOrderItemUpdateDto {
  price: number;
  article?: string;
  clientOrderItem?: string;
  id: string;
  operationalStatus: SupplierOrderItemStatus;
  invoicingStatus?: OrderItemInvoicingStatus;
}
