/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */

export type SupplierOrderStatus =
  (typeof SupplierOrderStatus)[keyof typeof SupplierOrderStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SupplierOrderStatus = {
  SCHEDULED: 'SCHEDULED',
  ACCEPTED: 'ACCEPTED',
  REFUSED: 'REFUSED',
  CANCELED: 'CANCELED',
  DONE: 'DONE',
} as const;
