/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import type { ArticleType } from './articleType';
import type { SupplierOrderItemStatus } from './supplierOrderItemStatus';
import type { OrderItemInvoicingStatus } from './orderItemInvoicingStatus';

export interface SupplierOrderItemListDto {
  id: string;
  itemNumber: string;
  date: string;
  price: number;
  articleName: string;
  assetName: string;
  assetId: string;
  clientOrderItemNumber: string;
  clientOrderItemId: string;
  clientName: string;
  clientAccountNumber: string;
  supplierOrderNumber: string;
  supplierOrderId: string;
  supplierName: string;
  supplierAccountNumber: string;
  articleType?: ArticleType;
  operationalStatus: SupplierOrderItemStatus;
  invoicingStatus: OrderItemInvoicingStatus;
}
