/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */

export type TutorialDtoScreensItem = {
  /** @minLength 2 */
  message: string;
  highlights: string[];
  animationUrl: string;
  /** @minimum 0 */
  position: number;
};
