/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */

export interface UpdateAddressDto {
  /** The name of the address */
  name: string;
  /** The street of the address */
  address1: string;
  /** The street of the address */
  address2?: string;
  /** The city of the address */
  city: string;
  /** The zip code of the address */
  postCode: string;
  /** The country of the address */
  country: string;
  phone?: string;
  unitNumber?: string;
  floor?: number;
  id: string;
}
