/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */

export interface ZohoItemDto {
  id: string;
  /** The unique identifier for the item in Zoho */
  itemZohoId: string;
  /** The price of the item */
  price: number;
  /** The SKU of the item */
  sku: string;
}
