"use strict";
/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.healthCheck = exports.getHealthCheckUrl = exports.getArticleById = exports.getGetArticleByIdUrl = exports.getArticles = exports.getGetArticlesUrl = exports.getDeliverables = exports.getGetDeliverablesUrl = exports.rateForClientOrderItem = exports.getRateForClientOrderItemUrl = exports.getClientOrderById = exports.getGetClientOrderByIdUrl = exports.createClientOrder = exports.getCreateClientOrderUrl = exports.getAllClientOrders = exports.getGetAllClientOrdersUrl = void 0;
const custom_fetch_1 = require("../../custom-fetch");
const getGetAllClientOrdersUrl = (params) => {
    const normalizedParams = new URLSearchParams();
    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? 'null' : value.toString());
        }
    });
    const stringifiedParams = normalizedParams.toString();
    return stringifiedParams.length > 0
        ? `/v1/client-orders?${stringifiedParams}`
        : `/v1/client-orders`;
};
exports.getGetAllClientOrdersUrl = getGetAllClientOrdersUrl;
const getAllClientOrders = (params, options) => __awaiter(void 0, void 0, void 0, function* () {
    return (0, custom_fetch_1.customFetch)((0, exports.getGetAllClientOrdersUrl)(params), Object.assign(Object.assign({}, options), { method: 'GET' }));
});
exports.getAllClientOrders = getAllClientOrders;
const getCreateClientOrderUrl = () => {
    return `/v1/client-orders`;
};
exports.getCreateClientOrderUrl = getCreateClientOrderUrl;
const createClientOrder = (clientOrderCreateDto, options) => __awaiter(void 0, void 0, void 0, function* () {
    return (0, custom_fetch_1.customFetch)((0, exports.getCreateClientOrderUrl)(), Object.assign(Object.assign({}, options), { method: 'POST', headers: Object.assign({ 'Content-Type': 'application/json' }, options === null || options === void 0 ? void 0 : options.headers), body: JSON.stringify(clientOrderCreateDto) }));
});
exports.createClientOrder = createClientOrder;
const getGetClientOrderByIdUrl = (id) => {
    return `/v1/client-orders/${id}`;
};
exports.getGetClientOrderByIdUrl = getGetClientOrderByIdUrl;
const getClientOrderById = (id, options) => __awaiter(void 0, void 0, void 0, function* () {
    return (0, custom_fetch_1.customFetch)((0, exports.getGetClientOrderByIdUrl)(id), Object.assign(Object.assign({}, options), { method: 'GET' }));
});
exports.getClientOrderById = getClientOrderById;
const getRateForClientOrderItemUrl = () => {
    return `/v1/client-order-items/rate`;
};
exports.getRateForClientOrderItemUrl = getRateForClientOrderItemUrl;
const rateForClientOrderItem = (clientOrderItemRateBodyDto, options) => __awaiter(void 0, void 0, void 0, function* () {
    return (0, custom_fetch_1.customFetch)((0, exports.getRateForClientOrderItemUrl)(), Object.assign(Object.assign({}, options), { method: 'POST', headers: Object.assign({ 'Content-Type': 'application/json' }, options === null || options === void 0 ? void 0 : options.headers), body: JSON.stringify(clientOrderItemRateBodyDto) }));
});
exports.rateForClientOrderItem = rateForClientOrderItem;
const getGetDeliverablesUrl = (params) => {
    const normalizedParams = new URLSearchParams();
    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? 'null' : value.toString());
        }
    });
    const stringifiedParams = normalizedParams.toString();
    return stringifiedParams.length > 0
        ? `/v1/deliverables?${stringifiedParams}`
        : `/v1/deliverables`;
};
exports.getGetDeliverablesUrl = getGetDeliverablesUrl;
const getDeliverables = (params, options) => __awaiter(void 0, void 0, void 0, function* () {
    return (0, custom_fetch_1.customFetch)((0, exports.getGetDeliverablesUrl)(params), Object.assign(Object.assign({}, options), { method: 'GET' }));
});
exports.getDeliverables = getDeliverables;
const getGetArticlesUrl = (params) => {
    const normalizedParams = new URLSearchParams();
    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? 'null' : value.toString());
        }
    });
    const stringifiedParams = normalizedParams.toString();
    return stringifiedParams.length > 0
        ? `/v1/articles?${stringifiedParams}`
        : `/v1/articles`;
};
exports.getGetArticlesUrl = getGetArticlesUrl;
const getArticles = (params, options) => __awaiter(void 0, void 0, void 0, function* () {
    return (0, custom_fetch_1.customFetch)((0, exports.getGetArticlesUrl)(params), Object.assign(Object.assign({}, options), { method: 'GET' }));
});
exports.getArticles = getArticles;
const getGetArticleByIdUrl = (id) => {
    return `/v1/articles/${id}`;
};
exports.getGetArticleByIdUrl = getGetArticleByIdUrl;
const getArticleById = (id, options) => __awaiter(void 0, void 0, void 0, function* () {
    return (0, custom_fetch_1.customFetch)((0, exports.getGetArticleByIdUrl)(id), Object.assign(Object.assign({}, options), { method: 'GET' }));
});
exports.getArticleById = getArticleById;
const getHealthCheckUrl = () => {
    return `/v1/healthz`;
};
exports.getHealthCheckUrl = getHealthCheckUrl;
const healthCheck = (options) => __awaiter(void 0, void 0, void 0, function* () {
    return (0, custom_fetch_1.customFetch)((0, exports.getHealthCheckUrl)(), Object.assign(Object.assign({}, options), { method: 'GET' }));
});
exports.healthCheck = healthCheck;
