/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

import { customFetch } from '../../custom-fetch';

import {
  GetAllClientOrders200,
  GetAllClientOrdersParams,
  ClientOrderDto,
  ClientOrderCreateDto,
  ClientOrderItemRateResponseDto,
  ClientOrderItemRateBodyDto,
  GetDeliverables200,
  GetDeliverablesParams,
  GetArticles200,
  GetArticlesParams,
  ArticleDto,
} from './http-schemas';

export type getAllClientOrdersResponse200 = {
  data: GetAllClientOrders200;
  status: 200;
};

export type getAllClientOrdersResponseSuccess =
  getAllClientOrdersResponse200 & {
    headers: Headers;
  };
export type getAllClientOrdersResponse = getAllClientOrdersResponseSuccess;

export const getGetAllClientOrdersUrl = (params?: GetAllClientOrdersParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/client-orders?${stringifiedParams}`
    : `/v1/client-orders`;
};

export const getAllClientOrders = async (
  params?: GetAllClientOrdersParams,
  options?: RequestInit,
): Promise<getAllClientOrdersResponse> => {
  return customFetch<getAllClientOrdersResponse>(
    getGetAllClientOrdersUrl(params),
    {
      ...options,
      method: 'GET',
    },
  );
};

export type createClientOrderResponse201 = {
  data: ClientOrderDto;
  status: 201;
};

export type createClientOrderResponse400 = {
  data: void;
  status: 400;
};

export type createClientOrderResponseSuccess = createClientOrderResponse201 & {
  headers: Headers;
};
export type createClientOrderResponseError = createClientOrderResponse400 & {
  headers: Headers;
};

export type createClientOrderResponse =
  | createClientOrderResponseSuccess
  | createClientOrderResponseError;

export const getCreateClientOrderUrl = () => {
  return `/v1/client-orders`;
};

export const createClientOrder = async (
  clientOrderCreateDto: ClientOrderCreateDto,
  options?: RequestInit,
): Promise<createClientOrderResponse> => {
  return customFetch<createClientOrderResponse>(getCreateClientOrderUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(clientOrderCreateDto),
  });
};

export type getClientOrderByIdResponse200 = {
  data: ClientOrderDto;
  status: 200;
};

export type getClientOrderByIdResponse404 = {
  data: void;
  status: 404;
};

export type getClientOrderByIdResponseSuccess =
  getClientOrderByIdResponse200 & {
    headers: Headers;
  };
export type getClientOrderByIdResponseError = getClientOrderByIdResponse404 & {
  headers: Headers;
};

export type getClientOrderByIdResponse =
  | getClientOrderByIdResponseSuccess
  | getClientOrderByIdResponseError;

export const getGetClientOrderByIdUrl = (id: string) => {
  return `/v1/client-orders/${id}`;
};

export const getClientOrderById = async (
  id: string,
  options?: RequestInit,
): Promise<getClientOrderByIdResponse> => {
  return customFetch<getClientOrderByIdResponse>(getGetClientOrderByIdUrl(id), {
    ...options,
    method: 'GET',
  });
};

export type rateForClientOrderItemResponse200 = {
  data: ClientOrderItemRateResponseDto;
  status: 200;
};

export type rateForClientOrderItemResponse201 = {
  data: ClientOrderItemRateResponseDto;
  status: 201;
};

export type rateForClientOrderItemResponse400 = {
  data: void;
  status: 400;
};

export type rateForClientOrderItemResponseSuccess = (
  | rateForClientOrderItemResponse200
  | rateForClientOrderItemResponse201
) & {
  headers: Headers;
};
export type rateForClientOrderItemResponseError =
  rateForClientOrderItemResponse400 & {
    headers: Headers;
  };

export type rateForClientOrderItemResponse =
  | rateForClientOrderItemResponseSuccess
  | rateForClientOrderItemResponseError;

export const getRateForClientOrderItemUrl = () => {
  return `/v1/client-order-items/rate`;
};

export const rateForClientOrderItem = async (
  clientOrderItemRateBodyDto: ClientOrderItemRateBodyDto,
  options?: RequestInit,
): Promise<rateForClientOrderItemResponse> => {
  return customFetch<rateForClientOrderItemResponse>(
    getRateForClientOrderItemUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(clientOrderItemRateBodyDto),
    },
  );
};

export type getDeliverablesResponse200 = {
  data: GetDeliverables200;
  status: 200;
};

export type getDeliverablesResponseSuccess = getDeliverablesResponse200 & {
  headers: Headers;
};
export type getDeliverablesResponse = getDeliverablesResponseSuccess;

export const getGetDeliverablesUrl = (params?: GetDeliverablesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/deliverables?${stringifiedParams}`
    : `/v1/deliverables`;
};

export const getDeliverables = async (
  params?: GetDeliverablesParams,
  options?: RequestInit,
): Promise<getDeliverablesResponse> => {
  return customFetch<getDeliverablesResponse>(getGetDeliverablesUrl(params), {
    ...options,
    method: 'GET',
  });
};

export type getArticlesResponse200 = {
  data: GetArticles200;
  status: 200;
};

export type getArticlesResponseSuccess = getArticlesResponse200 & {
  headers: Headers;
};
export type getArticlesResponse = getArticlesResponseSuccess;

export const getGetArticlesUrl = (params?: GetArticlesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/articles?${stringifiedParams}`
    : `/v1/articles`;
};

export const getArticles = async (
  params?: GetArticlesParams,
  options?: RequestInit,
): Promise<getArticlesResponse> => {
  return customFetch<getArticlesResponse>(getGetArticlesUrl(params), {
    ...options,
    method: 'GET',
  });
};

export type getArticleByIdResponse200 = {
  data: ArticleDto;
  status: 200;
};

export type getArticleByIdResponseSuccess = getArticleByIdResponse200 & {
  headers: Headers;
};
export type getArticleByIdResponse = getArticleByIdResponseSuccess;

export const getGetArticleByIdUrl = (id: string) => {
  return `/v1/articles/${id}`;
};

export const getArticleById = async (
  id: string,
  options?: RequestInit,
): Promise<getArticleByIdResponse> => {
  return customFetch<getArticleByIdResponse>(getGetArticleByIdUrl(id), {
    ...options,
    method: 'GET',
  });
};

export type healthCheckResponse200 = {
  data: void;
  status: 200;
};

export type healthCheckResponseSuccess = healthCheckResponse200 & {
  headers: Headers;
};
export type healthCheckResponse = healthCheckResponseSuccess;

export const getHealthCheckUrl = () => {
  return `/v1/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<healthCheckResponse> => {
  return customFetch<healthCheckResponse>(getHealthCheckUrl(), {
    ...options,
    method: 'GET',
  });
};
