/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';

import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';

import {
  getAllClientOrdersHandler,
  createClientOrderHandler,
  getClientOrderByIdHandler,
  rateForClientOrderItemHandler,
  getDeliverablesHandler,
  getArticlesHandler,
  getArticleByIdHandler,
  healthCheckHandler,
} from './handlers';
import {
  getAllClientOrdersQueryParams,
  createClientOrderBody,
  getClientOrderByIdParams,
  rateForClientOrderItemBody,
  getDeliverablesQueryParams,
  getArticlesQueryParams,
  getArticleByIdParams,
} from './tool-schemas.zod';

const server = new McpServer({
  name: 'proAPIServer',
  version: '1.0.0',
});

server.tool(
  'getAllClientOrders',
  'Get all authenticated client orders',
  {
    queryParams: getAllClientOrdersQueryParams,
  },
  getAllClientOrdersHandler,
);

server.tool(
  'createClientOrder',
  'Create a new client order',
  {
    bodyParams: createClientOrderBody,
  },
  createClientOrderHandler,
);

server.tool(
  'getClientOrderById',
  'Get a client order by Id',
  {
    pathParams: getClientOrderByIdParams,
  },
  getClientOrderByIdHandler,
);

server.tool(
  'rateForClientOrderItem',
  'Get rate for a client order item',
  {
    bodyParams: rateForClientOrderItemBody,
  },
  rateForClientOrderItemHandler,
);

server.tool(
  'getDeliverables',
  'Get all deliverables',
  {
    queryParams: getDeliverablesQueryParams,
  },
  getDeliverablesHandler,
);

server.tool(
  'getArticles',
  'Get all articles',
  {
    queryParams: getArticlesQueryParams,
  },
  getArticlesHandler,
);

server.tool(
  'getArticleById',
  'Get article by ID',
  {
    pathParams: getArticleByIdParams,
  },
  getArticleByIdHandler,
);

server.tool('healthCheck', 'Health check', {}, healthCheckHandler);
export default server;
