"use strict";
/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
Object.defineProperty(exports, "__esModule", { value: true });
const mcp_js_1 = require("@modelcontextprotocol/sdk/server/mcp.js");
const handlers_1 = require("./handlers");
const tool_schemas_zod_1 = require("./tool-schemas.zod");
const server = new mcp_js_1.McpServer({
    name: 'proAPIServer',
    version: '1.0.0',
});
server.tool('getAllClientOrders', 'Get all authenticated client orders', {
    queryParams: tool_schemas_zod_1.getAllClientOrdersQueryParams,
}, handlers_1.getAllClientOrdersHandler);
server.tool('createClientOrder', 'Create a new client order', {
    bodyParams: tool_schemas_zod_1.createClientOrderBody,
}, handlers_1.createClientOrderHandler);
server.tool('getClientOrderById', 'Get a client order by Id', {
    pathParams: tool_schemas_zod_1.getClientOrderByIdParams,
}, handlers_1.getClientOrderByIdHandler);
server.tool('rateForClientOrderItem', 'Get rate for a client order item', {
    bodyParams: tool_schemas_zod_1.rateForClientOrderItemBody,
}, handlers_1.rateForClientOrderItemHandler);
server.tool('getDeliverables', 'Get all deliverables', {
    queryParams: tool_schemas_zod_1.getDeliverablesQueryParams,
}, handlers_1.getDeliverablesHandler);
server.tool('getArticles', 'Get all articles', {
    queryParams: tool_schemas_zod_1.getArticlesQueryParams,
}, handlers_1.getArticlesHandler);
server.tool('getArticleById', 'Get article by ID', {
    pathParams: tool_schemas_zod_1.getArticleByIdParams,
}, handlers_1.getArticleByIdHandler);
server.tool('healthCheck', 'Health check', {}, handlers_1.healthCheckHandler);
exports.default = server;
