/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Magma API
 * The API used by Magma front-end
 * OpenAPI spec version: 1.0
 */
import { customFetch } from '../../magma-fetch';
import {
  GetClientsParams,
  ClientCreateDto,
  ClientUpdateDto,
  GetAllClientDeliverableParametersParams,
  ClientDeliverableParametersCreateDto,
  ClientDeliverableParametersUpdateDto,
  GetGroupsParams,
  GroupCreateDto,
  GroupUpdateDto,
  GetSuppliersParams,
  SupplierCreateDto,
  SupplierUpdateDto,
  GetUsersParams,
  UserCreateDto,
  UserUpdateDto,
  UpdateAssetDto,
  GetAssetsParams,
  CreateAssetDto,
  GetArticlesParams,
  ArticleCreateDto,
  ArticleUpdateDto,
  ArticleValidateDto,
  GetDeliverablesParams,
  RejectDeliverableDto,
  ImportDeliverableBody,
  UploadRoomplansBody,
  DeliverableVirtualTourDto,
  SubmittedFormDto,
  UpdateExportedFlowParams,
  ExportedFlowJsonDto,
  OrderResultJsonDto,
  GetClientOrderItemsParams,
  ClientOrderItemCreateDto,
  ClientOrderItemUpdateDto,
  ClientOrderItemBatchUpdateInvoicingStatusDto,
  GetResourceUrlParams,
  UploadResourceParams,
  UploadResourceBody,
  ClientOrderItemRateBodyDto,
  GetSupplierOrdersBySupplierIdParams,
  SupplierOrderUpdateDto,
  GetAllSupplierOrdersParams,
  SupplierOrderCreateDto,
  AmendSupplierOrderDto,
  GetAllClientOrdersByOrderIdParams,
  GetAllClientOrdersParams,
  ClientOrderCreateDto,
  GetSupplierOrderItemsParams,
  SupplierOrderItemBatchUpdateInvoicingStatusDto,
  ImportClientOrdersBody,
  InvoicePreferencesCreateDto,
  InvoicePreferencesUpdateDto,
  GetProjectsParams,
} from './http-schemas';

import {
  getClients,
  createClient,
  getClientByAccountNumber,
  getClientById,
  updateClient,
  getAllClientDeliverableParameters,
  createClientDeliverableParameters,
  getClientDeliverableParametersById,
  updateClientDeliverableParameters,
  getGroups,
  createGroup,
  getGroupByAccountNumber,
  getGroupById,
  updateGroup,
  getSuppliers,
  createSupplier,
  getSupplierByAccountNumber,
  getSupplierById,
  updateSupplier,
  getUsers,
  createUser,
  getUserById,
  updateUser,
  assignUserToAccount,
  unassignUserFromAccount,
  getAssetById,
  updateAsset,
  getAssets,
  createAsset,
  getArticles,
  createArticle,
  getArticleById,
  updateArticle,
  assignArticleToBillableAccount,
  validateArticleConfiguration,
  getRateFromSkuAndAccount,
  getDeliverables,
  getDeliverableById,
  publishDeliverable,
  rejectDeliverable,
  importDeliverable,
  getRoomplans,
  uploadRoomplans,
  cancelDeliverable,
  relaunchDeliverable,
  forceProcessedStatus,
  getVirtualTour,
  editVirtualTour,
  removeWindows,
  resetVirtualTour,
  maskWindows,
  validateDeliverable,
  getFlow,
  getFlowByClientOrderItemId,
  getSubmittedForms,
  updateSubmittedForms,
  getExportedFlow,
  updateExportedFlow,
  getOrderResult,
  updateOrderResult,
  healthCheck,
  getClientOrderItems,
  createClientOrderItem,
  getClientOrderItemById,
  updateClientOrderItemById,
  updateClientOrderItemsInvoicingStatus,
  getResourceUrl,
  uploadResource,
  rateForClientOrderItem,
  cancelClientOrderItem,
  getSupplierOrdersBySupplierId,
  getSupplierOrderById,
  updateSupplierOrderById,
  getAllSupplierOrders,
  createSupplierOrder,
  cancelSupplierOrderById,
  acceptSupplierOrderById,
  refuseSupplierOrderById,
  amendSupplierOrder,
  reproposeSupplierOrder,
  getAllClientOrdersByOrderId,
  getClientOrderById,
  getAllClientOrders,
  createClientOrder,
  getSupplierOrderItems,
  getSupplierOrderItemById,
  updateSupplierOrderItemsInvoicingStatus,
  cancelSupplierOrderItem,
  importClientOrders,
  exportBillableSupplierOrderItems,
  getInvoicePreferencesByAccountNumber,
  createInvoicePreferences,
  updateInvoicePreferences,
  refreshInvoicePreferencesByAccountNumber,
  getProjects,
  getProjectById,
} from './http-client';

import { RequestHandlerExtra } from '@modelcontextprotocol/sdk/shared/protocol.js';
import {
  ServerNotification,
  ServerRequest,
} from '@modelcontextprotocol/sdk/types.js';
/**
 * @summary Get all clients
 */

export type getClientsArgs = {
  queryParams: GetClientsParams;
  options?: RequestInit;
};

export const getClientsHandler = async (
  args: getClientsArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getClients(args.queryParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create client
 */

export type createClientArgs = {
  bodyParams: ClientCreateDto;
  options?: RequestInit;
};

export const createClientHandler = async (
  args: createClientArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await createClient(args.bodyParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get client by account number
 */

export type getClientByAccountNumberArgs = {
  pathParams: {
    accountNumber: string;
  };
  options?: RequestInit;
};

export const getClientByAccountNumberHandler = async (
  args: getClientByAccountNumberArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getClientByAccountNumber(
    args.pathParams.accountNumber,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get client by Id
 */

export type getClientByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const getClientByIdHandler = async (
  args: getClientByIdArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getClientById(args.pathParams.id, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update client
 */

export type updateClientArgs = {
  pathParams: {
    id: string;
  };
  bodyParams: ClientUpdateDto;
  options?: RequestInit;
};

export const updateClientHandler = async (
  args: updateClientArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await updateClient(args.pathParams.id, args.bodyParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all client deliverable parameters
 */

export type getAllClientDeliverableParametersArgs = {
  pathParams: {
    clientId: string;
  };
  queryParams: GetAllClientDeliverableParametersParams;
  options?: RequestInit;
};

export const getAllClientDeliverableParametersHandler = async (
  args: getAllClientDeliverableParametersArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getAllClientDeliverableParameters(
    args.pathParams.clientId,
    args.queryParams,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create client deliverable parameters
 */

export type createClientDeliverableParametersArgs = {
  pathParams: {
    clientId: string;
  };
  bodyParams: ClientDeliverableParametersCreateDto;
  options?: RequestInit;
};

export const createClientDeliverableParametersHandler = async (
  args: createClientDeliverableParametersArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await createClientDeliverableParameters(
    args.pathParams.clientId,
    args.bodyParams,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get client deliverable parameters by Id
 */

export type getClientDeliverableParametersByIdArgs = {
  pathParams: {
    clientId: string;
    id: string;
  };
  options?: RequestInit;
};

export const getClientDeliverableParametersByIdHandler = async (
  args: getClientDeliverableParametersByIdArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getClientDeliverableParametersById(
    args.pathParams.clientId,
    args.pathParams.id,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update client deliverable parameters
 */

export type updateClientDeliverableParametersArgs = {
  pathParams: {
    clientId: string;
    id: string;
  };
  bodyParams: ClientDeliverableParametersUpdateDto;
  options?: RequestInit;
};

export const updateClientDeliverableParametersHandler = async (
  args: updateClientDeliverableParametersArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await updateClientDeliverableParameters(
    args.pathParams.clientId,
    args.pathParams.id,
    args.bodyParams,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all groups
 */

export type getGroupsArgs = {
  queryParams: GetGroupsParams;
  options?: RequestInit;
};

export const getGroupsHandler = async (
  args: getGroupsArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getGroups(args.queryParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create group
 */

export type createGroupArgs = {
  bodyParams: GroupCreateDto;
  options?: RequestInit;
};

export const createGroupHandler = async (
  args: createGroupArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await createGroup(args.bodyParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get group by account number
 */

export type getGroupByAccountNumberArgs = {
  pathParams: {
    accountNumber: string;
  };
  options?: RequestInit;
};

export const getGroupByAccountNumberHandler = async (
  args: getGroupByAccountNumberArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getGroupByAccountNumber(
    args.pathParams.accountNumber,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get group by Id
 */

export type getGroupByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const getGroupByIdHandler = async (
  args: getGroupByIdArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getGroupById(args.pathParams.id, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update group
 */

export type updateGroupArgs = {
  pathParams: {
    id: string;
  };
  bodyParams: GroupUpdateDto;
  options?: RequestInit;
};

export const updateGroupHandler = async (
  args: updateGroupArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await updateGroup(args.pathParams.id, args.bodyParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all suppliers
 */

export type getSuppliersArgs = {
  queryParams: GetSuppliersParams;
  options?: RequestInit;
};

export const getSuppliersHandler = async (
  args: getSuppliersArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getSuppliers(args.queryParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create supplier
 */

export type createSupplierArgs = {
  bodyParams: SupplierCreateDto;
  options?: RequestInit;
};

export const createSupplierHandler = async (
  args: createSupplierArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await createSupplier(args.bodyParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get supplier by account number
 */

export type getSupplierByAccountNumberArgs = {
  pathParams: {
    accountNumber: string;
  };
  options?: RequestInit;
};

export const getSupplierByAccountNumberHandler = async (
  args: getSupplierByAccountNumberArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getSupplierByAccountNumber(
    args.pathParams.accountNumber,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get client by Id
 */

export type getSupplierByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const getSupplierByIdHandler = async (
  args: getSupplierByIdArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getSupplierById(args.pathParams.id, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update supplier
 */

export type updateSupplierArgs = {
  pathParams: {
    id: string;
  };
  bodyParams: SupplierUpdateDto;
  options?: RequestInit;
};

export const updateSupplierHandler = async (
  args: updateSupplierArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await updateSupplier(
    args.pathParams.id,
    args.bodyParams,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all users
 */

export type getUsersArgs = {
  queryParams: GetUsersParams;
  options?: RequestInit;
};

export const getUsersHandler = async (
  args: getUsersArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getUsers(args.queryParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create a new user
 */

export type createUserArgs = {
  bodyParams: UserCreateDto;
  options?: RequestInit;
};

export const createUserHandler = async (
  args: createUserArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await createUser(args.bodyParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get user by Id
 */

export type getUserByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const getUserByIdHandler = async (
  args: getUserByIdArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getUserById(args.pathParams.id, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update an existing user
 */

export type updateUserArgs = {
  pathParams: {
    id: string;
  };
  bodyParams: UserUpdateDto;
  options?: RequestInit;
};

export const updateUserHandler = async (
  args: updateUserArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await updateUser(args.pathParams.id, args.bodyParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Assign an user to account
 */

export type assignUserToAccountArgs = {
  pathParams: {
    id: string;
    accountNumber: string;
  };
  options?: RequestInit;
};

export const assignUserToAccountHandler = async (
  args: assignUserToAccountArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await assignUserToAccount(
    args.pathParams.id,
    args.pathParams.accountNumber,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Unassign an user from account
 */

export type unassignUserFromAccountArgs = {
  pathParams: {
    id: string;
    accountNumber: string;
  };
  options?: RequestInit;
};

export const unassignUserFromAccountHandler = async (
  args: unassignUserFromAccountArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await unassignUserFromAccount(
    args.pathParams.id,
    args.pathParams.accountNumber,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get an asset by id
 */

export type getAssetByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const getAssetByIdHandler = async (
  args: getAssetByIdArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getAssetById(args.pathParams.id, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update an asset
 */

export type updateAssetArgs = {
  pathParams: {
    id: string;
  };
  bodyParams: UpdateAssetDto;
  options?: RequestInit;
};

export const updateAssetHandler = async (
  args: updateAssetArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await updateAsset(args.pathParams.id, args.bodyParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all assets
 */

export type getAssetsArgs = {
  queryParams: GetAssetsParams;
  options?: RequestInit;
};

export const getAssetsHandler = async (
  args: getAssetsArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getAssets(args.queryParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create a new Asset
 */

export type createAssetArgs = {
  bodyParams: CreateAssetDto;
  options?: RequestInit;
};

export const createAssetHandler = async (
  args: createAssetArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await createAsset(args.bodyParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all articles
 */

export type getArticlesArgs = {
  queryParams: GetArticlesParams;
  options?: RequestInit;
};

export const getArticlesHandler = async (
  args: getArticlesArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getArticles(args.queryParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create a new article
 */

export type createArticleArgs = {
  bodyParams: ArticleCreateDto;
  options?: RequestInit;
};

export const createArticleHandler = async (
  args: createArticleArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await createArticle(args.bodyParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get article by ID
 */

export type getArticleByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const getArticleByIdHandler = async (
  args: getArticleByIdArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getArticleById(args.pathParams.id, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update an article
 */

export type updateArticleArgs = {
  pathParams: {
    id: string;
  };
  bodyParams: ArticleUpdateDto;
  options?: RequestInit;
};

export const updateArticleHandler = async (
  args: updateArticleArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await updateArticle(args.pathParams.id, args.bodyParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Assign an article to billable account
 */

export type assignArticleToBillableAccountArgs = {
  pathParams: {
    id: string;
    accountNumber: string;
  };
  options?: RequestInit;
};

export const assignArticleToBillableAccountHandler = async (
  args: assignArticleToBillableAccountArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await assignArticleToBillableAccount(
    args.pathParams.id,
    args.pathParams.accountNumber,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Validate an article configuration
 */

export type validateArticleConfigurationArgs = {
  bodyParams: ArticleValidateDto;
  options?: RequestInit;
};

export const validateArticleConfigurationHandler = async (
  args: validateArticleConfigurationArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await validateArticleConfiguration(args.bodyParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * This endpoint is used to get the rate for a given SKU and account. If a price book is associated with the account, it will be used to determine the rate.
 * @summary Get ZohoItem given a SKU and an account
 */

export type getRateFromSkuAndAccountArgs = {
  options?: RequestInit;
};

export const getRateFromSkuAndAccountHandler = async (
  args: getRateFromSkuAndAccountArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getRateFromSkuAndAccount(options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all deliverables
 */

export type getDeliverablesArgs = {
  queryParams: GetDeliverablesParams;
  options?: RequestInit;
};

export const getDeliverablesHandler = async (
  args: getDeliverablesArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getDeliverables(args.queryParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get deliverable by Id
 */

export type getDeliverableByIdArgs = {
  pathParams: {
    deliverableId: string;
  };
  options?: RequestInit;
};

export const getDeliverableByIdHandler = async (
  args: getDeliverableByIdArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getDeliverableById(args.pathParams.deliverableId, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Set Deliverable status to validated and trigger publication
 */

export type publishDeliverableArgs = {
  pathParams: {
    deliverableId: string;
  };
  options?: RequestInit;
};

export const publishDeliverableHandler = async (
  args: publishDeliverableArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await publishDeliverable(args.pathParams.deliverableId, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Reject the deliverable in QA
 */

export type rejectDeliverableArgs = {
  pathParams: {
    deliverableId: string;
  };
  bodyParams: RejectDeliverableDto;
  options?: RequestInit;
};

export const rejectDeliverableHandler = async (
  args: rejectDeliverableArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await rejectDeliverable(
    args.pathParams.deliverableId,
    args.bodyParams,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Import a new deliverable
 */

export type importDeliverableArgs = {
  pathParams: {
    clientOrderItemId: string;
    type:
      | 'SHOWROOM'
      | 'ROOMPLANS'
      | 'VIRTUAL_TOUR'
      | 'GAUSSIAN_SPLATTING'
      | 'FLYTHROUGH'
      | 'REPORT'
      | 'COSTING'
      | 'LINK'
      | 'ENERGY_PERFORMANCE_DIAGNOSTICS';
  };
  bodyParams: ImportDeliverableBody;
  options?: RequestInit;
};

export const importDeliverableHandler = async (
  args: importDeliverableArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await importDeliverable(
    args.pathParams.clientOrderItemId,
    args.pathParams.type,
    args.bodyParams,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get the current roomplans for a deliverable
 */

export type getRoomplansArgs = {
  pathParams: {
    deliverableId: string;
  };
  options?: RequestInit;
};

export const getRoomplansHandler = async (
  args: getRoomplansArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getRoomplans(args.pathParams.deliverableId, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Upload a new roomplans for a deliverable
 */

export type uploadRoomplansArgs = {
  pathParams: {
    deliverableId: string;
  };
  bodyParams: UploadRoomplansBody;
  options?: RequestInit;
};

export const uploadRoomplansHandler = async (
  args: uploadRoomplansArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await uploadRoomplans(
    args.pathParams.deliverableId,
    args.bodyParams,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Cancel a deliverable
 */

export type cancelDeliverableArgs = {
  pathParams: {
    deliverableId: string;
  };
  options?: RequestInit;
};

export const cancelDeliverableHandler = async (
  args: cancelDeliverableArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await cancelDeliverable(args.pathParams.deliverableId, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Relaunch a deliverable
 */

export type relaunchDeliverableArgs = {
  pathParams: {
    deliverableId: string;
  };
  options?: RequestInit;
};

export const relaunchDeliverableHandler = async (
  args: relaunchDeliverableArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await relaunchDeliverable(args.pathParams.deliverableId, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Force a deliverable to processed status
 */

export type forceProcessedStatusArgs = {
  pathParams: {
    deliverableId: string;
  };
  options?: RequestInit;
};

export const forceProcessedStatusHandler = async (
  args: forceProcessedStatusArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await forceProcessedStatus(
    args.pathParams.deliverableId,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get the virtual tour
 */

export type getVirtualTourArgs = {
  pathParams: {
    deliverableId: string;
  };
  options?: RequestInit;
};

export const getVirtualTourHandler = async (
  args: getVirtualTourArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getVirtualTour(args.pathParams.deliverableId, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Edit the virtual tour
 */

export type editVirtualTourArgs = {
  pathParams: {
    deliverableId: string;
  };
  bodyParams: DeliverableVirtualTourDto;
  options?: RequestInit;
};

export const editVirtualTourHandler = async (
  args: editVirtualTourArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await editVirtualTour(
    args.pathParams.deliverableId,
    args.bodyParams,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Remove windows from the virtual tour
 */

export type removeWindowsArgs = {
  pathParams: {
    deliverableId: string;
  };
  bodyParams: DeliverableVirtualTourDto;
  options?: RequestInit;
};

export const removeWindowsHandler = async (
  args: removeWindowsArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await removeWindows(
    args.pathParams.deliverableId,
    args.bodyParams,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Reset the virtual tour (remove all edits)
 */

export type resetVirtualTourArgs = {
  pathParams: {
    deliverableId: string;
  };
  options?: RequestInit;
};

export const resetVirtualTourHandler = async (
  args: resetVirtualTourArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await resetVirtualTour(args.pathParams.deliverableId, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Mask windows in the virtual tour
 */

export type maskWindowsArgs = {
  pathParams: {
    deliverableId: string;
  };
  options?: RequestInit;
};

export const maskWindowsHandler = async (
  args: maskWindowsArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await maskWindows(args.pathParams.deliverableId, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Validate a deliverable
 */

export type validateDeliverableArgs = {
  pathParams: {
    deliverableId: string;
  };
  options?: RequestInit;
};

export const validateDeliverableHandler = async (
  args: validateDeliverableArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await validateDeliverable(args.pathParams.deliverableId, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get a flow by id
 */

export type getFlowArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const getFlowHandler = async (
  args: getFlowArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getFlow(args.pathParams.id, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get a flow by client order item id
 */

export type getFlowByClientOrderItemIdArgs = {
  pathParams: {
    clientOrderItemId: string;
  };
  options?: RequestInit;
};

export const getFlowByClientOrderItemIdHandler = async (
  args: getFlowByClientOrderItemIdArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getFlowByClientOrderItemId(
    args.pathParams.clientOrderItemId,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get submitted forms by client order item id
 */

export type getSubmittedFormsArgs = {
  pathParams: {
    clientOrderItemId: string;
  };
  options?: RequestInit;
};

export const getSubmittedFormsHandler = async (
  args: getSubmittedFormsArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getSubmittedForms(
    args.pathParams.clientOrderItemId,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create a new submitted form
 */

export type updateSubmittedFormsArgs = {
  pathParams: {
    clientOrderItemId: string;
  };
  bodyParams: SubmittedFormDto[];
  options?: RequestInit;
};

export const updateSubmittedFormsHandler = async (
  args: updateSubmittedFormsArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await updateSubmittedForms(
    args.pathParams.clientOrderItemId,
    args.bodyParams,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get exported flow json by client order item id
 */

export type getExportedFlowArgs = {
  pathParams: {
    clientOrderItemId: string;
  };
  options?: RequestInit;
};

export const getExportedFlowHandler = async (
  args: getExportedFlowArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getExportedFlow(args.pathParams.clientOrderItemId, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update exported flow json by client order item id
 */

export type updateExportedFlowArgs = {
  pathParams: {
    clientOrderItemId: string;
  };
  queryParams: UpdateExportedFlowParams;
  bodyParams: ExportedFlowJsonDto;
  options?: RequestInit;
};

export const updateExportedFlowHandler = async (
  args: updateExportedFlowArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await updateExportedFlow(
    args.pathParams.clientOrderItemId,
    args.bodyParams,
    args.queryParams,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get order result json by client order item id
 */

export type getOrderResultArgs = {
  pathParams: {
    clientOrderItemId: string;
  };
  options?: RequestInit;
};

export const getOrderResultHandler = async (
  args: getOrderResultArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getOrderResult(args.pathParams.clientOrderItemId, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update order result json by client order item id
 */

export type updateOrderResultArgs = {
  pathParams: {
    clientOrderItemId: string;
  };
  bodyParams: OrderResultJsonDto;
  options?: RequestInit;
};

export const updateOrderResultHandler = async (
  args: updateOrderResultArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await updateOrderResult(
    args.pathParams.clientOrderItemId,
    args.bodyParams,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Health check
 */

export type healthCheckArgs = {
  options?: RequestInit;
};

export const healthCheckHandler = async (
  args: healthCheckArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await healthCheck(options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all client order items
 */

export type getClientOrderItemsArgs = {
  queryParams: GetClientOrderItemsParams;
  options?: RequestInit;
};

export const getClientOrderItemsHandler = async (
  args: getClientOrderItemsArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getClientOrderItems(args.queryParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create a client order item
 */

export type createClientOrderItemArgs = {
  bodyParams: ClientOrderItemCreateDto;
  options?: RequestInit;
};

export const createClientOrderItemHandler = async (
  args: createClientOrderItemArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await createClientOrderItem(args.bodyParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get a client order item by Id
 */

export type getClientOrderItemByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const getClientOrderItemByIdHandler = async (
  args: getClientOrderItemByIdArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getClientOrderItemById(args.pathParams.id, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update a client order item by Id
 */

export type updateClientOrderItemByIdArgs = {
  pathParams: {
    id: string;
  };
  bodyParams: ClientOrderItemUpdateDto;
  options?: RequestInit;
};

export const updateClientOrderItemByIdHandler = async (
  args: updateClientOrderItemByIdArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await updateClientOrderItemById(
    args.pathParams.id,
    args.bodyParams,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update invoicing status of client order items
 */

export type updateClientOrderItemsInvoicingStatusArgs = {
  bodyParams: ClientOrderItemBatchUpdateInvoicingStatusDto;
  options?: RequestInit;
};

export const updateClientOrderItemsInvoicingStatusHandler = async (
  args: updateClientOrderItemsInvoicingStatusArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await updateClientOrderItemsInvoicingStatus(
    args.bodyParams,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get a resource by client order item id
 */

export type getResourceUrlArgs = {
  pathParams: {
    clientOrderItemId: string;
  };
  queryParams: GetResourceUrlParams;
  options?: RequestInit;
};

export const getResourceUrlHandler = async (
  args: getResourceUrlArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getResourceUrl(
    args.pathParams.clientOrderItemId,
    args.queryParams,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Upload a resource by client order item id
 */

export type uploadResourceArgs = {
  pathParams: {
    clientOrderItemId: string;
  };
  queryParams: UploadResourceParams;
  bodyParams: UploadResourceBody;
  options?: RequestInit;
};

export const uploadResourceHandler = async (
  args: uploadResourceArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await uploadResource(
    args.pathParams.clientOrderItemId,
    args.bodyParams,
    args.queryParams,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get rate for a client order item
 */

export type rateForClientOrderItemArgs = {
  bodyParams: ClientOrderItemRateBodyDto;
  options?: RequestInit;
};

export const rateForClientOrderItemHandler = async (
  args: rateForClientOrderItemArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await rateForClientOrderItem(args.bodyParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Client order item canceled
 */

export type cancelClientOrderItemArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const cancelClientOrderItemHandler = async (
  args: cancelClientOrderItemArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await cancelClientOrderItem(args.pathParams.id, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all supplier orders by Supplier Id
 */

export type getSupplierOrdersBySupplierIdArgs = {
  pathParams: {
    supplierId: string;
  };
  queryParams: GetSupplierOrdersBySupplierIdParams;
  options?: RequestInit;
};

export const getSupplierOrdersBySupplierIdHandler = async (
  args: getSupplierOrdersBySupplierIdArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getSupplierOrdersBySupplierId(
    args.pathParams.supplierId,
    args.queryParams,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get a supplier order by Id
 */

export type getSupplierOrderByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const getSupplierOrderByIdHandler = async (
  args: getSupplierOrderByIdArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getSupplierOrderById(args.pathParams.id, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update a supplier order by Id
 */

export type updateSupplierOrderByIdArgs = {
  pathParams: {
    id: string;
  };
  bodyParams: SupplierOrderUpdateDto;
  options?: RequestInit;
};

export const updateSupplierOrderByIdHandler = async (
  args: updateSupplierOrderByIdArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await updateSupplierOrderById(
    args.pathParams.id,
    args.bodyParams,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all supplier orders
 */

export type getAllSupplierOrdersArgs = {
  queryParams: GetAllSupplierOrdersParams;
  options?: RequestInit;
};

export const getAllSupplierOrdersHandler = async (
  args: getAllSupplierOrdersArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getAllSupplierOrders(args.queryParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create a new supplier order
 */

export type createSupplierOrderArgs = {
  bodyParams: SupplierOrderCreateDto;
  options?: RequestInit;
};

export const createSupplierOrderHandler = async (
  args: createSupplierOrderArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await createSupplierOrder(args.bodyParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Cancel a supplier order by Id
 */

export type cancelSupplierOrderByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const cancelSupplierOrderByIdHandler = async (
  args: cancelSupplierOrderByIdArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await cancelSupplierOrderById(args.pathParams.id, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Accept a supplier order by Id
 */

export type acceptSupplierOrderByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const acceptSupplierOrderByIdHandler = async (
  args: acceptSupplierOrderByIdArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await acceptSupplierOrderById(args.pathParams.id, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Accept a supplier order by Id
 */

export type refuseSupplierOrderByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const refuseSupplierOrderByIdHandler = async (
  args: refuseSupplierOrderByIdArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await refuseSupplierOrderById(args.pathParams.id, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Amend Supplier order
 */

export type amendSupplierOrderArgs = {
  pathParams: {
    id: string;
  };
  bodyParams: AmendSupplierOrderDto;
  options?: RequestInit;
};

export const amendSupplierOrderHandler = async (
  args: amendSupplierOrderArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await amendSupplierOrder(
    args.pathParams.id,
    args.bodyParams,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create a new supplier order with new conditions. Cancels the previous one.
 */

export type reproposeSupplierOrderArgs = {
  pathParams: {
    id: string;
  };
  bodyParams: SupplierOrderCreateDto;
  options?: RequestInit;
};

export const reproposeSupplierOrderHandler = async (
  args: reproposeSupplierOrderArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await reproposeSupplierOrder(
    args.pathParams.id,
    args.bodyParams,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all client orders by Client Id
 */

export type getAllClientOrdersByOrderIdArgs = {
  pathParams: {
    clientId: string;
  };
  queryParams: GetAllClientOrdersByOrderIdParams;
  options?: RequestInit;
};

export const getAllClientOrdersByOrderIdHandler = async (
  args: getAllClientOrdersByOrderIdArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getAllClientOrdersByOrderId(
    args.pathParams.clientId,
    args.queryParams,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get a client order by Id
 */

export type getClientOrderByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const getClientOrderByIdHandler = async (
  args: getClientOrderByIdArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getClientOrderById(args.pathParams.id, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all client orders
 */

export type getAllClientOrdersArgs = {
  queryParams: GetAllClientOrdersParams;
  options?: RequestInit;
};

export const getAllClientOrdersHandler = async (
  args: getAllClientOrdersArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getAllClientOrders(args.queryParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create a new client order
 */

export type createClientOrderArgs = {
  bodyParams: ClientOrderCreateDto;
  options?: RequestInit;
};

export const createClientOrderHandler = async (
  args: createClientOrderArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await createClientOrder(args.bodyParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all supplier order items
 */

export type getSupplierOrderItemsArgs = {
  queryParams: GetSupplierOrderItemsParams;
  options?: RequestInit;
};

export const getSupplierOrderItemsHandler = async (
  args: getSupplierOrderItemsArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getSupplierOrderItems(args.queryParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get a supplier order item by Id
 */

export type getSupplierOrderItemByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const getSupplierOrderItemByIdHandler = async (
  args: getSupplierOrderItemByIdArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getSupplierOrderItemById(args.pathParams.id, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update invoicing status of supplier order items
 */

export type updateSupplierOrderItemsInvoicingStatusArgs = {
  bodyParams: SupplierOrderItemBatchUpdateInvoicingStatusDto;
  options?: RequestInit;
};

export const updateSupplierOrderItemsInvoicingStatusHandler = async (
  args: updateSupplierOrderItemsInvoicingStatusArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await updateSupplierOrderItemsInvoicingStatus(
    args.bodyParams,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Supplier order item canceled
 */

export type cancelSupplierOrderItemArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const cancelSupplierOrderItemHandler = async (
  args: cancelSupplierOrderItemArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await cancelSupplierOrderItem(args.pathParams.id, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Import new client orders
 */

export type importClientOrdersArgs = {
  pathParams: {
    clientId: string;
  };
  bodyParams: ImportClientOrdersBody;
  options?: RequestInit;
};

export const importClientOrdersHandler = async (
  args: importClientOrdersArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await importClientOrders(
    args.pathParams.clientId,
    args.bodyParams,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Export billable supplier order items
 */

export type exportBillableSupplierOrderItemsArgs = {
  options?: RequestInit;
};

export const exportBillableSupplierOrderItemsHandler = async (
  args: exportBillableSupplierOrderItemsArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await exportBillableSupplierOrderItems(options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get invoice preferences by account number
 */

export type getInvoicePreferencesByAccountNumberArgs = {
  pathParams: {
    accountNumber: string;
  };
  options?: RequestInit;
};

export const getInvoicePreferencesByAccountNumberHandler = async (
  args: getInvoicePreferencesByAccountNumberArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getInvoicePreferencesByAccountNumber(
    args.pathParams.accountNumber,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create invoice preferences
 */

export type createInvoicePreferencesArgs = {
  bodyParams: InvoicePreferencesCreateDto;
  options?: RequestInit;
};

export const createInvoicePreferencesHandler = async (
  args: createInvoicePreferencesArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await createInvoicePreferences(args.bodyParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Update invoice preferences
 */

export type updateInvoicePreferencesArgs = {
  pathParams: {
    invoicePreferenceId: string;
  };
  bodyParams: InvoicePreferencesUpdateDto;
  options?: RequestInit;
};

export const updateInvoicePreferencesHandler = async (
  args: updateInvoicePreferencesArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await updateInvoicePreferences(
    args.pathParams.invoicePreferenceId,
    args.bodyParams,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Refresh invoice preferences by account number
 */

export type refreshInvoicePreferencesByAccountNumberArgs = {
  pathParams: {
    accountNumber: string;
  };
  options?: RequestInit;
};

export const refreshInvoicePreferencesByAccountNumberHandler = async (
  args: refreshInvoicePreferencesByAccountNumberArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await refreshInvoicePreferencesByAccountNumber(
    args.pathParams.accountNumber,
    options,
  );

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all projects
 */

export type getProjectsArgs = {
  queryParams: GetProjectsParams;
  options?: RequestInit;
};

export const getProjectsHandler = async (
  args: getProjectsArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getProjects(args.queryParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get project by Id
 */

export type getProjectByIdArgs = {
  pathParams: {
    projectId: string;
  };
  options?: RequestInit;
};

export const getProjectByIdHandler = async (
  args: getProjectByIdArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getProjectById(args.pathParams.projectId, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};
