/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export interface AddressDto {
  id: string;
  name: string;
  address1: string;
  address2?: string;
  city: string;
  postCode: string;
  country: string;
  phone?: string;
  unitNumber?: string;
  floor?: number;
}
