/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export type AnnotationPanoramaComponentDtoType =
  (typeof AnnotationPanoramaComponentDtoType)[keyof typeof AnnotationPanoramaComponentDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnnotationPanoramaComponentDtoType = {
  ANNOTATION_PANORAMA: 'ANNOTATION_PANORAMA',
} as const;
