/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { AnnotationPanoramaComponentDtoType } from './annotationPanoramaComponentDtoType';
import type { FormDto } from './formDto';

export interface AnnotationPanoramaComponentDto {
  position: number;
  navigation?: string;
  type: AnnotationPanoramaComponentDtoType;
  forms: FormDto[];
}
