/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export type ArticleStatus = (typeof ArticleStatus)[keyof typeof ArticleStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ArticleStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
} as const;
