/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { AddressDto } from './addressDto';

export interface AssetAccessDto {
  id: string;
  address?: AddressDto;
  remote: boolean;
  description?: string;
}
