/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { ComponentsDto } from './componentsDto';

export interface BaseFlowDto {
  components: ComponentsDto;
}
