/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export type CaptureType = (typeof CaptureType)[keyof typeof CaptureType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CaptureType = {
  CAR: 'CAR',
  ROOM: 'ROOM',
  HOUSING: 'HOUSING',
  OTHER: 'OTHER',
  FREE: 'FREE',
} as const;
