/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export type CapturePanoramaV2ComponentDtoType =
  (typeof CapturePanoramaV2ComponentDtoType)[keyof typeof CapturePanoramaV2ComponentDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CapturePanoramaV2ComponentDtoType = {
  CAPTURE_PANORAMA_V2: 'CAPTURE_PANORAMA_V2',
} as const;
