/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { CaptureType } from './captureType';
import type { CaptureAlert } from './captureAlert';
import type { CaptureOrientation } from './captureOrientation';
import type { CaptureFocusMode } from './captureFocusMode';
import type { CaptureConfigParamsDto } from './captureConfigParamsDto';

export interface CaptureConfigDto {
  type: CaptureType;
  alerts?: CaptureAlert[];
  orientation: CaptureOrientation;
  focusMode: CaptureFocusMode;
  viewFinder: boolean;
  stopWatch: boolean;
  captureLimit?: number;
  roomPlan: boolean;
  displayProgressBar: boolean;
  validationThreshold?: number;
  maxValue?: number;
  params: CaptureConfigParamsDto;
}
