/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { AssetDto } from './assetDto';
import type { ClientOrderItemStatus } from './clientOrderItemStatus';
import type { OrderItemInvoicingStatus } from './orderItemInvoicingStatus';

export interface ClientOrderItemListDto {
  /**
   * @minimum 1
   * @maximum 100
   */
  perPage?: number;
  /** @minimum 1 */
  page?: number;
  sortBy?: string;
  id: string;
  itemNumber: string;
  clientName: string;
  clientId: string;
  articleName: string;
  price: number;
  vat: number;
  requiredDeliverableTypes: string[];
  asset: AssetDto;
  orderDate: string;
  dueDate?: string;
  legacyForm?: string;
  operationalStatus: ClientOrderItemStatus;
  invoicingStatus: OrderItemInvoicingStatus;
}
