/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { ClientOrderStatus } from './clientOrderStatus';

export interface ClientOrderListDto {
  id: string;
  orderNumber: string;
  /** Client name */
  clientName: string;
  createdAt: string;
  articlesNames: string[];
  status: ClientOrderStatus;
  expectedDeliverableQuantity: number;
}
