/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { OrderResultJsonDto } from './orderResultJsonDto';

export interface ClientOrderCreateItemDto {
  id?: string;
  article: string;
  reference: string;
  dueDate?: string;
  rateSimulationWorkflowId: string;
  orderResult: OrderResultJsonDto;
}
