/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { ClientOrderItemListDto } from './clientOrderItemListDto';
import type { ClientOrderStatus } from './clientOrderStatus';

export interface ClientOrderDto {
  id: string;
  orderNumber: string;
  items: ClientOrderItemListDto[];
  orderDate: string;
  status: ClientOrderStatus;
  totalAmount: number;
}
