/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { ArticleListResultDto } from './articleListResultDto';
import type { AssetDto } from './assetDto';
import type { ClientOrderDto } from './clientOrderDto';
import type { ClientOrderItemStatus } from './clientOrderItemStatus';
import type { OrderItemInvoicingStatus } from './orderItemInvoicingStatus';

export interface ClientOrderItemDto {
  id: string;
  itemNumber: string;
  article: ArticleListResultDto;
  asset: AssetDto;
  dueDate?: string;
  price: number;
  vat: number;
  clientOrder: ClientOrderDto;
  operationalStatus: ClientOrderItemStatus;
  invoicingStatus: OrderItemInvoicingStatus;
  legacyForm?: string;
  fromODS?: boolean;
  createdAt: string;
  updatedAt: string;
}
