/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export type DeconnectionComponentDtoType =
  (typeof DeconnectionComponentDtoType)[keyof typeof DeconnectionComponentDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeconnectionComponentDtoType = {
  DECONNECTION: 'DECONNECTION',
} as const;
