/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { DeliverableGeometryDtoType } from './deliverableGeometryDtoType';
import type { DeliverableAabb } from './deliverableAabb';

export interface DeliverableGeometryDto {
  geometry_uuid: string;
  path: string;
  type: DeliverableGeometryDtoType;
  aabb?: DeliverableAabb;
  y_clip_min?: number;
  y_clip_max?: number;
}
