/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export interface DeliverableRoomDto {
  room_uuid: string;
  panorama_uuids: string[];
  room_name?: string;
}
