/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export type DeliverableProvider =
  (typeof DeliverableProvider)[keyof typeof DeliverableProvider];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeliverableProvider = {
  GCP: 'GCP',
  AWS: 'AWS',
  SCALEWAY: 'SCALEWAY',
  OODRIVE: 'OODRIVE',
} as const;
