/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { DeliverableMinimapDtoType } from './deliverableMinimapDtoType';
import type { DeliverableMinimapDtoPanoramaUuidsPoses2dItem } from './deliverableMinimapDtoPanoramaUuidsPoses2dItem';

export interface DeliverableMinimapDto {
  type: DeliverableMinimapDtoType;
  path: string;
  panorama_uuids_poses_2d: DeliverableMinimapDtoPanoramaUuidsPoses2dItem[];
}
