/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export type Device = (typeof Device)[keyof typeof Device];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Device = {
  ANDROID: 'ANDROID',
  IOS: 'IOS',
} as const;
