/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export type ExportedCapturePanoramaDtoType =
  (typeof ExportedCapturePanoramaDtoType)[keyof typeof ExportedCapturePanoramaDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExportedCapturePanoramaDtoType = {
  EXPORTED_CAPTURE_PANORAMA: 'EXPORTED_CAPTURE_PANORAMA',
} as const;
