/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { ClientOrderStatus } from './clientOrderStatus';

export type GetAllClientOrdersParams = {
  /**
   * @minimum 1
   * @maximum 100
   */
  perPage?: number;
  /**
   * @minimum 1
   */
  page?: number;
  sortBy?: string;
  status?: ClientOrderStatus;
  orderNumber?: string;
  clientAccountNumber?: string;
  createdAfter?: string;
  createdBefore?: string;
};
