/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { Paginated } from './paginated';
import type { GetArticles200AllOf } from './getArticles200AllOf';

export type GetArticles200 = Paginated & GetArticles200AllOf;
