/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { Paginated } from './paginated';
import type { GetAllClientOrders200AllOf } from './getAllClientOrders200AllOf';

export type GetAllClientOrders200 = Paginated & GetAllClientOrders200AllOf;
