/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { ListComponentDtoType } from './listComponentDtoType';
import type { BaseFlowDto } from './baseFlowDto';
import type { ListConfigDto } from './listConfigDto';

export interface ListComponentDto {
  position: number;
  navigation?: string;
  type: ListComponentDtoType;
  flow: BaseFlowDto;
  config: ListConfigDto;
}
