/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { ListComponentDisplayMode } from './listComponentDisplayMode';
import type { EmptyStateDto } from './emptyStateDto';
import type { TooltipDto } from './tooltipDto';

export interface ListConfigDto {
  editable: boolean;
  /** @minLength 2 */
  defaultName: string;
  displayMode: ListComponentDisplayMode;
  emptyState: EmptyStateDto;
  tooltip?: TooltipDto;
  /** @minimum 0 */
  minValue?: number;
  /** @minimum 1 */
  maxValue?: number;
  /** @minLength 2 */
  firstButtonLabel?: string;
  /** @minLength 2 */
  secondButtonLabel?: string;
}
