/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { OrderingConfigWorkflowType } from './orderingConfigWorkflowType';
import type { ComponentsDto } from './componentsDto';

export interface OrderingConfigJsonDto {
  workflowType: OrderingConfigWorkflowType;
  components: ComponentsDto;
  ignoreKeys?: string[];
  saveKeys?: string[];
}
