/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export interface PaginationMeta {
  /** @minimum 1 */
  page: number;
  /** @minimum 1 */
  perPage: number;
  /** @minimum 1 */
  totalCount: number;
  /** @minimum 1 */
  pageCount: number;
  hasPreviousPage: boolean;
  hasNextPage: boolean;
}
