/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { DeliverableProvider } from './deliverableProvider';
import type { DeliverableType } from './deliverableType';
import type { DeliverableStatus } from './deliverableStatus';
import type { ClientOrderItemDto } from './clientOrderItemDto';

export interface PaginatedDeliverableDto {
  id: string;
  path: string;
  provider: DeliverableProvider;
  type: DeliverableType;
  status: DeliverableStatus;
  clientOrderItem?: ClientOrderItemDto;
}
