/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { PipelineJsonDto } from './pipelineJsonDto';

export interface PipelineDto {
  id: string;
  name: string;
  description?: string;
  json: PipelineJsonDto;
}
