/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { PipelineImageProcessingDtoTripodRemovalMethod } from './pipelineImageProcessingDtoTripodRemovalMethod';

export interface PipelineImageProcessingDto {
  enhance_contrast?: boolean;
  /**
   * @minItems 2
   * @maxItems 2
   */
  lod?: number[];
  icon_width?: number;
  /**
   * @minimum 0
   * @maximum 255
   */
  wb_target_a?: number;
  /**
   * @minimum 0
   * @maximum 255
   */
  wb_target_b?: number;
  tripod_removal_method?: PipelineImageProcessingDtoTripodRemovalMethod;
  denoise_image?: boolean;
  white_balance?: boolean;
  mask_windows?: boolean;
}
