/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */

export type PlayerVideoComponentDtoType =
  (typeof PlayerVideoComponentDtoType)[keyof typeof PlayerVideoComponentDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlayerVideoComponentDtoType = {
  PLAYER_VIDEO: 'PLAYER_VIDEO',
} as const;
