/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { SurfaceRangeDto } from './surfaceRangeDto';

export interface PricingInformationDto {
  /** The SKU template used for pricing */
  skuTemplate: string;
  /** The name of the article */
  surfaceRanges?: SurfaceRangeDto[];
}
