/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import type { SwitchComponentDtoType } from './switchComponentDtoType';
import type { SwitchCaseDto } from './switchCaseDto';

export interface SwitchComponentDto {
  position: number;
  navigation?: string;
  type: SwitchComponentDtoType;
  cases: SwitchCaseDto[];
}
