/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Pro API
 * The Pro API
 * OpenAPI spec version: 1.1
 */
import { customFetch } from '../../pro-fetch';
import {
  GetAllClientOrdersParams,
  ClientOrderCreateDto,
  ClientOrderItemRateBodyDto,
  GetDeliverablesParams,
  GetArticlesParams,
} from './http-schemas';

import {
  getAllClientOrders,
  createClientOrder,
  getClientOrderById,
  rateForClientOrderItem,
  getDeliverables,
  getArticles,
  getArticleById,
  healthCheck,
} from './http-client';

import { RequestHandlerExtra } from '@modelcontextprotocol/sdk/shared/protocol.js';
import {
  ServerNotification,
  ServerRequest,
} from '@modelcontextprotocol/sdk/types.js';
/**
 * @summary Get all authenticated client orders
 */

export type getAllClientOrdersArgs = {
  queryParams: GetAllClientOrdersParams;
  options?: RequestInit;
};

export const getAllClientOrdersHandler = async (
  args: getAllClientOrdersArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getAllClientOrders(args.queryParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Create a new client order
 */

export type createClientOrderArgs = {
  bodyParams: ClientOrderCreateDto;
  options?: RequestInit;
};

export const createClientOrderHandler = async (
  args: createClientOrderArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await createClientOrder(args.bodyParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get a client order by Id
 */

export type getClientOrderByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const getClientOrderByIdHandler = async (
  args: getClientOrderByIdArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getClientOrderById(args.pathParams.id, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get rate for a client order item
 */

export type rateForClientOrderItemArgs = {
  bodyParams: ClientOrderItemRateBodyDto;
  options?: RequestInit;
};

export const rateForClientOrderItemHandler = async (
  args: rateForClientOrderItemArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await rateForClientOrderItem(args.bodyParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all deliverables
 */

export type getDeliverablesArgs = {
  queryParams: GetDeliverablesParams;
  options?: RequestInit;
};

export const getDeliverablesHandler = async (
  args: getDeliverablesArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getDeliverables(args.queryParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get all articles
 */

export type getArticlesArgs = {
  queryParams: GetArticlesParams;
  options?: RequestInit;
};

export const getArticlesHandler = async (
  args: getArticlesArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getArticles(args.queryParams, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Get article by ID
 */

export type getArticleByIdArgs = {
  pathParams: {
    id: string;
  };
  options?: RequestInit;
};

export const getArticleByIdHandler = async (
  args: getArticleByIdArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await getArticleById(args.pathParams.id, options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};

/**
 * @summary Health check
 */

export type healthCheckArgs = {
  options?: RequestInit;
};

export const healthCheckHandler = async (
  args: healthCheckArgs,
  extra: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const options = args.options ?? {};
  const headers: Record<string, string> = {};
  if (extra.sessionId) {
    headers['mcp-session-id'] = extra.sessionId;
  }
  options.headers = headers;
  const res = await healthCheck(options);

  return {
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify(res),
      },
    ],
  };
};
